### ISSUE TITLE
String concatenation doesn't seem to work inside function calls

### ISSUE THREAD

**Issue by mattbasta** [mozilla/nunjucks#100]
``` django
{% set url = media('/docs/privacy/' + language + '.html') %}
```

The above expression throws a parse error locally:

```
parseSignature: expected comma after expression
```

Investigating to try to figure out what might be wrong.

**Comment by pierre-b** [comment]
Hi guys, do you know what is the operator to concatenate strings?
Looks like the only way is to use the "replace" filter: 'my string _str2' | replace('_str2', string2)

**Comment by carljm** [comment]
The `+` operator should work fine.

**Comment by wenlittleoil** [comment]
The + operator doesn't work at all, what a pity, it's a common case.
