### ISSUE TITLE
Variables being concatenated instead of summed

### ISSUE THREAD

**Issue by elektray** [mozilla/nunjucks#1010]
I would like to sum two variables with Nunjucks but the output is the concatenation of the value of the two.

I declare the variables as an array in this format:

`setupCredits(`
`[`
  `{month:1, value: 0},`
  `{month: 2, value: 0},`
  `{month: 3, value: 0},`
  `{month: 4, value: 300},`
  `{month: 5, value: 0},`
  `{month: 6, value: 200},`
  `{month: 7, value: 500}`
`]`
`);`

I make the sum as follows:

`{% set clearedMonth =  session.epayelp.credits[month].value + `session.epayelp.paymentAmountForEachMonth[month]` %}`
`{{ clearedMonth  | formatMoney }}`

session.epayelp.paymentAmountForEachMonth[month] is equal to 1146.38 whilst session.epayelp.credits[month].value is equal to 200. The output is 200146.38. Interesting enough if I swap the order the output is 1146.38

**Comment by ArmorDarks** [comment]
Can you provide more accurate example of what you're doing? What's behind `setupCredits` function, and what going on in `sessesion.epayelp` object?

**Comment by elektray** [comment]
@ArmorDarks Of course!!! The application uses Nunjucks and Express.

The `setupCredits` functions assigns the credit array for the particular sesison.
 ' setupCredits = function (credits) {'
    'req.session.epayelp.credits = credits;'
  '};'

The `session.epayelp` object is an array with a similar structure. It is generated as follows:

`// Amount paid for each month`
    `req.session.epayelp.paymentAmountForEachMonth = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];`

  `  for (i = 1; i < 13; i++) {`
      `req.session.epayelp.paymentMonthCount = 0;`
    `  for (n = 0; n < payments.length; n++) {`
     `   for (allocatedir = 0; allocatedir < payments[n].allocated.length; allocatedir++) {`
        `  if (payments[n].allocated[allocatedir].month == i) {`
        `    req.session.epayelp.paymentMonthCount = req.session.epayelp.paymentMonthCount + payments[n].allocated[allocatedir].amount;`
  `        }`
      `  }`
`      }`

Let me know if you need more code, I don't want to bombard you will pages of code.

**Comment by ArmorDarks** [comment]
Small tip: use [fanced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks) to output your code. It will make it easier to read for others :)

Your code still looks to me quite enigmatic, though, so I can't tell where the issue lays straight away.

My wild guess is that one of values is a string.

Try to `typeof` `session.epayelp.credits[month].value` and `session.epayelp.paymentAmountForEachMonth[month]` in Nunjucks. You will need to create small Nunjucks filter or global function which will `console.log` `typeof`.

You can also try to replace your complex logic with some static values, which that logic supposed to return. That way you will be sure that it indeed returns intended values, and if it fixes an issue, at least you will know vector in which you should look for your potential troublemaker.
