### ISSUE TITLE
dynamically added nunjucks dont have access to javascript functions or variables

### ISSUE THREAD

**Issue by sudhirbeldar** [mozilla/nunjucks#1013]
Hello team, 

I am facing a issue where I have rendered a nunjucks file from browser js like show below

$('.middle-content').html(nunjucks.render('account-verification.njk')

account-verification.njk is login form where I need have some validations for which I have validate.js in place. But my validations doesn't work.
Now, the exact things works perfectly where in this njk is loaded from begining.

Also, If I add some logic on input fields to check input values from user, which is handled in javascript function in other .js file, its not working.
But if I write a <script> in same .njk file, its working.

Can someone help me, how to dynamically render nunjucks file so that other jquery and javascript functions will be available without doing anything... or let me know if I am missing something in render method.

**Comment by ArmorDarks** [comment]
I'm not sure about why exactly it happens, but my guess is it's because you're rendering Nunjucks lately. Now think, it means that all your event listeners and so on will be called before DOM actually receives anything from Nunjucks, thus targeting non-existing nodes, selectors returning nothing.

**Comment by sudhirbeldar** [comment]
@ArmorDarks  Thanks for reverting on this. But there must be something so that I can handle this case. Is there?

Or is there any other way to implement this?

**Comment by ArmorDarks** [comment]
I didn't have much experience with client-side Nunjucks. We're mostly using it for statically rendered content, while React seems to be much more appropriate and easier to work with when it comes to client-side rendering.

If what I've described indeed a source of issue, you need to explore how to add event listeners to yet not existing elements. For instance, [here](https://stackoverflow.com/questions/10920355/attaching-click-event-to-a-jquery-object-not-yet-added-to-the-dom).

**Comment by fdintino** [comment]
@sudhirbeldar you can pass a callback as the third argument to `nunjucks.render`, so you could do something like this:

```javascript
nunjucks.render('account-verification.njk', {}, function callback(err, res) {
    if (err) throw(err);
    $('.middle-content').html(res);
    // Validation goes here
});
```

**Comment by fdintino** [comment]
Since this is a support question rather than a bug, and we haven't heard back from the ticket creator in several months, I'm going to mark it as closed.
