### ISSUE TITLE
fail to extends layout using multiple templates dirs

### ISSUE THREAD

**Issue by calidion** [mozilla/nunjucks#1016]
for dirs:

```
[ '/home/eric/Sites/gitlab.com/user/test/vig/templates/views',
  '/home/eric/Sites/gitlab.com/user/src/templates/views',
  '/home/eric/Sites/gitlab.com/user/templates/views' ]
```

and
one template file named `login.html` in dir `src/templates/views`.
wants to  use the layout name `layout.html` in dir `test/vig/templates/views`

then it fail to resolve the layout and issue an error like the following:

```
{ Template render error: (/home/eric/Sites/gitlab.com/user/src/templates/views/user/login.html)
  Template render error: (/home/eric/Sites/gitlab.com/user/src/templates/views/user/login.html)
  Error: template not found: /home/eric/Sites/gitlab.com/user/src/templates/views/layout.html
```

**Comment by ArmorDarks** [comment]
Can you show your templates? Particularly, `extend` parts.

**Comment by fdintino** [comment]
Since we haven't heard back from @calidion, and it doesn't sound like it's a bug in nunjucks, but rather a misconfiguration issue or a typo in his or her templates, I'm going to close out this issue. @calidion if you are able to provide more information, feel free to reopen the ticket.
