### ISSUE TITLE
error

### ISSUE THREAD

**Issue by imsheng** [mozilla/nunjucks#1018]
![image](https://user-images.githubusercontent.com/10435075/28814585-c477535e-76d0-11e7-99b3-b016cd24ac7e.png)

html:
`<div class="col-md-3"><p><a href="#province_{{ province.id }}_wrap"><span class="{{ province.id }}">{{ province.title }}</span></a></p></div>`

**Comment by ArmorDarks** [comment]
Hi

Your error coming from jQuery, it isn't related to Nunjucks

**Comment by imsheng** [comment]
thank you.
