### ISSUE TITLE
 SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by WingGao** [mozilla/nunjucks#1023]
if there's strange char in a template file, the `compile` function will throw this error
![image](https://user-images.githubusercontent.com/1698794/29409878-c730a494-8380-11e7-9198-067eef95bdb0.png)
here is the file 
```html
<script>
console.log("1 ")
</script>
```

**Comment by fdintino** [comment]
I'm unable to reproduce issues with unicode characters in the input, either in template files or in direct calls to the `compile` function. Could you provide a more detailed example? Your screenshot is just of a file that has `console.log("…")`, which is not a template, and then you have a separate script file that logs the number 1?

**Comment by fdintino** [comment]
Closing this due to lack of feedback (I'm trying to triage the open issues on this repository, as there are quite a few). @WingGao feel free to reopen if you can provide additional information.
