### ISSUE TITLE
请问如何输出代码?

### ISSUE THREAD

**Issue by xinnian1992** [mozilla/nunjucks#1025]
我想在模板里显示代码如微信模板，但是被解析了，请指点,谢谢诶
{{first.DATA}}
内容:{{content.DATA}}
时间:{{time.DATA}}
{{remark.DATA}}

**Comment by dayfine** [comment]
you mean the rendering the actual code? Use <pre></pre>tag and stringify your code inside?

**Comment by zhuweiyou** [comment]
```
{% verbatim %}
{{first.DATA}}
内容:{{content.DATA}}
时间:{{time.DATA}}
{{remark.DATA}}
{% endverbatim %}
```

**Comment by xinnian1992** [comment]
谢谢

**Comment by zhuweiyou** [comment]
@xinnian1992  {% row %} 或许也可以，这两等价的

**Comment by xinnian1992** [comment]
ok，谢谢

**Comment by fdintino** [comment]
Seems like this was resolved.
