### ISSUE TITLE
Slice filter returns array of arrays

### ISSUE THREAD

**Issue by mikkna** [mozilla/nunjucks#1026]
This could be the preferred outcome for all I know, but using `| slice(n)` slices to the correct length, but also maps all objects in the array to arrays. 

Steps to reproduce:
```
{% set arr = [{
    'foo': 'bar'
}, {
    'foo': 'buzz'
}] %}

{% for item in arr | slice(1) %}
    {{ item.foo }}
{% endfor %}
```
This produces no output

```
{% for item in arr | slice(1) %}
    {% set item = item[0] %}
    {{ item.foo }}
{% endfor %}
```
This produces the expected outcome ('bar').

See [https://github.com/mozilla/nunjucks/blob/master/src/filters.js#L379](url) for source. An array is pushed into the result array for every slice in the loop. This creates an array of arrays

**Comment by Spown** [comment]
Just curious, why would you want to do it this way anyway?

The simple
```
{% for item in arr %}
    {{ item.foo }}
{% endfor %}
```
does what you want anyway... ``{% for item in arr | slice(n) %}`` is done to "chankify" an array into smaller arrays and this i what it exactly does in your case. If you don't want the end result be an array - then don't use slice.

**Comment by mikkna** [comment]
Since it shares its name with Javascript's native .slice() method, I assumed it would produce the same result. 

The more accurate use case would be this: 
`{% for item in arr | customFIlter | slice(5) %}`
where arr is an array of 10 items, customFilter is used to sort the array, and then slice is used to only loop through the first 5 elements.

I see that the slice filter is not what I need, but the naming would suggest otherwise

**Comment by Spown** [comment]
Well nunjucks came from Jinja which is a originally a python lib. So the naming isn't js-based. I would suggest to do these kinds of data-for-output-preparation before templating. I.e. slice it in node/browser-js environment and send the sliced chunk to Nunjucks context. Most templating engines aren't designed to host complex computations even if they can perform them. Nunjucks for example does heavy eval'ing and data formatting and produces tons of VM noise under the hood. So sending more data then you actually intend to use and increasing the complexity of data processing can not only reduce productivity, but also destabilize the algorithmic (actually happened to me). 

don't forget to close the issue, cheers.
