### ISSUE TITLE
How to user JSON object in template?

### ISSUE THREAD

**Issue by nxycdl** [mozilla/nunjucks#1031]
const user = {
                username: 'myusername',
                name: 'truename',
                age: 35,
                fam: {
                    sex: 1,
                    name: 2
                },
                list: [{qq: '1', dd: '2'}, {qq: '2', dd: '3'}]
            }
            await this.ctx.render('home/postForm.tpl', user);

in my postForm.tpl
<html>
<head></head>
<body>
<div>
    <input type="text" value="{{username}}">
</div>
</body>
<script> 
    var fam = {{fam}};
    var list = {{list}};
    console.log(myapp.fam);
    console.log(myapp.list);
</script>
</html>

but list is an []object object] , 
how i can get list value

**Comment by ArmorDarks** [comment]
You need to use `|dump` filter on list to dump it "as it is". Also, depending on you autoescaping settings, you might need to pass it through `|safe` filter to prevent escaping.

**Comment by nxycdl** [comment]
Thans you.
 I use this code and get correct value 
var list = {{list|dump|safe}};
    console.log(list);
