### ISSUE TITLE
can nunjucks works in java project?

### ISSUE THREAD

**Issue by yale8848** [mozilla/nunjucks#1032]
i used nunjucks in node project, it work well 👍 . And i hope one day  nunjucks can use in java project.

**Comment by Maktub714** [comment]
it work well too

**Comment by fdintino** [comment]
I wouldn't be able to provide support for it, but I suspect you could run nunjucks with [rhino](https://github.com/mozilla/rhino) in Java.

**Comment by yale8848** [comment]
@fdintino ok，thanks

**Comment by fdintino** [comment]
That's not to say I wouldn't be able to offer guidance if you make a decent effort and get stuck somewhere, particularly if it looks like the fault is with nunjucks. If that happens, feel free to open another ticket.
