### ISSUE TITLE
Filters don't fully allow simple Javascript statements.

### ISSUE THREAD

**Issue by MichMich** [mozilla/nunjucks#1035]
I'm trying to use a ternary operator based in a nunchuck filter.
```
{{myValue | round(myBoolean ? 0 : 2)}}
```
Whenever I use a simple statement like this, the full template stops parsing. The parser gives the following error:

> parseSignature: expected comma after expression

I did some additional tests, and concluded the following:
```
{{myValue | round(1 * 2)}} // works
{{myValue | round(myVar)}} // works
{{myValue | round(myVar * 2)}} // works
{{myValue | round(myBoolean)}} // works

{{myValue | round(!myBoolean)}} // gives error: unexpected token: !
```

It looks like the javascript statements aren't parsed *before* they are injected into the filter function. Is there a clean way around this (other than making an intermediate variable)?

**Comment by MichMich** [comment]
I just figured out the following works:
````
{{myValue | round(0 if myBoolean else 2)}}
````
It's an ok-ish solution, but I would prefer native JS code.

**Comment by ArmorDarks** [comment]
Nunjucks isn't JavaScript. It follows Jinja2 and thus uses Jinja's operators, not JavaScript ones.

**Comment by MichMich** [comment]
Ok, closing this for now. Thanks for the info.

**Comment by ArmorDarks** [comment]
> {{myValue | round(!myBoolean)}} // gives error: unexpected token: !

Same is for this one. It isn't JavaScript.

Instead use `not` operator:

```jinja
{{ myValue | round(not myBoolean) }}
```
