### ISSUE TITLE
Easiest way to use nunjucks in the browser (client-side)?

### ISSUE THREAD

**Issue by Extarys** [mozilla/nunjucks#1036]
I've been using nunjucks in nodejs (server-side for a couple of months and it's amazing.

But I'm trying to figure out how I can use it on the client side

I have my simple html file on cordova but how do I get started with layouts and templating?

I'm just bugged here

Can someone provide an example?

Thanks!

**Comment by ArmorDarks** [comment]
Hi

Basicly, you just write your templates in files whenever you like, then it is highly advised to precompile them as described here https://mozilla.github.io/nunjucks/api.html#precompiling

Then it will be easier to use those templates on client side, and you could use slim build of Nunjucks, without compiler (it will be much smaller).

And you will need something, that will control and install views on client side. Like, say, Backbone.

However, my personal advice  — those days Nunjucks isn't great tool for client-side tasks. It will be much harder to build high amount of interactions using Nunjucks than by just using React\Preact or Vue alone. Not to mention, that Nunjucks won't give you snap and performant way to quickly re-render you views upon changes. At least, right now it is so.

**Comment by Extarys** [comment]
Thanks for the inputs ! Client side wise you are right, I should investigate other paths.
