### ISSUE TITLE
RenderTostring gives Template render error: (unknown path)  Error: template not found: ./textGallery.html

### ISSUE THREAD

**Issue by paramjitkaur** [mozilla/nunjucks#1039]
I have a master template subHeadings.html  that references the child template(imageGallery.html) as follows 
```
<div class="{{categoryRoomNav.type}} track-group">
    <h2>{{ categoryRoomNav.title }}</h2>
        {% include "./imageGallery.html" %} 
</div>
```

but when I am doing 
let result = nunjucks.renderString(subHeadingsTemplate,  subHeadingsData);
I get an error
```
 Template render error: (unknown path)
      Template render error: (unknown path)
      Error: template not found: ./textGallery.html
```

I tried both absolute and relative path but did not work

**Comment by fdintino** [comment]
Closing this as it seems like the original question was adequately answered. @paramjitkaur feel free to reopen if you disagree.

**Comment by sundaycrafts** [comment]
I found the easiest way to solve it.
[renderString() can receive the option on third argument](https://github.com/mozilla/nunjucks/blob/6f3e4a36a71cfd59ddc8c1fc5dcd77b8c24d83f3/nunjucks/src/environment.js#L318) in nunjucks v3.1.3.

So you can tell nunjucks the file location it tried to render like this:

```js
// it would be throw error with given file location
nunjucks.renderString('Hello {{?guest?}', {guest: 'James'}, {path: '/file/location/path'})
```
