### ISSUE TITLE
Did UMD or CommonJS get implemented?

### ISSUE THREAD

**Issue by KayakinKoder** [mozilla/nunjucks#1044]
I worked my way through some issue threads and pull requests but couldn't tell for sure if anything in this realm got implemented.

And thanks for maintaining this awesome project, once my JS skills are (a lot) better I hope to help out.

**Comment by fdintino** [comment]
Hi! Yes, the package is importable in node as a standard commonjs module, and the webpack-generated rollup files in the browser directory of the repo are UMD.

**Comment by KayakinKoder** [comment]
Thanks, maybe I should ask this in rollup.js, but does anyone know how to import nunjucks/browser with rollup?

`import nunj from 'nunjucks'; `

even with `rollup-plugin-node-resolve` and `rollup-plugin-commonjs` throws a lot of warnings, seems like it's not importing the /browser modules.

**Comment by KayakinKoder** [comment]
Turns out `rollup-plugin-node-resolve` was in fact getting the node bundle instead of the /browser bundle. The fix is:

resolve({
    browser: true
})

This tells `rollup-plugin-node-resolve` to look for a `browser` field in package.json https://www.npmjs.com/package/rollup-plugin-node-resolve
