### ISSUE TITLE
addGlobal need async version

### ISSUE THREAD

**Issue by devalexqt** [mozilla/nunjucks#1046]
Will be amazing if addGlobal can run async code.

**Comment by devoidfury** [comment]
Can you expand on that/provide example code of what you'd like to do? What's the use-case for this?

**Comment by ArmorDarks** [comment]
Duplicate of https://github.com/mozilla/nunjucks/issues/819

**Comment by devalexqt** [comment]
Example: get user files from DB and then render page...

**Comment by fdintino** [comment]
Closing as a duplicate of #819
