### ISSUE TITLE
rendering templates via php?

### ISSUE THREAD

**Issue by leotankilevich** [mozilla/nunjucks#1047]
How to render nunjucks template via php?

**Comment by ArmorDarks** [comment]
It would be better option to use Twig or Liquid, which are essentially Jinja/Django templating incarnation for PHP. They are very similar to Nunjucks.

Nunjucks is a JavaScript library. You can't use it for rendering templates with PHP directly.

**Comment by fdintino** [comment]
Yes, if you want to render jinja-style templates in php, your best bet is to use Twig or Liquid.
