### ISSUE TITLE
filter without value

### ISSUE THREAD

**Issue by torloneg** [mozilla/nunjucks#1051]
Can I create a filter that does not receive a value with the character |?
I wanted to create functions like filters that don't need a value. The syntax should be of the type: {{ Now ("en","dddd") }} --> Monday.
To do this with a filter I can use the syntax {{ "" | Now ("it","dddd") }} but I would like to do it in a more compact way.

envNunjucks.addFilter('Now', function(value,language,format ) {

      return moment().locale(language).format(format);
  });

thx

**Comment by ArmorDarks** [comment]
You need to use [`addGlobal`](https://mozilla.github.io/nunjucks/api.html#addglobal) for this
