### ISSUE TITLE
Precompiling for Node?

### ISSUE THREAD

**Issue by rkyoku** [mozilla/nunjucks#1065]
Hi there,

I precompiled my templates to JS, but when trying to load them for SSR inside my Node app, I got an error `window is not defined` (`window.nunjucksPrecompiled = window.nunjucksPrecompiled || {}`)

Is it possible to add an option for the "destination" of templates? I like to have them inside my App namespace. `window.nunjucksPrecompiled` is currently hardcoded inside `precompile-global.js`.

I am using npm scripts as a build tool.

Thanks!

**Comment by ArmorDarks** [comment]
See #995

**Comment by RenaudParis** [comment]
This issue only means people are giving up on precompiling for server-side.

I, on the other hand, think that precompiling should be isomorphic and not depend on a specific feature like the `window` object.

After all, the docs says that templates are cached server-side, which means compilation does work server-side. All I'm asking is to give developers the ability to perform this compilation themselves, by allowing for a custom container for compiled templates (instead of the default `window.nunjucksPrecompiled`).

**Comment by fdintino** [comment]
The precompiled wrapper can be configured; I imagine you could create a commonjs wrapper if you wanted to.

**Comment by RenaudParis** [comment]
Yeah I saw that wrapper option, and indeed maybe I could create my own. But
I'd prefer that a simple option be available to change the hardcoded
window.nunjucksPrecompiled, rather than every single developer needing
precompiled templates server-side had to create said wrapper :)

If this is flexibility is hard to add, please do tell, so that we can
understand better.

In that case, I would maybe create that wrapper and share it here.

Le mar. 13 févr. 2018 à 00:32, Frankie Dintino <notifications@github.com> a
écrit :

**Comment by fdintino** [comment]
Yes, please do. I would definitely add this functionality to nunjucks, but I'm not quite clear on what this should look like, so seeing an example would be helpful.

**Comment by ArmorDarks** [comment]
I wonder does precompiling at all gives any benefits on serverside? Isn't after full compilation template will be cached anyway, thus performance difference would be neglectable?

**Comment by RenaudParis** [comment]
Okay I'll soon look into it!

Le mar. 13 févr. 2018 à 00:42, Frankie Dintino <notifications@github.com> a
écrit :

**Comment by RenaudParis** [comment]
You're right, I read in the docs that the template would be cached.

But if I get to choose, I'd rather have the same behavior client-side and
server-side: always use precompiled templates and use the same App
structure.

That's what I did back then with doT and Hbs anyway.

Maybe it's just my preference and I'm overcomplicating things, but I do not
seem to be the only one expecting this, as I saw in some other issues.

Le mar. 13 févr. 2018 à 01:03, Serj Lavrin <notifications@github.com> a
écrit :

**Comment by sidvishnoi** [comment]
I'm working on a project where I need to store the pre-compiled templates in the filesystem. I'm trying to make it work with as many template engines as possible. 

For rendering compiled templates with Pug, I saved a serialization as:
``` js
module.exports = function render(locals, pugRuntime) {
   // <serialized template uses pugRuntime and locals>
   // return rendered string
 } 
```

I think it would be useful if a similar API can be provided with nunjucks along with a lightweight runtime.

**Comment by ogonkov** [comment]
@fdintino is right, using custom wrapper + loader makes the trick.

I'm personally use it to remove `window` in my loader like that:

Creates custom wrapper that writes precompiled templates to some variable:

https://github.com/ogonkov/nunjucks-loader/blob/136293fe4e73d0dcc59aff205ae21da7b6b0ba85/src/precompile/local-var-wrapper.js#L17-L21

webpack loader writes it to loader output:

https://github.com/ogonkov/nunjucks-loader/blob/136293fe4e73d0dcc59aff205ae21da7b6b0ba85/src/loader.js#L51

For NodeJS, you need do the same, but write it to some kind of file, that will export your precompiled templates via `module.exports`.

Then i create new `Environment` with Nunjucks loader, that accept precompiled template (without `window`) as param:

https://github.com/ogonkov/nunjucks-loader/blob/136293fe4e73d0dcc59aff205ae21da7b6b0ba85/src/runtime.js#L7

I think it should work without `webpack` by generating this precompiled templates, but Nunjuncks loader should inherit or borrow methods for `getSource` from [`NodeResolveLoader`](https://github.com/mozilla/nunjucks/blob/1485a44297f1fef3dfd5db0d8e7e047ed1709822/nunjucks/src/node-loaders.js#L89)

**Comment by fdintino** [comment]
In case it's helpful for anyone, this is the webpack nunjucks loader I wrote for myself a little while back:

```javascript
var fs = require('fs');
var path = require('path');
const loaderUtils = require('loader-utils');
const nunjucks = require('nunjucks');

class NunjucksLoader extends nunjucks.Loader {
  init(searchPaths, sourceFoundCallback) {
    this.sourceFoundCallback = sourceFoundCallback;
    if (searchPaths) {
      searchPaths = Array.isArray(searchPaths) ? searchPaths : [searchPaths];
      // For windows, convert to forward slashes
      this.searchPaths = searchPaths.map(path.normalize);
    } else {
      this.searchPaths = ['.'];
    }
  }
  getSource(name) {
    const paths = this.searchPaths.map(p => path.resolve(path.resolve(p), name));
    const fullpath = paths.find(p => fs.existsSync(p));

    if (!fullpath) {
      return null;
    }

    this.sourceFoundCallback(fullpath);

    return {
      src: fs.readFileSync(fullpath, 'utf-8'),
      path: fullpath,
      noCache: this.noCache
    };
  }
}

module.exports = function nunjucksLoader(content) {
  if (this.cacheable) {
    this.cacheable();
  }
  const cb = this.async();
  const opt = loaderUtils.getOptions(this) || {};
  const config = opt.config || {};
  const {searchPaths} = opt;
  let context = opt.context;

  if (typeof context === 'string') {
    this.addDependency(context);
    delete require.cache[require.resolve(context)];
    context = require(context); // eslint-disable-line global-require
  }

  const Environment = opt.env;
  const loader = new NunjucksLoader(searchPaths, (p) => this.addDependency(p));
  const env = new Environment(loader, config);

  env.renderString(content, context, (err, res) => {
    if (err) {
      cb(err);
    } else {
      cb(null, res);
    }
  });
};
```
