### ISSUE TITLE
Include a specific block from a file

### ISSUE THREAD

**Issue by jeffreymeng** [mozilla/nunjucks#1068]
If it possible to Include only a certain block from a file? So sort of like `include`, but it only includes a certain block from the file.

(Sorry, I'm not quite sure how to word this nicely or add more information, so please ask whatever you need to clarify)

**Comment by ArmorDarks** [comment]
`macro` probably the closest thing you're looking for. You can import it from a file with `macro` declaration and then use.

**Comment by jeffreymeng** [comment]
ok, thanks
