### ISSUE TITLE
Nunjucks 3.1.0 breaking change from 3.0.1: missing browser/

### ISSUE THREAD

**Issue by peets** [mozilla/nunjucks#1070]
I have a build script that expects the file `nunjucks/browser/nunjucks.js` to exist. It doesn't exist anymore in 3.1.0, and I don't see any mention of this file in the changelog.

Where can I find this file now? Can you add this information to the Changelog?

Thanks

**Comment by fdintino** [comment]
how are you installing the package? If you use `npm install nunjucks` the package contains the browser folder. And if you `npm install` from source it will build those files.

**Comment by peets** [comment]
I'm using bower

**Comment by fdintino** [comment]
oh okay, looks like bower doesn't run `postinstall` scripts. I'll have to see what the equivalent is for bower.

**Comment by ArmorDarks** [comment]
How bower happens to be alive still...

**Comment by fdintino** [comment]
@peets try running `bower cache clean` and then reinstalling.

**Comment by peets** [comment]
@fdintino thanks, that works; here's the relevant output from `bower install`

```
bower nunjucks#^3.0.0  not-cached https://github.com/theatlantic/nunjucks-bower.git#^3.0.0
bower nunjucks#^3.0.0  resolve https://github.com/theatlantic/nunjucks-bower.git#^3.0.0
bower nunjucks#^3.0.0  download https://github.com/theatlantic/nunjucks-bower/archive/v3.1.0.tar.gz
bower nunjucks#^3.0.0  extract archive.tar.gz
bower nunjucks#^3.0.0  resolved https://github.com/theatlantic/nunjucks-bower.git#3.1.0
bower nunjucks#^3.0.0  install nunjucks#3.1.0
```
