### ISSUE TITLE
3.1.0 cache bug

### ISSUE THREAD

**Issue by atian25** [mozilla/nunjucks#1074]
it seems that, nunjucks@3.1.0 `noCache: false` is break.

see https://github.com/atian25/nunjucks-cache-bug/blob/master/test/index.test.js

when change to 3.0.1 the test pass.

**Comment by maxcbc** [comment]
Just spent 2 days fighting this. Have experienced this too.

**Comment by fdintino** [comment]
Sorry about that. Working on a fix at this very moment.

**Comment by atian25** [comment]
yes, it fixed.

but still a security warning: https://nodesecurity.io/orgs/eggjs/projects/c0f43ecf-9b21-436c-85b9-dfa163de53e7/26

**Comment by fdintino** [comment]
It looks like that security warning is for the hoek library. It doesn't seem to have anything to do with nunjucks.

**Comment by popomore** [comment]
nunjucks@3.1.2 > chokidar@1.7.0 > fsevents@1.1.3 > node-pre-gyp@0.6.39 > hawk@3.1.3 > hoek@2.16.3

But hoek is in the dependency chain of nunjucks

**Comment by atian25** [comment]
chokidar@2.2.0
