### ISSUE TITLE
traditional for loop

### ISSUE THREAD

**Issue by roosh-t3** [mozilla/nunjucks#1080]
Why there is no loop which should be run till a specific condition is met and incremented on each

like 
```njk
{% for(;i < 5; i++) %}
```

**Comment by ArmorDarks** [comment]
Because this is specific to JavaScript and Java for loop structure. It rarely occurs in other languages.

See answer here https://stackoverflow.com/questions/32701303/loop-by-integer-value-with-nunjucks-templating.

**Comment by roosh-t3** [comment]
what about a condition like this `i <= current + 4 && i <= pages` I maybe missing something here.

**Comment by fdintino** [comment]
Yes, that's easily doable. Something like this, for instance:

```javascript
nunjucks.renderString(
  '{% for i in range(0, max(current + 4, pages)) -%}{{ i }}{%- endfor %}',
  {
    max: Math.max,
    current: 6,
    pages: 9
  });
```
