### ISSUE TITLE
无法实时在线更改文件

### ISSUE THREAD

**Issue by Freen247** [mozilla/nunjucks#1081]
每次更改路由或者文档后，需要重启项目~有点儿不方便

**Comment by fdintino** [comment]
You should pass `noCache: true`, either to [`nunjucks.configure`](https://mozilla.github.io/nunjucks/cn/api.html#configure) or to [`new FileSystemLoader()`](https://mozilla.github.io/nunjucks/cn/api.html#filesystemloader)

**Comment by Freen247** [comment]
get√
