### ISSUE TITLE
Hot to Pass variables to JavaScript in ExpressJS? 

### ISSUE THREAD

**Issue by crazyqipython** [mozilla/nunjucks#1084]
Do you have any idea to render variables use Nunjucks in the JavaScript like the Ejs solution below?

https://stackoverflow.com/questions/16098397/pass-variables-to-javascript-in-expressjs

I try to follow the Ejs style, But it can't work!!

**Comment by ArmorDarks** [comment]
You need to pass variables while configuring Nunjucks environment.

Use `env.addGlobal('myVar', myVar)' for this.

**Comment by crazyqipython** [comment]
That exactly what I want, Thank you
