### ISSUE TITLE
Nunjucks add a random comma

### ISSUE THREAD

**Issue by chemitaxis** [mozilla/nunjucks#1085]
Hi, we are having an issue very strange. 

Nunjucks is adding a comma in the middle of my script tag, is any linit in the template engine? We are adding a big data64 encoded string. The comma is moving depending the size of the data64 string.

![0fd3523d-7a51-4096-950c-40d5c5a4a2a3](https://user-images.githubusercontent.com/1420409/37421143-d529f406-27b8-11e8-982f-1c5be5d7e8d3.jpeg)

Thanks!

**Comment by ArmorDarks** [comment]
Can you show the code, please?

**Comment by chemitaxis** [comment]
Yes, here you have the express configuration:

```
app.set('views', `${config.root}/app/views`);
app.set('view engine', 'nunjucks');
const envNunJucks = nunjucks.configure(`${config.root}/app/views`, {
    autoescape: true,
    noCache: true,
    watch: true,
    express: app
  });
```

And here the code tempalte:

```
<script>
    window.dataBase64 = "{{ dataGenially }}";
    window.dataBase64WithoutCommas = window.dataBase64.replace(/,/g , ''); // we did that to replace the comma, but the comma is assigned randomly
    window.dataParsed = atob(window.dataBase64WithoutCommas);
    window.dataGeniallyOffline = JSON.parse(window.dataParsed);
  </script>
```

The controller code where we pass the data to the view:

```
res.render('offline', {
        title: result.Genially.Name,
        id: req.params.id,
        dataGenially: Buffer.from(JSON.stringify(dataGenially)).toString(
          'base64'
        ),
        fontLinks: fontBuilder.composeGoogleFontLinks(googleFonts),
        customFontTags: fontBuilder.composeCustomStylesTags(
          customFonts,
          idUser
        ),
        uniqueImageSources
      });
```

We have converted the data to data64 to prevent error with json formated code.

Thanks @ArmorDarks !

**Comment by chemitaxis** [comment]
Something important... the "dataGenially" can be a very big data64 string (about 3/4 Mb)

**Comment by devoidfury** [comment]
What kind of data does it contain/can you provide a test case? It'll be helpful to us if we can recreate the issue in public code -- that way we can reproduce the issue and fix it.

**Comment by chemitaxis** [comment]
Ok, I will try to create a small repo to reproduce the error... I can give you or process:

We are attaching the JSON to a window variable to view the data without internet connection. 

We convert the JSON data to a base64 string because we found errors with the "," in the middle of our JSON, and we thought... ok, lets convert this JSON to a data64 string and in the client we convert the data64 string to a normal string, and after to a JSON. But... when we do that, the problem persist, and this comma is added randomly to our code.

It's like the nunjucks template can send all the data to the template, and split it in array or similar... do you know about any limitation with it?

Thanks @devoidfury

**Comment by devoidfury** [comment]
If nunjucks is adding commas to the output that shouldn't be there, it's a bug -- there is no intentional limitation here.

**Comment by ArmorDarks** [comment]
Try setting autoescaping to `false`, or using `"{{ dataGenially|safe }}"`

**Comment by devoidfury** [comment]
Any update on reproducing this issue? I'd love to send a patch but I don't really follow what's going on, have not been able to duplicate the issue.

**Comment by chemitaxis** [comment]
Hi, I don’t have time to create the repo... maybe next week... I’m so
sorry... :(

**Comment by fdintino** [comment]
@chemitaxis No worries. Feel free to reopen when you get a chance to provide more details.
