### ISSUE TITLE
Adding a custom filter causes app to break with no error/stack trace

### ISSUE THREAD

**Issue by kingsloi** [mozilla/nunjucks#1094]
Hi, I am working with the following code (copied from: https://github.com/mozilla/nunjucks/issues/989)
```
import nunjucks from 'nunjucks';
import { Environment } from 'nunjucks';

let env = new Environment({dev: true});

import shuffle from 'filters/shuffle';
env.addFilter('shuffle', shuffle);
```

>  filters/shuffle.js
```
import { shuffle } from 'lodash';

export default function filter(arr) {
  return shuffle(arr);
}
```

> app.js
```
let templateData = {
  values: [1,2,3,4,5]
};

var tpl = require('templates/form.njk');
var html = tpl.render(templateData);

```

> form.njk
```
{% for value in values | shuffle %}
   {{ value }}
{% endfor %}
```

I expect it to shuffle the array, however, I get a blank screen, with no errors/stack trace in the console, or no errors with Webpack/Laravel Mix. If I remove the `| shuffle` my array prints as normal. 

Any ideas?

node = v9.9.0
npm = 5.6.0

lodash: ^4.17.4
nunjucks: ^3.1.2
nunjucks-loader: ^3.0.0

**Comment by fdintino** [comment]
I can't speak to why you're not getting an error or a stacktrace, but are you setting the nunjucks environment config in your webpack.config.js? The nunjucks-loader docs have pretty specific instructions for adding custom filters.

**Comment by kingsloi** [comment]
@fdintino, I was picking my head for hours at that. 10,000 thank-yous aren't enough, you saved my weekend.
