### ISSUE TITLE
debug nunjucks path

### ISSUE THREAD

**Issue by microcipcip** [mozilla/nunjucks#1099]
Hi, I am trying for hours to use **include**  and **extends** but I get the wrong path.
Is there a way to output the path of the current file or something similar so I can figure out how to get it right? 

May be worth mentioning that I am using consolidate.js

**Comment by devoidfury** [comment]
The paths aren't relative to the current file, they're relative to whatever paths you pass into configure.

So say you have a layout like so:

```
project/
  templates/
    layout.njk
    pages/
      homepage.njk
    partials/
      alert.njk
```

and you configure the view directory: `app.set('views', __dirname + '/templates')`

and you render the homepage: `res.render('pages/homepage.njk')`

The extends and includes will be relative to the view directory:

```jinja
{# example homepage.njk #}
{% extends 'layout.njk' %}

{% block mainbody %}
  <h1>Hello World!</h1>
  {% include 'partials/alert.njk' %}
{% endblock %}
```

**Comment by microcipcip** [comment]
@devoidfury thanks for your help, I finally managed to include it, and it surprised me because I needed to provide the whole path from the root of the app. My problem probably is that I am using consolidate.js indirectly from the [email-templates](https://github.com/niftylettuce/email-templates/) package so I don't quite understand how the path is set up.
