### ISSUE TITLE
I have a problem when I use for

### ISSUE THREAD

**Issue by z3214965** [mozilla/nunjucks#1101]
I have a problem when I use for，this problem is "This would display if the 'item' collection were empty"

my code:
<h1>Posts</h1>
<ul>
{% for item in items %}
  <li>{{ item.title }}</li>
{% else %}
  <li>This would display if the 'item' collection were empty</li>
{% endfor %}
</ul>

 let env = nunjucks.configure(path.resolve(__dirname, "../views"));
 var items = [{ title: "foo", id: 1 }, { title: "bar", id: 2 }]
env.render('./system-user/system-user.html', items);

**Comment by devoidfury** [comment]
The second argument to `render` takes an object, and the attributes there are used for lookup --

```js
let env = nunjucks.configure(path.resolve(__dirname, "../views"));
var items = [{ title: "foo", id: 1 }, { title: "bar", id: 2 }]
env.render('./system-user/system-user.html', {items: items});
```

**Comment by z3214965** [comment]
I am too careless, thank you
