### ISSUE TITLE
Nested dependency on randomatic@1.1.7 with security vulnerability

### ISSUE THREAD

**Issue by lastrader** [mozilla/nunjucks#1103]
Can you update to chokidar >=2.0.0 which removes dependency on randomatic?

See: https://nodesecurity.io/advisories/157

nunjucks@3.1.2 > chokidar@1.7.0 > anymatch@1.3.2 > micromatch@2.3.11 > braces@1.8.5 > expand-range@1.8.2 > fill-range@2.2.3 > randomatic@1.1.7

**Comment by i-hardy** [comment]
There's also issues with stringstream (https://nodesecurity.io/advisories/664) and sshpk (https://nodesecurity.io/advisories/606), all stemming from the same chokidar dependency.
