### ISSUE TITLE
set var loaded from interpolated require

### ISSUE THREAD

**Issue by iManu** [mozilla/nunjucks#1105]
Hello,

I try to set a var using webpack interpolated html-loader setting, without results
`{% set title = ${require('../data/data.json').index.title} %}`
or 
`{% set title = require('../data/data.json').index.title %}`

the error message is `Template render error: expected block end in set statement`

When I used another technique, it's working very fine:
`{% block title %}${require('../data/data.json').index.title}{% endblock %}`

But I need to use `title` multiple times in the parent `base` template, and this is not allowed with blocks, while setting a var is more effective unless it cannot use require :/
 
Do you see what I mean ?

**Comment by ArmorDarks** [comment]
My recommendation would be not to do such a horrible thing and pass any required data while invoking `env.render` as a context, then just use it in templates. Like this:

```js
const DATA = require(require('../data/data.json')

...

env.render('your_template', { DATA })
```

and later use it in your templates as

```jinja
{% set title = DATA.someProp %}
```

Otherwise, your app will have serious performance issues, because require will be invoked with each render of each page when any `title` first declaration will be encountered.

**Comment by fdintino** [comment]
If you're interpolating with webpack at compile time, you may not incur a performance issue. But in that case you will need to properly quote the value in the `{% set %}` tag. Something like the following might work:

```html
{% set title = ${JSON.stringify(require('../data/data.json').index.title)} %}

**Comment by iManu** [comment]
Thank you for the responses.

The site is builded to be static at the end, so I don't really care about rendering.

I found no way to use @ArmorDarks solution for the moment, as I use webpack & `nunjucks-html-loader`.

With @fdintino idea, I got an `expected block end in set statement` error.

**Comment by ArmorDarks** [comment]
> The site is builded to be static at the end, so I don't really care about rendering.

This is still matters when website grows. We didn't care too until site reached 400 pages. There you start to see really slow builds.

> I found no way to use @ArmorDarks solution for the moment, as I use webpack & nunjucks-html-loader.

You can pass Nunjucs context with `nunjucks-html-loader` by following https://github.com/ryanhornberger/nunjucks-html-loader/issues/8

**Comment by iManu** [comment]
@ArmorDarks I'm sure the website never grow more than 10 pages (actually 3), but I note your relevant remark ;)
I've no time to test about passing context you link about, but I try that asap. It's seems to be THE solution I search !
