### ISSUE TITLE
Nunjuck prevents Codekit app to delete old <link> elements

### ISSUE THREAD

**Issue by petrchutny** [mozilla/nunjucks#1108]
I use [Codekit](https://codekitapp.com/) as a front-end coding too to do live browser refreshing. Codekit injects new `<link>` elements with newly compiled CSS code every time I make some changes, and deletes the old `<link>` elements.
Nunjucks that a website of a company that I work in uses, prevents the deletion of old  `<link>`, so they remain in the page and cause trouble (slow browser, CSS multiplications)
Here is the error from Chrome's console:
![image](https://user-images.githubusercontent.com/1197393/40045919-e254a56a-582b-11e8-8831-acff94ee0507.png)
I am communicating with Bryan Jones, the author of Codekit. He has replicated this problem and explained to me what is causing it. Since Codekit is quite a commonly used pre-compiling live-reloading tool for front-end developers, it might be good looking into it, thank you.

**Comment by devoidfury** [comment]
Nunjucks doesn't touch the DOM directly at all. This sounds like a problem with either Codekit, the way the frontend glue is written, or the way the livereload mechanism work. Can you provide a full error stack trace, just to make sure? There's no way to duplicate that problem on this end.

**Comment by fdintino** [comment]
There's not enough information here to troubleshoot the problem. How is nunjucks being used? Specifically, what is the nunjucks code that, when added, causes this error to be thrown?

**Comment by petrchutny** [comment]
@fdintino I've just removed all the scripts and the problem persists, **so this doesn't seem to be a Nunjuck's issue**. Sorry for your time guys, I wasn't aware of this.
