### ISSUE TITLE
 I send a line to the client but nunjucks subtracts, why?

### ISSUE THREAD

**Issue by shanematte** [mozilla/nunjucks#1113]
Hello!! 
HELP
let attributes = '50000-70000'

when displayed on the client displays this -20000
20000-50000 = -20000 why?

I need to get this out 20000-50000

**Comment by ArmorDarks** [comment]
How exactly do you pass `attributes` to Nunjucks?

**Comment by shanematte** [comment]
@ArmorDarks 
```
			filter:{
				word,
				salary, // 100000 - 200000
				cityId,
				catId
			}
```

**Comment by ArmorDarks** [comment]
eh, can you share more of your code?

**Comment by devoidfury** [comment]
If you want to share a variable like that in generated javascript code, you have to json encode it. You can use the dump filter to get JSON-encoded values:

```js
let selectedsalary = {{ filter.salary | dump }}
console.log(selectedsalary)
```

**Comment by ArmorDarks** [comment]
@shanematte When re-reading your original issues and your answer above, I can't get what exactly doesn't work for you. Can you be more specific?

**Comment by shanematte** [comment]
Thanks. 
found a solution
let selectedsalary = {{ filter.salary }} => "{{ filter.salary }}"
