### ISSUE TITLE
How do I include a template from native javascript

### ISSUE THREAD

**Issue by jkxdev** [mozilla/nunjucks#1123]
I have a template file in which i need to include another template, but i need to pass a variable to that template.
To do that, I need to set a variable before including the second template.
```jinja2
  {% set configName = "config_group_name1" %} {# I need this inside the included file#}
  {% set utilsinclude =  parent_dir + "/utilspath/utils.j2" %}
  {% include utilsinclude %}
```

now I need to do the same in many existing files and in new files those will be added. So, I need to make the above as a function/Macro/block whatever.

In addition, there are context variables in the current template that needs to be accessed in the utils.j2 template.

Now, macros seemed to be the best option, but the parent context is not accessible inside the macro.

took a further deviation by setting a callback function to the context of render call to parent-template.
```javascript
var contextvar = {};
contextvar.parent_dir = __directory;  
contextvar.utilsconfig = function utilsconfig(configNameVal) {
    this.ctx.configName = "configNameVal";
    var utilsinclude =  this.parent_dir + "/utilspath/utils.j2";
    var tmpl = this.env.getTemplate(utilsinclude,true,/*<how to get parent name here>*/);
    return  tmpl.render(this.getVariables());
};
var filename = 'parent-template.j2';
res = nunjucks.render(filename,contextvar);
```
and then calling it inside the parent-template.j2 as below
```jinja2
{{ utilsconfig("config_group_name1") }}
```
but in the above way also, i am not able to get the name of the parent - template full path
because of which it has to be rendered individually.

so what happens is that all my xml tags gets encoded when the render for the parent_template gets called.
eg - >
```xml
<param name="configName" value="configNameVal"/> 
gets converted to 
&lt;param name=&quot; configName&quot; value=&quot; configNameVal&quot;/&gt;
```

if i get the parent name, i suppose i dont need to explicitly call the render, **please correct me**
or if i cant do that, **how do i avoid the encoding** ?
 
the only condition is that i need to get this done with a function/macro call
but i cant keep passing different parameters from the context every time, like i did with macros

referred https://github.com/mozilla/nunjucks/issues/109 and 
https://github.com/mozilla/nunjucks/issues/327
but not exactly matching.

I prefer using a macro, as the code will be clean, but getting the context is an issue.
please suggest
@jlongster @garygreen

**Comment by Pomax** [comment]
can you untag me on this? This is not something I can help out, unfortunately.

**Comment by jkxdev** [comment]
modified the call and it worked.
```jinja2
{{ utilsconfig("config_group_name1") | safe }}
```
thanks

**Comment by ArmorDarks** [comment]
You can import macro with context, just add `with context` at the end of the import.

```jinja
{% from 'components/Test.nj' import Test with context %}
```

**Comment by ArmorDarks** [comment]
Also, do not assign functions directly to the context. Use `env.addGlobal('utilsconfig', yourFunc)` instead
