### ISSUE TITLE
Errors seem to be swallowed.

### ISSUE THREAD

**Issue by davidjamesstone** [mozilla/nunjucks#1127]
I'm new to Nunjucks so please forgive me but I'm finding it very hard to debug when things start going wrong as errors don't seem to propagate up.

Whether it's a syntax error in the template, or a missing template, no errors are raised and and null is returned from the `template.render(context)` method.

My render pipeline is sync, the only way I've been able to get it to report the error though is to  provide an error-first callback to the `render` method, get the error, then remember to remove the callback after. This is quite frustrating.

I've also tried setting the `throwOnUndefined` option to `true` but that doesn't seem to make a difference.

Can anyone shed a light on this? I can provide some example code if needed.

While this is proving to be painful from a dev point of view, my bigger concern is that errors are swallowed in production.

Many thanks

Dave

**Comment by devoidfury** [comment]
Can you provide the example illustrating the issue? Thanks!

**Comment by davidjamesstone** [comment]
Hi @devoidfury.

Here's is an example of missing import.
I would expect the following to throw, given the file import doesn't exist.

No errors are thrown, the result `html` is null. `throwOnUndefined` doesn't have any affect.

```
const nunjucks = require('nunjucks')

const env = nunjucks.configure('./', {
  autoescape: true,
  watch: false,
  // throwOnUndefined: true
})

const template = nunjucks.compile(`
{% from "bad-path/macro.njk" import foo %}
{{title}}
`, env)

const html = template.render({title: 'Hello world'})

console.log(html)
==> null
``` 

Many thanks

**Comment by cgatesman** [comment]
I am seeing this with `{% include %}` as well.

**Comment by TomFrost** [comment]
This also happens for `throwOnUndefined = true` when the template is syntactically correct and all referenced files are in place, but the context is missing a variable that the template references. The render output is null, but nothing is actually thrown in the synchronous API. As with the above, the error can be captured in a callback function.

**Comment by TomFrost** [comment]
Looks like this could be related to #678

**Comment by leosdad** [comment]
Sorry to revive an old post, but I started using Nunjucks some days ago and the problem is still there. I'm using `renderString()`, not the async methods. Syntax errors do raise an exception, while import errors, macro errors (and maybe others) are still silently swallowed. This makes debugging complex templates very hard.

**Comment by fdintino** [comment]
@leosdad two questions: are you passing a callback into `renderString()`, and what version of nunjucks do you have installed?

**Comment by fdintino** [comment]
If the answer to the first question is no, and you're using the latest version, would it be possible to paste a minimal test case showing the problem? The example provided in the [comment above](https://github.com/mozilla/nunjucks/issues/1127#issuecomment-407696659) is fixed in the latest version.

**Comment by leosdad** [comment]
Hi, @fdintino! Yes, I'm using the latest version, and I'm using no callback with `renderString()`. I'll try to reduce the problem code to the minimum and post it here ASAP. Thanks!

**Comment by fdintino** [comment]
Thank you. And just to make sure I don't miss it, could you instead post it in a new issue?

**Comment by leosdad** [comment]
Sure, I'll do that.

**Comment by leosdad** [comment]
I've opened issue #1272 with the test case.
