### ISSUE TITLE
How to render array data?

### ISSUE THREAD

**Issue by DrakeXiang** [mozilla/nunjucks#1128]
I thought this should be intuitive as doc says:
```javascript
var items = [{ title: "foo", id: 1 }, { title: "bar", id: 2}];
<h1>Posts</h1>
<ul>
{% for item in items %}
  <li>{{ item.title }}</li>
{% else %}
  <li>This would display if the 'item' collection were empty</li>
{% endfor %}
</ul>
```

But actually it's not working if I use array directly:
```javascript
// index.html
...
<div id="test"></div>
...

<script>
       var items = [{ title: "foo", id: 1 }, { title: "bar", id: 2}];
      var items = nunjucks.render('./items.html', items);
      $('#test').html(items)
</script>
```
```javascript
// items.html
{% for item in items %}
  <div>{{item.title}}</div>
{% endfor %}
```

It will only work if I wrap the array in an object and with a key of `items`, I couldn't find anywhere about this issue, so I guess there's a way to refer to the array itself?

**Comment by DrakeXiang** [comment]
Ok, my current work around is wrap the array with object in render function inline, still feels a little hacky

**Comment by fdintino** [comment]
The template doesn't know that the array is called `items` unless you pass it as an object with the key `items`. So, calling:

```javascript
nunjucks.render('./items.html', {items: [{title: 'foo', id: 1}, ...]})
```

isn't a workaround, it's just how context is passed to the template.
