### ISSUE TITLE
Is it possible to get template information?

### ISSUE THREAD

**Issue by Tera3yte** [mozilla/nunjucks#1129]
Is it possible to get template information e.g. used variables / blocks and more? 

Something like `nunjucks.parse('/path/to/template')` with an output of `{variables: ['abc', 'efg'], blocks: ['my_block']}` would be very usefull. Did not find something like this in the docs. May somebody can help me here.

**Comment by fdintino** [comment]
Closing this in favor of #1153, so we have a single issue to track this request.
