### ISSUE TITLE
caller

### ISSUE THREAD

**Issue by guohuihot** [mozilla/nunjucks#1133]
```
{% macro a() %}
    <div></div>
    {{ caller() }}
{% endmacro %}

{{ a() }} // wrong

But
{% call a() %} <div></div> {% endcall %} // right
```

**Comment by fdintino** [comment]
Are you sharing that you figured out how to use call with `caller()`, or is this a bug report, or...?

**Comment by fdintino** [comment]
There doesn't appear to be an issue here. `caller` only works when used with `{% call %}`

**Comment by guohuihot** [comment]
...
