### ISSUE TITLE
How to handle errors in custom filter?

### ISSUE THREAD

**Issue by poluyanov** [mozilla/nunjucks#1137]
Hi! Is there a proper way not to catch exceptions in custom filter?

This code passing silent:
`
env.addFilter('myFilter', function(text) {
        undefinedFunction(); // Expect exception
});
`

One solution is providing callback to env.render() method, but i want to run my code synchronously.

**Comment by devoidfury** [comment]
```js
try {
    env.render(...)
} catch(e) {
    // error handling here
}
```

**Comment by revelt** [comment]
@poluyanov Hi Ivan, did the above idea work or do you still need help or can we close this ticket?
