### ISSUE TITLE
How to define dynamic block names in a loop?

### ISSUE THREAD

**Issue by lerran80** [mozilla/nunjucks#1138]
I have a template with:
![image](https://user-images.githubusercontent.com/22422447/44632123-e128f800-a94b-11e8-8f95-01d93adbda15.png)

Later, I would like to define the values for the blocks like this:
![image](https://user-images.githubusercontent.com/22422447/44632131-09b0f200-a94c-11e8-891b-8a5200dfbdc1.png)

But instead, the for loop creates 3 blocks with the same name "item", so if I later define:
![image](https://user-images.githubusercontent.com/22422447/44632141-38c76380-a94c-11e8-83d2-542eb6a2ebd1.png)

"TEST ITEM" is rendered 3 times.

Is it possible to generate 3 blocks named "A", "B" and "C" in the for loop?

**Comment by fdintino** [comment]
This is not possible, but whatever you are trying to do can probably be accomplished by other means.

**Comment by akelmj** [comment]
cantiero , can you add example code or expaine how you solve this issue?

thanks.

**Comment by cantiero** [comment]
Hi! I have been away from this code base and from Nunjucks for a long time now. Unfortunatelly I do not remember nor would know where to look for the real case I was facing.

Sorry I can't help. Lesson learned, next time I will include whatever I did so other people can benefit from it.
