### ISSUE TITLE
Avoid node.js dependence / Work without node.js in client side

### ISSUE THREAD

**Issue by jonalxh** [mozilla/nunjucks#1141]
Hi guys.

I'm trying to create a simple website with a **base.html** template and according to menu actions change the content space, something like this:

**base.html**
```
{% block header %}
<!-- css links and meta tags here -->
{% endblock %}
<body>
    <aside>
        <ul> 
            <li>
                <a href="dashboard.html">Dashboard</a>
            </li>
            <li>
                <a href="users.html">Users</a>
            </li>
        </ul>
    </aside>
    <div id="content-container">
        {% block content %}

        {% endblock%}
    </div>

    <script src="../nunjucks.min.js">
</body>

```

**dashboard.html**

```
{% extends base.html %}

{% block content %}
<!-- my graphics and data here -->
{% block content %}
```

I just want that on click the item menu, it renders the content in the **block content** area, but i'm just working with html, javascript, css and jquery. 
Is it posible to do this without node.js and a precompilation? Maybe just instanciating the nunjucks module and writing some js code on the client JS file?
I've looked for throught the docs and I did not find an answer. Sorry for the dummy question.

Thanks a lot for your help.

**Comment by devoidfury** [comment]
You wouldn't be able to use extends with a base layout (which has <body> or <head> in it). nunjucks doesn't know anything about HTML or the DOM, it just outputs a string.

**Comment by jonalxh** [comment]
Hi @devoidfury, thanks for your instant answer.
So, acording to your answer it is not possible to do something like this or similar?
I've mentioned it because it's the way python jinja2 templates work, and I read nunjucks is based on it.

**Comment by devoidfury** [comment]
It works just like jinja, but more complex layouts (like using extends with a parent template that has head/body) can only be done with server-side rendering. Jinja is server-side only

**Comment by devoidfury** [comment]
You'd need either a nodejs server to render the templates on request, or client-side only and just modify the content inside body. With client-side-only you'd need to copy+paste the outer layout (head/body with the javascript includes, etc) into each file
