### ISSUE TITLE
Importing Macro causes content not to render

### ISSUE THREAD

**Issue by oleersoy** [mozilla/nunjucks#1148]
I created a test project here:

https://github.com/oleersoy/nunjucks

```
git clone https://github.com/oleersoy/nunjucks
npm i
cd nunjucks
node index.js
```
The console will log `null` because the `contact.html` file imports the `templates/forms.njk` macro file.  If the import statement is deleted from `contacts.html` then the console.log statement will log the rendered contact html.  Thoughts?

**Comment by ArmorDarks** [comment]
Your [forms](https://github.com/oleersoy/nunjucks/blob/master/src/templates/forms.njk) template has a typo — unclosed `{% macro label( text ) %}`

It actually had to throw an error, but maybe you've suppressed it somewhere. Or try using callback following [docs](https://mozilla.github.io/nunjucks/api.html#render) to actually get an error.

**Comment by oleersoy** [comment]
@ArmorDarks thank you!  It works now.  I'll close the issue.  Thanks again!
