### ISSUE TITLE
[Question] Is it possible to pass multiline content / markup to nunjucks macros? 

### ISSUE THREAD

**Issue by oleersoy** [mozilla/nunjucks#1149]
Wondering whether it's possible to pass content like:

```
  <div class="TestHeader ">
    <span class="TestCounter"></span>
    <span class="TestComponent">TestBoxLeft</span>
  </div>
```
To a nunjucks macro?  So if the above content could be inserted into a variable called `content` the macro could be called like this:
```
{% import "insert.njk" as insert %}

{{ insert.content( content ) }}
```

**Comment by devoidfury** [comment]
```jinja
{% macro content() %}
foo {{ caller() }} bar
{% endmacro %}

{% call content() %}
  <div class="TestHeader ">
    <span class="TestCounter"></span>
    <span class="TestComponent">TestBoxLeft</span>
  </div>
{% endcall %}

```
https://mozilla.github.io/nunjucks/templating.html#call

**Comment by oleersoy** [comment]
@devoidfury THAT'S VERY COOL - Thank you!  I played around with a mini prototype that can be found [here in case anyone else needs to do something similar](https://github.com/oleersoy/nunjucks).  In my case I'm planning on rearchitecting [superflycss/cli](https://www.npmjs.com/package/@superflycss/cli) to generate [tests like these](https://superflycss.github.io/component-test/target/test/html/) using the nunjucks macros.  Right now I'm using JSDOM to copy the markup content to another section so that the markup example section can be syntax highlighted, and now it looks like I can cut out the JSDOM manipulation and use pure nunjucks.  Thanks again!
