### ISSUE TITLE
Not replacing `{{1}}`

### ISSUE THREAD

**Issue by kirillgroshkov** [mozilla/nunjucks#1152]
```
Nunjucks.renderString('Hello {{1}}', {1: 'Sofia'})
// or
Nunjucks.renderString('Hello {{1}}', {'1': 'Sofia'})
```

Returns `Hello 1` instead of expected `Hello Sofia`

**Comment by yannou788** [comment]
Hi i thinks it's because your object keys is an integer. Just change you key name to a string value

**Comment by kirillgroshkov** [comment]
@yannou788 yes, I've tried that to, but result is the same

**Comment by yannou788** [comment]
@kirillgroshkov if you set it like that it's will work : `Nunjucks.renderString('Hello {{ myvariable }}', {myvariable: 'Sofia'})`

The problem in my opinion is that nunjuck think thats 1 is not an variables but just a common number

**Comment by devoidfury** [comment]
```js
> var nunjucks = require('nunjucks')
> nunjucks.renderString('{{ 2 * 5 + 7 }}')
'17'
> nunjucks.renderString('{{ foo or 1 }}')
'1'
> nunjucks.renderString('{{ foo or 1 }}', {foo: 'bar'})
'bar'
```
If we changed that, to work with context variables that look like numbers, we'd break all the math. I, for one, am using this kind of thing in production and it would be a breaking change, I'm not seeing a good reason to alter this.

**Comment by kirillgroshkov** [comment]
So, I will close the issue since I don't believe fix is possible. Unfortunately for me.
