### ISSUE TITLE
Provide a way to discover a template's dependencies

### ISSUE THREAD

**Issue by chocolateboy** [mozilla/nunjucks#1153]
nunjucks doesn't provide a way to discover a template's direct or transitive dependencies i.e. the child and grandchild templates that are loaded (via `extends`, `import` or `include`) when a parent template is rendered. This is needed to [integrate](https://github.com/devmattrick/parcel-plugin-nunjucks/issues/1) ([efficiently](https://github.com/devmattrick/parcel-plugin-nunjucks/pull/3)) with bundlers such as [Parcel](https://github.com/parcel-bundler/parcel), which track changes in dependencies and use them to trigger rebuilds.

(Note: this is orthogonal to nunjucks' caching support via chokidar, though the implementations may overlap.)

Ideally, this would be scoped to a particular `Environment#render` call, but there doesn't appear to be any space in the `render` method's parameters to squeeze in additional options, or to return an additional value. Maybe a sister method with a more flexible interface?

```javascript
// result is an object rather than a string
const result = env.parse(templatePath, { context: ..., trackDependencies: true })
console.log('dependencies:', result.dependencies)
console.log('source:', result.source)
```

This makes dependency tracking optional, to err on the side of efficiency, but they could be included by default as it's a new API, and the overhead is unlikely to be high e.g.:

```javascript
const result = env.parse(templatePath, { context: ... })
```

Another way to do it is via an EventEmitter API (which is already used, lightly, in loaders) e.g.:

```javascript
env.on('dependency', ({ name, path, parent }) => { ... })
```

This has several advantages:

- it doesn't clutter or crowd any existing APIs
- it's easier to implement
- it's easy to extend
- if there's a performance concern, it could be toggled on/off with a constructor option e.g. `new Environment(loaders, { trackDependencies: true })`

The main disadvantage is that it doesn't *directly* answer the question "What are this template's dependencies?" i.e. it requires extra work to scope the results to a particular template/render. (This also implies the use of a full EventEmitter implementation rather than the cut-down version that's currently used for loaders, and suggests the addition of some new events e.g. `render:start` and `render:end`.)

---

I'm envisaging each dependency as an object with the following core fields:

```javascript
{
    name: "../macros/util.html.njk",
    path: "/home/foo/dev/example/src/html/macros/util.html.njk",
    parent: "/home/foo/dev/example/src/html/screens/layout.html.njk",
}
```

Optional fields could include `cached` (a boolean indicating that the template was retrieved from its loader's cache) and maybe `async` (the template was retrieved by an async loader).

# Example

### layout.html

```xml
{% include "../components/header.html" %}
<h1>Body</h1>
{% include "../components/footer.html" %}
```

### header.html

```xml
<h1>Header</h1>
```

### footer.html

```xml
<h1>Footer</h1>
{% include "./copyright.html" %}
```

### copyright.html

```xml
Copyright ⓒ example.com 2018
```

### render

```javascript
    const result = env.parse("src/html/screens/layout.html")
    console.log(result.dependencies)
```

### result

```javascript
[
    {
        name: "src/html/screens/layout.html",
        path: "/home/foo/example/src/html/screens/layout.html",
        parent: null,
    },
    {
        name: "../components/header.html",
        path: "/home/foo/example/src/html/components/header.html",
        parent: "/home/foo/example/src/html/screens/layout.html",
    },
    {
        name: "../components/footer.html",
        path: "/home/foo/example/src/html/components/footer.html",
        parent: "/home/foo/example/src/html/screens/layout.html",
    },
    {
        name: "./copyright.html",
        path: "/home/foo/example/src/html/components/copyright.html",
        parent: "/home/foo/example/src/html/components/footer.html",
    },
]
```

**Comment by chocolateboy** [comment]
Related: #1129

**Comment by andreyvolokitin** [comment]
So, for now, we can use [`nunjucks-parser`](https://github.com/chocolateboy/nunjucks-parser) to get dependencies from entry file?

**Comment by chocolateboy** [comment]
@andreyvolokitin Yes, but the implementation is hacky as it's tightly coupled to the internals of `Environment#getTemplate`. The EventEmitter solution mentioned above would make it non-hacky.

**Comment by andreyvolokitin** [comment]
@chocolateboy I use only `FileSystemLoader` in my use case, and internally it gets every file path needed (though every other loader should also do it). If there would be a way to utilize this, I thought that this may work similar to `nunjucks-parser` where it collects every dependency with `Environment#getTemplate`?

**Comment by chocolateboy** [comment]
@andreyvolokitin I'm not sure what you're asking, but if you have a question about nunjucks-parser feel free to raise an [issue](https://github.com/chocolateboy/nunjucks-parser/issues).

**Comment by andreyvolokitin** [comment]
I was wondering if it possible/viable to solve this issue (getting template dependencies) by using the internals of a loader ([`FileSystemLoader `](https://mozilla.github.io/nunjucks/api.html#filesystemloader) specifically), which gets all related [file paths](https://github.com/mozilla/nunjucks/blob/master/nunjucks/src/node-loaders.js#L81)

**Comment by chocolateboy** [comment]
Not without changing `Environment#getTemplate`. `Environment#getTemplate` doesn't call `Loader#getSource` if the template is [cached](https://github.com/mozilla/nunjucks/blob/9a0ce364effd28fcdb3ab922fcffa9343b7b3630/nunjucks/src/environment.js#L207-L225) (the [`noCache` option](https://mozilla.github.io/nunjucks/api.html#configure) doesn't affect this).

**Comment by fdintino** [comment]
I think hooking into `Environment.getTemplate()` would be the correct way to approach this, no? It's perfectly legal nunjucks / jinja2 syntax to write:

```jinja2
{% include parent_template_name %}
```

In the simple case, where includes and extends are only strings, it is possible to parse the dependencies. But in the general case I think you would only be able to determine dependencies at runtime.

**Comment by fdintino** [comment]
Actually, a custom loader would probably be the way to go.

**Comment by chocolateboy** [comment]
@fdintino  Yes, I'd prefer the EventEmitter API.

**Comment by fdintino** [comment]
@chocolateboy does something like d4d646a work for you?

**Comment by chocolateboy** [comment]
@fdintino I haven't had a chance to play with it, but yes, thanks, that looks useful :+1:
