### ISSUE TITLE
Configure relative path

### ISSUE THREAD

**Issue by vladSvitelskyi** [mozilla/nunjucks#1156]
I'm working on improvements for [jest-nunjucks](https://github.com/denar90/jest-nunjucks) plugin and faced the problem with templates imported inside another templates, here the [example](https://github.com/vladSvitelskyi/jest-nunjucks/blob/test-include/tests/test.spec.js) of test suite

in case:

```
{% from './test2.njk' import testMacro %}

<div>{{ testString }}</div>{{ testMacro() }}
```

everything works good, but using include everything crashes and template can't be compiled.

```
{% include '../test.njk' %}
```

Here the configurations - https://github.com/vladSvitelskyi/jest-nunjucks/blob/test-include/index.js

Thanks for the help.

**Comment by denar90** [comment]
The problem here looks like  because of wrong dir (path) value in ```njk.configure(`${dir}`)```, but I'm not sure... 
@fdintino can it be because path is absolute?

**Comment by vladSvitelskyi** [comment]
@jlongster maybe you can help, thanks)

**Comment by denar90** [comment]
@vladSvitelskyi I played a bit with your fork and looks like something wrong with resolving templates in folders.
When I just dropped relative path from include `{% include '../test.njk' %}` => `{% include '../test.njk' %}` it started working. Looks like nunjucks think that templates in folder `templates` are placed on the same level as others (e.g. `test.njk`)...

**Comment by denar90** [comment]
Looks like problem here because in njk template you try to include file from folder above, but as @carljm mantioned
https://github.com/mozilla/nunjucks/issues/642#issuecomment-173408151

you should include from the folder you configured in FileSystemLoader... , so `{% include '../test.njk' %} ` is wrong way while `{% include 'test.njk' %}` is correct.

**Comment by fdintino** [comment]
Right. Jinja2 (and by extension, nunjucks) does not allow for relative include imports. Files should be imported relative to the template root.
