### ISSUE TITLE
Errors swallowed in synchronous render (2018)

### ISSUE THREAD

**Issue by AlJohri** [mozilla/nunjucks#1164]
hi @fdintino, just raising the priority of this bug since it seems fairly serious. in some conditions, when there is a template syntax error, the synchronous version of `env.render` simply returns null instead of throwing the error. there are several issues describing this such as:
- https://github.com/mozilla/nunjucks/issues/678
- https://github.com/mozilla/nunjucks/issues/1116
- https://github.com/mozilla/nunjucks/issues/1127

It appears the bug has something to do with async as the callback version of this function seems to  pass down the error object.

@carljm requested a failing a test that showcases this bug which can be found here: https://github.com/mozilla/nunjucks/pull/689 thanks to @nicolasartman

@oleics did some initial debugging back in 2016 https://github.com/mozilla/nunjucks/issues/678#issuecomment-226188784 and found that there is a line `var forceAsync = true;` which could be contributing although this code has changed quite a bit since then.

This bug makes it *very* hard to write templates with nunjucks and it would be great to resolve this soon.

**Comment by fdintino** [comment]
Agreed this is serious. I got bit by this myself recently. I'll prioritize finding a fix.

**Comment by rdmurphy** [comment]
We're hitting this too, and it's led to a lot of baffling debugging sessions and burnt time.

**Comment by AlJohri** [comment]
Thanks @fdintino!
