### ISSUE TITLE
Passing variables of nested template to outer templates

### ISSUE THREAD

**Issue by jtlapp** [mozilla/nunjucks#1170]
I have a single template for the generic layout of every page on my site. It includes a header, a menu bar, and a footer. It also includes meta tags, such as for `og:url`, `og:title`, `og:image`, `twitter:title`, and `twitter:image`. The content of these tags should vary by page.

How do I have a nested template provide the content values for the meta tags of the outer template? Ideally, my tested templates would specify these values for use in the outer template.

Some of my nested templates are themselves pages, but some of them are templates for further pages that I generate by iterating over a data set.

(I've actually implemented exactly this in my own quick-and-dirty templating system, but I'd like to switch things over to nunjucks.)

**Comment by ArmorDarks** [comment]
If I got your issue correctly, you need to read through #406

**Comment by jtlapp** [comment]
> If I got your issue correctly, you need to read through #406

Okay, thank you. That `config()` function method might work, but I was hoping to make a tool based on nunjucks that non-programmers would be comfortable with. It looks like either I'll need to add my own processing layer that does this or find some other templating system. Thanks for your help!
