### ISSUE TITLE
array access via .0. not supported

### ISSUE THREAD

**Issue by jgroom33** [mozilla/nunjucks#1174]
supported {{ dataArr[1]['name'] }}
supported  {{ dataArr[0].name }}
not supported  {{ dataArr.0.name }}
not supported  {{ dataArr[0]name }}

http://jsfiddle.net/2mcvg6xe/1/

**Comment by SidneyNemzer** [comment]
In JavaScript, dot notation doesn't allow numbers to start a segment

Ok: `data.$0`
Syntax Error: `data.0`

**Comment by jgroom33** [comment]
Thanks. I might be getting confused with python
