### ISSUE TITLE
render xml files

### ISSUE THREAD

**Issue by anselal** [mozilla/nunjucks#1177]
Hi there, 

is it possible  to render xml files using nunjucks ?

I have set the Content-Type to 'text/xml' and have set `autoescape: false` but the xml file is being rendered as plain text, although the source code is xml

**Comment by ArmorDarks** [comment]
It is possible to render literally anything with Nunjucks. It's just a templating engine after all. All depends on your setup.

What exactly are you doing? Is it static generation, server or client-side one?

**Comment by anselal** [comment]
Hi. Thanks for the clarification because I had an argue with a colleague and he said that this is just a html engine.

I think i figured it out. Must have done something wrong with the headers.
It seems to work now. 

Just for reference, this is how I render my xml files:

app.js
```javascript
// Configure Nunjucks
const _templates = 'templates' ;
nunjucks.configure( _templates, {
            autoescape: false,
            cache: false,
            express: app
            } ) ;

// Set Nunjucks as rendering engine for pages with .html suffix
// app.engine( 'html', nunjucks.render ) ;
app.set( 'view engine', 'nunjucks.render' ) ;

app.use(function (req, res, next) {
    res.header("Content-Type",'text/xml');
    next();
});
```

in the controller
```javascript
res.render(my_xml_file);
```
