### ISSUE TITLE
nunjucks-slim.min.js 3.1.3 not work in IE10

### ISSUE THREAD

**Issue by stywell** [mozilla/nunjucks#1178]
SCRIPT5007: 无法获取未定义或 null 引用的属性“apply” 
nunjucks-slim.min.js, 行2 字符9144

**Comment by stywell** [comment]
When you create an instance through `var env = new nunjucks.Environment();` in IE10
And then something went wrong.

**Comment by fdintino** [comment]
I'm sorry, but we only support IE 11 and higher. If you include a [polyfill](https://polyfill.io/v2/docs/) before nunjucks-slim you may be able to get it to work.

**Comment by zandko** [comment]
ie 11 is also not feasible
