### ISSUE TITLE
Support for SSI?

### ISSUE THREAD

**Issue by bradleytaunt** [mozilla/nunjucks#1179]
I've been trying to find a definitive answer in the Docs / past issues, but I can't seem to see any mention of support for server side includes?

Example:
```
<!--#if expr="$HTTP_COOKIE=/fonts\-loaded\=true/" -->
<html lang="en" class="fonts-loaded" dir="ltr">
<!--#else -->
<html lang="en" dir="ltr">
<!--#endif -->
```

The above ignores the conditional and just returns *both* `html` elements on build. I apologize in advance if I have overlooked something simple 😛

**Comment by devoidfury** [comment]
Nunjucks doesn't deal with http or the webserver or even html at all -- it just generates and outputs text. Anything outside of `{{ expression }}`, `{% tagname %}`, `{# comment #}`, nunjucks doesn't touch at all.

So my guess here is that either the syntax of that SSI is incorrect, or your webserver is not handling them correctly.
