### ISSUE TITLE
Not displaying third+ variables when get it from {% for %} cycle

### ISSUE THREAD

**Issue by mihalt** [mozilla/nunjucks#1180]
Hi! Can't make something like this

Context, wich is sent to html:
```
var context = {
    fruits: new Map([
      ["banana", "yellow", "big"],
      ["apple", "red", "average"],
      ["peach", "pink", "average"]
])
```
Html:
```
{% for fruit, color, size in fruits %}
  Did you know that {{ fruit }} is {{ color }} and have {{ size }} size?
{% endfor %}
```

And I get something like this: 
`Did you know that banana is yellow and have size?`

If I put 4, 5 and more variables in the 'fruits' items characteristic list nothing is displaying.

**Comment by fdintino** [comment]
That's not because of nunjucks, but because of `Map`. [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) takes an iterable of key-value pairs. If you specify more than a key and a value, the subsequent values get ignored.
