### ISSUE TITLE
Templating JS files with variables on NodeJS

### ISSUE THREAD

**Issue by Extarys** [mozilla/nunjucks#1183]
I would like to know if it's possible to template a JS file. The client is sending an ID and I would like to serve a JS file with a variable.

serve.js
```js
[...]
lib.options.key = {{k}}
```
server.js
```js
reply.view('serve.js', {k: '123456'})
```

I would also like to not enable caching on this, obviously.

Is it possible to do this?

**Comment by SidneyNemzer** [comment]
I leave the JS as a static file, and modify the njk template with a script element like this:

```njk
<script>
const KEY = '{{ key }}'
</script>
```

**Comment by Extarys** [comment]
Thanks @SidneyNemzer I owuld prefer to serve a JS file but I suppose I could play around that. 

Thanks for the idea.
