### ISSUE TITLE
Root data json access?

### ISSUE THREAD

**Issue by kkashou** [mozilla/nunjucks#1190]
Hello!

I am trying to figure out if there is a way for me to get access to the different data json files from different pages rather than the page that it matches base on file name. Is this possible?

Thanks

**Comment by devoidfury** [comment]
Can you elaborate on that? I'm not clear on what you're asking.

**Comment by kkashou** [comment]
@devoidfury - I am trying get access to other json files in data folder and display that same set of data on those page templates. I don’t wanna duplicate the data for each json file and nunjucks files.

Hopefully that helps!

**Comment by devoidfury** [comment]
I still don't follow, can you provide a code example? Nunjucks doesn't do anything with JSON out of the box, so I'm not clear on what you're talking about.

**Comment by kkashou** [comment]
Okay so you know how you can use the render api https://mozilla.github.io/nunjucks/api.html#render, well I am doing that and reference each json file data to each html render instance. I want to be able to access json data from other instances on top of what ever data json it was pass in.

Does that make sense?

**Comment by devoidfury** [comment]
Not really, no, I don't follow. Change the code that calls `render` to include all the json files you need there?

**Comment by kkashou** [comment]
@devoidfury - I created a special case and appended the json data I wanted to see across the app every-time the render is being called! Thank you very much!
