### ISSUE TITLE
Deprecation warning with XMLHttpRequest 

### ISSUE THREAD

**Issue by lordent** [mozilla/nunjucks#1191]
Message from google chrome browser
> web-loaders.js:86 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

**Comment by SidneyNemzer** [comment]
It's surprising that a templating engine would make any requests clientside. Are you sure this message came from nunjucks?

**Comment by ultimate-tester** [comment]
The webloader loads the templates from a URL. This is done with a synchronous XMLHttpRequest by default. You'll have to configure nunjucks like this:

`nunjucks.configure('/views', {web: {useCache: true, async: true}, autoescape: true});`

The important part is `{web: {useCache: true, async: true}`. This will make it async. After this change, make sure you render templates with a callback like this:

`nunjucks.render(viewName, options, function (err, body) {
// Do stuff
});`

**Comment by fdintino** [comment]
@ultimate-tester is correct; you can get rid of this deprecation notice by enabling async mode. But the nunjucks docs strongly advise against using the WebLoader; it's far better practice to precompile your templates than to load them over AJAX and parse them client-side.
