### ISSUE TITLE
node.js version dependency issues

### ISSUE THREAD

**Issue by ccemeraldeyes** [mozilla/nunjucks#1194]
When trying to run yarn, I received the following error:

`error nunjucks@3.1.3: The engine "node" is incompatible with this module. Expected version ">= 6.9.0 <= 11.0.0-0". Got "11.0.0"`

The issues are twofold:

1. 11.0 is not current with the stable minor version
2. I'm not sure why 11.0.0 doesn't match 11.0.0-0 (this one MAY be a yarn issue)

**Comment by fdintino** [comment]
This was fixed in nunjucks 3.1.6 (see #1168). If you install the latest version you will no longer run into this issue.
