### ISSUE TITLE
--toggle in macro reserved words? Strange bug...

### ISSUE THREAD

**Issue by Jakobud** [mozilla/nunjucks#1212]
Really weird bug I'm running into. I have this macro:

```
{% macro radio(name, value) %}

<li class="nav__submenu-item nav__submenu-item--toggle">
  <input type="radio" name="{{ name }}" value="{{ value }}" id="hello" class="nav__checkbox"/>
</li>

{% endmacro %}
```

This will not render for some reason. No errors or anything. Strangely enough, I have pinpointed the issue down to the `--toggle` in the class name. If I remove `--toggle` or change it to `-toggle` or `--toggl` then it renders fine.

I can't find anything in the docs or source code that would indicate why this would be happening. Am I missing something obvious here?

**Comment by devoidfury** [comment]
nunjucks doesn't know about html, everything outside of `{{ }}`, `{% %}`, or `{# #}` is treated as plain text output. Can you render the template and double-check the source code output? I tried but couldn't reproduce the issue; if this is happening in nunjucks it's a bug.

My best guess is something in your CSS is hiding that element visibly, but it should still be there. Something like, `.nav__submenu-item nav__submenu-item--toggle { display: none }`

**Comment by Jakobud** [comment]
Well it wasn't any CSS that I was seeing. It literally just wasn't rendering in the page source. For some reason it's no longer doing this. So I'm going to assume that it was something else interfering for now unless I can properly reproduce it later. Thank you,
