### ISSUE TITLE
templates always report compilation errors on next tick even if called synchronously

### ISSUE THREAD

**Issue by boutell** [mozilla/nunjucks#1217]
See:

https://github.com/mozilla/nunjucks/blob/224645791298db835df0acff3dc596d3a9ed2c4d/nunjucks/src/environment.js#L310

Despite the preceding comment the use of asap forces us to next tick and a hard crash for synchronous render calls despite try/catch.

Thanks for looking into it! We will have to deal with it in 2.x for apostrophe but it doesn't look like the code has changed in 3.x so our patch may prove acceptable.

**Comment by boutell** [comment]
hmm this explanation is not yet sufficient.

**Comment by fdintino** [comment]
This was fixed in 3.1.7. See 68ba15c4a
