### ISSUE TITLE
Crazy question: C#

### ISSUE THREAD

**Issue by Perlkonig** [mozilla/nunjucks#1226]
I came across this package while looking for a Jinja2 for C#. I came across Nunjucks 1.0.1 in NuGet, but I see that development has continued. Is there any chance of getting an updated .NET binary? Not sure what that entails or why it stopped back in 2013. The change logs don't explicitly mention it.

Thanks!

**Comment by fdintino** [comment]
I became maintainer of this project about two years ago, but I doubt that a C# port of jinja2 would have anything in common with this project (other than the name, apparently). I'm sorry I can't provide more info.
