### ISSUE TITLE
Indent macro adds extra newline

### ISSUE THREAD

**Issue by agirardeaudale** [mozilla/nunjucks#1231]
Running via Node 10.16.0 on Windows through WSL/Ubuntu, I find that the indent macro is adding an additional trailing newline character.

Example Input:
```
### Block Filter
{% filter indent(4) -%}
A
B
C
{%- endfilter %}
###


{% macro letters() -%}
A
B
C
{%- endmacro -%}

### Filter with macro
{{ letters() | indent(4) }}
###
```

Expected Output:
```
### Block Filter
A
    B
    C
###


### Filter with macro
A
    B
    C
###
```

Actual Output:
```
### Block Filter
A
    B
    C

###


### Filter with macro
A
    B
    C

###
```

The expected output is what I see when I run the same template through Jinja in Python. I've checked that all of the line break characters are newlines and not carriage returns. Interestingly, Nunjucks is also adding an additional newline to the end of the file, I'm not sure if that's by design. I haven't noticed an extra newline when using any tags or filters besides indent.

**Comment by gilesvessey** [comment]
I am also running into this issue. Probably going to write a template filter to indent without the added newline, but I shouldn't have to.
