### ISSUE TITLE
Cannot access all variables

### ISSUE THREAD

**Issue by limitlessloop** [mozilla/nunjucks#1238]
Hi I'm trying to create a `this` keyword which I can use in templates regardless of what the object is called.

For example

```njk
{% for key, value in this %}
  // ...
{% endfor %}
```

Following the advice of this [issue](https://github.com/mozilla/nunjucks/issues/809). I'm trying to add a global that gets all variables but `this` returns undefined.

```js
env.addGlobal('this', function () {
  console.log(this) // -> undefined
  return this.getVariables()
}())
```

Can anyone help me in understanding what might be wrong? Does the environment need to be setup in a particular way? Many thanks.

**Comment by ArmorDarks** [comment]
You can see working examples with [here](https://github.com/LotusTM/Kotsu/blob/master/modules/nunjucks-extensions.js#L109) and [here](https://github.com/LotusTM/Kotsu/blob/master/modules/nunjucks-extensions.js#L309).

I've noticed `()` in your code after function declaration:

```js
env.addGlobal('this', function () {
  console.log(this) // -> undefined
  return this.getVariables()
}()) // <- here
```

It's the root of your issue. That function should be a callback, but you're actually invoking function right away with `()`, so it never gets bound proper `this` by environment.

**Comment by limitlessloop** [comment]
Ah, of course. Thank you. Can't believe I didn't see that either.

I'm still having difficulty using it. Does the global need to be used as a method, ie `{{ this() }}`? And will it get the current context?

For example, should it work like this?

```
let template = `\
{% for item in this %}
  <li>{{ item.title }}</li>
{% else %}
  <li>This would display if the 'item' collection were empty</li>
{% endfor %}
`

let data = {
	items: [{
			title: "foo",
			id: 1
		},
		{
			title: "bar",
			id: 2
		}
	]
}

nunjucks.renderString(template, data)
```

Outputs:

```
<li>foo</li>

<li>bar</li>
```

Or in the case of 

```js
let template = `\
{% for item in items %}
  <li>{{ this.title }}</li>
{% else %}
  <li>This would display if the 'item' collection were empty</li>
{% endfor %}
````

Should it output

```
<li>foo</li>

<li>bar</li>
```

**Comment by ArmorDarks** [comment]
Yes, in that case, you need to use it as a function, like `{{ this() }}`, since you're passing a function into `addGlobal`.

```js
// A function. Have to be used as `{{ this() }}`
env.addGlobal('this', function () {
  return this.getVariables()
})

// A string. Just reference it as `{{ myString }}`
env.addGlobal('myString', 'some string')

// An object. Reference it as `{{ myObject.test }} {{ myObject.test2 }}`
env.addGlobal('myObject', { test: 1, test2: 2 })
```

**Comment by limitlessloop** [comment]
Ok thanks. Should it have knowledge of the current context it's in, for example if it's within a for loop, should the this be relatively to the data it's currently in? When I tried it, it just returned the original object passed to the template.

**Comment by ArmorDarks** [comment]
`this.getVariables()` just gets the _environment_ context, and it isn't bound to any scope. Thus, it won't work that way.

In fact, because in Nujucks you have full access to the env context just right away and adding `this.getVariables()`  as a global doesn't implement real `this`. the whole effort doesn't have much sense :)

**Comment by limitlessloop** [comment]
Ok cool. Thanks for explaining and the background. I did have a need for it, but it was a while ago so I'd need to revisit what I was trying to do to give an example.
