### ISSUE TITLE
is it possible to use a filter when setting a variable?

### ISSUE THREAD

**Issue by RwwL** [mozilla/nunjucks#1243]
I'd like to be able to set a variable using a filter so I don't have to call complex filters multiple times, for example:
```
{% set isOpen = computeOpenOrClosedStatus(content.businessHours, content.timezone) %}

<p class="locationStatus--{{ "open" if isOpen else "closed" }}">
    {{ "Open now" if isOpen else "Closed" }}
</p>
```
This doesn't seem to be possible based on my experimentation so far, but any clarification and/or other suggestions would be much appreciated.

Using the `{% filter %}` block doesn't seem to be possible for this scenario because I can't see a way to then pipe that result to the `safe` filter, so I can't render HTML as HTML.

**Comment by ArmorDarks** [comment]
You should be able to do it like this

```jinja
{% set isOpen = content.businessHours | computeOpenOrClosedStatus(content.timezone) %}
```

Or if you want to use it as a function, you need to register it with `addGlobal` instead.

**Comment by RwwL** [comment]
Thanks very much! That syntax does work with filters; wish I'd thought to try it.
