### ISSUE TITLE
Some characters break Nunjucks

### ISSUE THREAD

**Issue by devoidfury** [mozilla/nunjucks#126]
A U+2028 character (there may be others) in a template will cause nunjucks to throw "SyntaxError: Unexpected token ILLEGAL". Sometimes these sneaky beasts will work their way into copy. 

I understand if they cause an issue and throw or warn, but it should be handled better.

Tested on 0.1.10 and 0.1.9, broken in both.

EDIT: fixed character above; error happens regardless of where it is in the template.

**Comment by jlongster** [comment]
I think I remember fixing this bug in another one, please reopen if it still exists

**Comment by Primajin** [comment]
I am still having this issue with the U+2028 Character breaking the build :(
I managed to replace it with a text editor, but was scratching my head for a really long time before i found this issue here.

I am using gulp-nunjucks-html @ 2.0.0

**Comment by smohadjer** [comment]
I'm using gulp-nunjucks-render 2.2.2 and I get this error. The copy throwing error:

<article>
	Beim Zugriff auf unser Internetangebot erfassen wir folgende Daten in einer Protokolldatei:  - 
</article>
