### ISSUE TITLE
Documentation about use with Fusebox and Consolidate

### ISSUE THREAD

**Issue by stumpythumb** [mozilla/nunjucks#1263]
Im wondering if theres anyone with experience integrating templates with fusebox bundler. Would there be any useful docs to point to?

**Comment by fdintino** [comment]
I've not worked with either. It seems that [consolidate.js](https://github.com/tj/consolidate.js/) has some documentation on integration with nunjucks. I very much doubt there is any documentation on nunjucks and fusebox, but a github code search brought up [this result](https://github.com/DevQuayle/Front-End_Developer_Tools/blob/b398d303bbce82636e8c63a27d53eeb11d601c70/fuse/sparks/renderHtml.js). I'd recommend consulting the consolidate and fusebox communities for more information.
