### ISSUE TITLE
compile is not a function

### ISSUE THREAD

**Issue by cossssmin** [mozilla/nunjucks#1267]
Trying to use [this](https://mozilla.github.io/nunjucks/api.html#compile), I get:

```sh
TypeError: nunjucks.compile is not a function
```

Are docs misleading, or...?

**Comment by ogonkov** [comment]
You should import `nunjucks` before using it methods.

**Comment by cossssmin** [comment]
Thanks, was trying to use it off of the environment; took a look `nunjucks/index.js` and you're right 👍
