### ISSUE TITLE
prefix matching

### ISSUE THREAD

**Issue by tcurdt** [mozilla/nunjucks#1273]
What's the best way to do prefix matching in an `if`? Using a regex?

    {% if `r/^\/tech\/foo/`.test(page.url) %}

Or is there a way to make string slice comparisons?

**Comment by ogonkov** [comment]
Seems like you want [custom filter](https://mozilla.github.io/nunjucks/api.html#custom-filters)

**Comment by tcurdt** [comment]
@ogonkov, can you elaborate. I am not sure how a custom filter will help with prefix matching.

**Comment by tcurdt** [comment]
Something along the lines of this?

    {% if page.url | hasPrefix('/tech/foo') %}

**Comment by ogonkov** [comment]
Yep, like this in your example

**Comment by tcurdt** [comment]
That seems to work.
