### ISSUE TITLE
Adding date 'Y'

### ISSUE THREAD

**Issue by ctuxboy** [mozilla/nunjucks#1282]
Hello,

I want display the year (2020) in my website's footer.
With Liquid it is easy :

`{{ "now" | date: "%Y" }}`

How can i do that with Nunjucks?

**Comment by ogonkov** [comment]
You can add [custom filter](https://mozilla.github.io/nunjucks/api.html#custom-filters) for that.
```js
env.addFilter('date', (val, format) => {
  if (val === 'now' && format === '%Y') {
    return (new Date()).getFullYear();
  }

  return null;
})
```

```nunjucks
{{ 'now' | date('%Y') }}
```

**Comment by ctuxboy** [comment]
Hi,
Thanks for your useful tip!
Works perfect 🙂
