### ISSUE TITLE
Build an iframe with contents with nunjucks?

### ISSUE THREAD

**Issue by jasonday** [mozilla/nunjucks#1288]
I'm attempting to use nunjucks to build an iframe with code examples I'm pulling from an api.

Template:
```
<iframe src="about:blank" name="{{code.value.ex_title}}">
        <!DOCTYPE html>
            <html>
                <head>
                <meta charset="UTF-8">
                <title>{{code.value.ex_title}}</title>
                <style>
                {% set css %}
                    {{code.value.ex_CSS | safe}}
                {% endset %}  
                </style>
                </head>
                <body>
                <div>
                {% set html %}
                    {{import code.value.ex_html | safe}}
                {% endset %}
                </div>
                <script>
                {% set js %}
                    {{code.value.ex_JS | safe}}
                {% endset %}
                </script>
                </body>
            </html>
        </iframe>
```

But the iframe does not render correctly. The html, css, js all populates, but not as part of the `<head>` or `<body>` elements. See:

![image](https://user-images.githubusercontent.com/748011/81639458-fb3d8f00-93e9-11ea-886d-4f432d82a3bf.png)

**Comment by ogonkov** [comment]
I believe that `<iframe>`'s doesn't work that way. You should render nunjucks html to [`set`](https://mozilla.github.io/nunjucks/templating.html#set) and [encode it to `src` attribute of `<iframe>`](https://stackoverflow.com/a/10419102/990942).

**Comment by fdintino** [comment]
Yes. The `<iframe>` element doesn't have any children nodes. If present, the browser doesn't render them.
