### ISSUE TITLE
Is there a way to render a template with only specific nodes?

### ISSUE THREAD

**Issue by elantion** [mozilla/nunjucks#1294]
I want to combine nunjunks with html-webpack-plugin. I don't want to parse all nodes but only 'extends', 'block', 'include'.
Is there a way to achieve this?
Thanks, good day.

**Comment by ogonkov** [comment]
Can you give an example of what you trying to achieve?

**Comment by elantion** [comment]
For example, I want to convert below template to html and I don't want to deal with variables.
```html
<!doctype html>
<html lang="cn">
    <head>
    <title>{{ title }}</title>
    </head>
    <body>
    {% block body %}{% endblock %}
    </body>
</html>
```
expect
```html
<!doctype html>
<html lang="cn">
    <head>
    <title>{{ title }}</title>
    </head>
    <body>
    <div id="app"></div>
    </body>
</html>
```

**Comment by ogonkov** [comment]
Looks like you want to wrap some parts of your template in `{% raw %}...{% raw %}`, to avoid rendering of this part.
It's the only way to render only specific nodes.

```jinja2
<!doctype html>
<html lang="cn">
    <head>
    <title>{% raw %}{{ title }}{% endraw %}</title>
    </head>
    <body>
    {% block body %}{% endblock %}
    </body>
</html>
```

What problem did you trying to solve? May be there a easier way.

**Comment by elantion** [comment]
It seem like it works for me. but what I expecting was some kind of configuration to achieve this. Thanks all the same. Good day, mate.
