### ISSUE TITLE
Ignore missing not working

### ISSUE THREAD

**Issue by androdel** [mozilla/nunjucks#1297]
When doing an include, I added the 'ignore missing', but it still throws the 'template not found' error (using latest Nunjucks version).

According to the docs it should be in there: https://mozilla.github.io/nunjucks/templating.html#include

**Comment by ogonkov** [comment]
Can you make sample repo, to reproduce error?

**Comment by androdel** [comment]
Works in my test repo. Will be something wrong in the project itself.
