### ISSUE TITLE
template inclusion from parent template location

### ISSUE THREAD

**Issue by Pomax** [mozilla/nunjucks#13]
It might be a nice idea to allow (through an env setting) template inclusion relative to the parent's template, so something like

```
./index.html
./templates/viewX.html
./templates/viewY.html
```

where index.html loads viewX.html, which in turn includes viewY.html. These could then use the following include syntax:

```
index.html: {% include "templates/viewX.html" %}
viewX.html: {% include "viewY.html" %}
```

that way, moving templates around in clusters would not require changing the inclusion paths except for in the ancestral parent template.

Not sure if jinja2 supports that, come to think of it... if it doesn't, it should! O_O

**Comment by jlongster** [comment]
This was implemented in this PR: https://github.com/mozilla/nunjucks/pull/349
