### ISSUE TITLE
When using `renderString`, fields in error callback undefined

### ISSUE THREAD

**Issue by MH15** [mozilla/nunjucks#1300]
When an error is triggered while using `renderString("template string", {}, (err, res) => {}`, the `err.lineno` and `err.colno` fields are undefined.

**Comment by ogonkov** [comment]
Can you make a small repo to show a problem?

**Comment by MH15** [comment]
Yep! Will do at lunch.

**Comment by ogonkov** [comment]
There is also new version, that address some problems with errors, make sure to use latest version, while making demo repo.

**Comment by MH15** [comment]
Here we go.
https://github.com/MH15/nunjucks-renderstring-error
`npm install` then `node index.js`

**Comment by ogonkov** [comment]
`lineno` + `colno` are lost when error get "prettified"

https://github.com/mozilla/nunjucks/blob/c7337e78800aa3087dcf955a47365996ade78fab/nunjucks/src/lib.js#L37-L39

@fdintino is it intended behaviour?

**Comment by ogonkov** [comment]
@MH15 oh, i think i got it. When `Environment` configured with `dev: true`, error got full information about the error.

This behaviour was discussed before.

**Comment by MH15** [comment]
Wow thanks for your help! So if I set up an environment with `dev: true`, the information won't be stripped?

**Comment by ogonkov** [comment]
Yep, looks like it's not a bug, but feature
