### ISSUE TITLE
Create a toJSON Filter

### ISSUE THREAD

**Issue by Gabrz** [mozilla/nunjucks#1322]
I need a toJSON Filter

And I think I just have to add this to src/filter.js
```
function toJSON(str) {
	return JSON.parse(str);
}

_exports.toJSON = toJSON;
```

But to have a proper Pull Request I have to write a testcase, but I don't know how to do that.
Is there anybody who can give some assistance with that?

Thanks

**Comment by sparkalow** [comment]
You could use the built in [dump](https://mozilla.github.io/nunjucks/templating.html#dump) filter maybe.

**Comment by Gabrz** [comment]
I was able to make a testcase (and documentation) and created a pull request
