### ISSUE TITLE
Understanding what a user defined template means

### ISSUE THREAD

**Issue by blachawk** [mozilla/nunjucks#1342]
Hello,
I'm learning nunjucks for the first time this week.  Your docs mention of a warning that it is not safe to run user-defined templates or inject user-defined content into template definitions. Can someone please explain what that means? and perhaps an example of the right approach to take when using nunjucks?

Does that mean that anything relating to to sensitive (private) data relating to a user or users, should not be used within nunjucks? or is it more than that?

How are user defined templates different from custom .njk templates I create in an express app?

**Comment by ogonkov** [comment]
In your app you can handle user input and forward it to nunjucks engine, for example.

If all your templates under you control, you don't have to worry.
