### ISSUE TITLE
Am I able to insert blocks inside set?

### ISSUE THREAD

**Issue by felipeqq2** [mozilla/nunjucks#1345]
Am I able to insert blocks inside a set element with Nunjucks? Like this:
```
        {% set css %}
        {% block includeCSS %}
            {% include "styles.css" %}
        {% endblock %}
        {% endset %}

        {% set js %}
        {% block includeJS %}
            {% include "script.js" %}
        {% endblock %}
        {% endset %}
```
When I'm running this file: 
```
{% extends 'layouts/default.njk' %}
{% block includeCSS %}CONTENT{% endblock %}
```
 I'm getting an error:
```
Template render error: (./src/_includes/layouts/default.njk)
      Error: unknown block "includeJS"
```
I basically need to have all blocks inside the child template, is there any way to avoid this?

**Comment by glgoose** [comment]
Why do you want to use block assignments inside set block assignments?

**Comment by felipeqq2** [comment]
To change the variable according to the template, but I already managed to do this using macro :)
