### ISSUE TITLE
nunjucks can't find views' path even if I input the absolute path

### ISSUE THREAD

**Issue by kborisov00** [mozilla/nunjucks#1348]
![Screenshot at 2021-03-24 22-49-05](https://user-images.githubusercontent.com/53948066/112381356-29227e00-8cf3-11eb-8f38-c682c2970282.png)
When I build it with webpack, the whole server becomes one file, the views are in a "views" folder in the same directory with the server file, I've tried everything but I keep getting "Template not found" error, which means the views folder was not found.

**Comment by ogonkov** [comment]
Show your webpack config

**Comment by kborisov00** [comment]
Never mind, it was a an issue with the "path" library
