### ISSUE TITLE
Block inside of a conditional expression, check if set

### ISSUE THREAD

**Issue by nodesocket** [mozilla/nunjucks#135]
I am trying to do a conditional block, by checking if the block exists. If so, use it, else use some default markup.

````
    {% if headerNavigation %}
        {% block headerNavigation %}{% endblock %}
    {% else %}
        <ul>
           <li>First</li>
           <li>Second</li>
       <ul>
    {% endif %}
````

But even though `headerNavigation` is defined, it always hits the else statement. How do I check if block `headerNavigation` is set?

**Comment by ArmorDarks** [comment]
In jinja you have to call it via `self`, like described here:

http://stackoverflow.com/questions/18720899/how-can-i-determine-if-a-jinja2-template-block-is-empty

(here is description in docs http://jinja.pocoo.org/docs/dev/templates/#child-template)

So, it have to be `{% if self.headerNavigation() %} - {% endif %}`

However, as far as I remember, nunjucks doesn't support `self` calls. I really hope that it will be implemented in future.

**Comment by jlongster** [comment]
We'll implement self, deferring to #164
