### ISSUE TITLE
implement sourcemaps

### ISSUE THREAD

**Issue by jlongster** [mozilla/nunjucks#136]
It might be easy enough to implement sourcemaps, since we already track the line/col information everywhere. There's a cool library that helps a lot with this I think.

With this, you could literally set breakpoints in your template within the browser and step through it.

**Comment by jlongster** [comment]
I do plan on switching to webpack or browserify, but here I was talking about generating sourcemaps for the actual templates, not nunjucks code. These sourcemaps would map the template code to the generated JS so you could theoretically debug templates straight in the debugger.

I won't have time do this though

**Comment by popomore** [comment]
When will switch to webpack or browserify? Which one do you prefer?
