### ISSUE TITLE
Cannot set headers after they are sent to client ( error from express.js and next.js server using next-routes)

### ISSUE THREAD

**Issue by ahmed-stack** [mozilla/nunjucks#1361]
Hello community, I am facing a frustrating issue :( my server crashes sometimes on development and production. I am using express.js ^4.17.1 and next.js ^9.5.3. Below is my code files. I have defined my custom routes in server side. 

I am using my handler like this, this handler causes the problem, but i have to implement like this for server side rendering.

**import routes from './routes';
const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
const handler = routes.getRequestHandler(app);**

Using this implementation solves the problem but I want to find a solution for above implementation.

**const dev = process.env.NODE_ENV !== 'production';
const app = next({ dev });
const handler = app.getRequestHandler();**

**This is the error I am getting**
![image](https://user-images.githubusercontent.com/55018534/124704203-1e3fd200-df0d-11eb-98df-e3bd19a0938d.png)

**This is my routes file**
![image](https://user-images.githubusercontent.com/55018534/124704497-9efece00-df0d-11eb-9593-af3959865df5.png)

**This is my server file**
![image](https://user-images.githubusercontent.com/55018534/124704704-ef762b80-df0d-11eb-8f6b-5828d72cf291.png)

**Comment by ogonkov** [comment]
It doesn't looks like nunjucks related to me
