### ISSUE TITLE
How to create a Template object with a string?

### ISSUE THREAD

**Issue by tahmidkhan** [mozilla/nunjucks#1367]
I want to create a `Template` object using a string (something like `"<h1>Hello {{ username }}</h1>"`) and then manually call that object's `render()` function. The examples in the docs all use `renderString()` which returns the results after calling `render()`. 

Is there a way to do this? Thanks for any help.

**Comment by tahmidkhan** [comment]
Ok after digging into the codebase, I've found the solution:

```javascript
var myTemplate = new nunjucks.Template(templateString, nunjucksEnv)
```

**Comment by ogonkov** [comment]
You actually want precompile
