### ISSUE TITLE
Make { autoescape: true } the default 

### ISSUE THREAD

**Issue by af** [mozilla/nunjucks#138]
I'm a bit surprised that nunjucks doesn't autoescape by default. I know it's easy to turn on, but having a more secure default setting seems like good practice.

**Comment by zephraph** [comment]
Just thought I'd throw in a [link](http://jinja.pocoo.org/docs/dev/faq/#why-is-autoescaping-not-the-default) to why jinja2 is _not_ autoescaped by default.

**Comment by jlongster** [comment]
we'll consider this again later

**Comment by jlongster** [comment]
Actually, let's do this for 2.0 (moved from https://github.com/mozilla/nunjucks/issues/427)

**Comment by ricordisamoa** [comment]
What about @zephraph's link? (Especially the last paragraph)

**Comment by zephraph** [comment]
So long as I can configure the default, I'm fine.

**Comment by carljm** [comment]
@ricordisamoa Personally I think Jinja2 makes the wrong choice there. It's certainly true that both Jinja and nunjucks can be used to generate things other than HTML (and for that reason autoescape should definitely be configurable), but practically speaking they are by far most commonly used to generate HTML, and the value of secure-by-default in that context should trump the other considerations, IMO.

**Comment by ricordisamoa** [comment]
Interestingly, while Jinja2's autoescaping is turned off by default, Flask automatically turns it on for XML and HTML templates:
http://flask.pocoo.org/docs/dev/templating/#jinja-setup
