### ISSUE TITLE
please add tag for version 3.2.3

### ISSUE THREAD

**Issue by pravi** [mozilla/nunjucks#1405]
Currently latest tag is 3.2.2 even though npm registry has 3.2.3. Please add the tag for 3.2.3 so we can use github repo as source for the debian package instead of npm registry (for building from source).

**Comment by binyamin** [comment]
@pravi In the meantimg, is it possible to use a commit hash?

**Comment by fdintino** [comment]
Sorry for the delay in responding. I've pushed out a tag for the v3.2.3 release.
