### ISSUE TITLE
For filters, if the input is SafeString, the output should also be SafeString

### ISSUE THREAD

**Issue by wenfw** [mozilla/nunjucks#1453]
e.g.

The code below returns a SafeString.

```
{{ some_html_string | filter_returns_safe_string }}
```

Then the code below should return a SafeString too, but it does not.

```
{{ some_html_string | filter_returns_safe_string | upper }}
```

**Comment by crossjs** [comment]
Just discovered that we can use this approach:

```
{{ some_html_string | filter_returns_safe_string | upper | safe }}
```

I'm going to close this issue. Thanks.

**Comment by wenfw** [comment]
Just discovered that we can use this approach:

```
{{ some_html_string | filter_returns_safe_string | upper | safe }}
```

I'm going to close this issue. Thanks.
