### ISSUE TITLE
iOS 7 WebLoader won't work

### ISSUE THREAD

**Issue by aaboyd** [mozilla/nunjucks#172]
The WebLoader in iOS 7 will fail because [synchronous ajax requests are not allowed](http://stackoverflow.com/questions/18965329/ios-7-javascript-xmlhttprequest-bug).  Precompiling templates work fine, and I'm sure a custom async loader would work fine as well.  Submitting this in case anyone runs into this issue in the future.

**Comment by jlongster** [comment]
Thanks for making us aware of it, I won't have any time to work on it thought
