### ISSUE TITLE
[Question] Is there a way to turn off tracebacks?

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/nunjucks#175]
Is there a way to turn off tracebacks in output for a specific environment?

E.g  in the unlikely event a broken template was loaded in a non-development environment, is there a way to prevent tracebacks being shown?

**Comment by jlongster** [comment]
There is not, but that would be a good thing to add. You could attach an error handler, and we already have a function to do some stuff to the error anyway.

**Comment by fdintino** [comment]
Feel free to reopen if I am incorrect, but I believe that handling the error while using [asynchronous rendering](https://mozilla.github.io/nunjucks/api.html#asynchronous-support) can accomplish this.
