### ISSUE TITLE
Swig or Nunjucks?

### ISSUE THREAD

**Issue by kokujin** [mozilla/nunjucks#179]
I am evaluating a templating engine along the lines of the Django/Jinja templating engines. How does Nunjucks stack against Swig?
1. Speed
2. Client side loading as AMD module
3. I did not find any CLI version of Nunjucks, does one exist?

Here is an overview which might help:

http://paularmstrong.github.io/node-templates/

Thanks

**Comment by lichenhao** [comment]
I was wrote a case a few time ago.

https://jsfiddle.net/cLkjp99f/9/

The `swig.js` is best choice for precompile or in browser side.
