### ISSUE TITLE
Support Python's slice notation

### ISSUE THREAD

**Issue by baskerville** [mozilla/nunjucks#188]
It might be worth adding support for Python's slice notation (`foo[start:end:step]`)?

**Comment by TeoTN** [comment]
+1

**Comment by jbmoelker** [comment]
If ever picked up, I'd suggest adding this to [jinja-compat](https://github.com/mozilla/nunjucks/blob/master/src/jinja-compat.js) (see [documentation on installjinjacompat](https://mozilla.github.io/nunjucks/api.html#installjinjacompat)).
