### ISSUE TITLE
most of string filters (capitalize, center, indent, truncate...) failed if left value is not a string

### ISSUE THREAD

**Issue by tdelmas** [mozilla/nunjucks#189]
The comportment of nunjucks is very permissive in some ways : 

"If a value is undefined or null, nothing is displayed. The same behavior occurs when referencing undefined or null objects. The following all output nothing if foo is undefined: {{ foo }}, {{ foo.bar }}, {{ foo.bar.baz }}."

But the simple fact to add a filter can break a template if the value is undefined : 
If foo is undefined, 
{{ foo }} display nothing but {{ foo ¦ truncate }} failed.

I think most string filters for strings should start with :
if ( typeof str !== 'string' ) { return ''; }

**Comment by metasansana** [comment]
Uhh +1... What's the status of this? I was about to create a custom `capitalize` tag and came across this issue. Can I help?

**Comment by garygreen** [comment]
I don't think nunjucks should automatically convert `undefined` or `null` to `''` before pipe to the filter, as some filters can handle arrays, objects, etc. Though I agree it should definitely be handled by the filter itself, to check for instances of an undefined/null and convert to the most 'sane empty' type for that filter so it won't throw an exception.

**Comment by metasansana** [comment]
@garygreen I can do a PR for what @tdelmas suggests for capitalize, center, indent, truncate. I don't see it doing any harm in the interim.

**Comment by jlongster** [comment]
Let's move this into the PR here: https://github.com/mozilla/nunjucks/pull/358 We'll fix it there.

**Comment by jlongster** [comment]
This is fixed on master
