### ISSUE TITLE
make separate loader for precompiled templates

### ISSUE THREAD

**Issue by sunflowerdeath** [mozilla/nunjucks#194]
If i replace WebLoader with my own loader, precompiled templates are not available.

Usage of precompiled templates does not mean than I want to use WebLoader.
For example, i can have my templates in `<script>` tag on the page, not somewhere in the web, but in the same time I want to use some templates in precompiled way.

If u will make separate loaders for precompiled templates and for web loading, it will be possible to use precompiled templates loader with my own loaders together.

Here's example of separate loaders: https://gist.github.com/sunflowerdeath/9093146

**Comment by jlongster** [comment]
closing, please open a PR if you still have ideas

**Comment by jlongster** [comment]
actually we have found some use cases, now there is a builtin PrecompiledLoader
