### ISSUE TITLE
Errors in callbacks reported as template errors

### ISSUE THREAD

**Issue by sambs** [mozilla/nunjucks#199]
For example, calling this function:

    var nunjucks = require('nunjucks');
    var env = new nunjucks.Environment();

    function dodgyThing (context, callback) {
      env.render('show {{item}}', context, function (err, str) {
        throw new Error('Im not a template error');
      });
    }

    dodgyThing({item: 'apple'}, function (){});

gives:

    Template render error: (unknown path)
    Error: Im not a template error
      at Object.exports.withPrettyErrors (/packages/node/nunjucks/src/lib.js:31:17)
      at Obj.extend.render (/packages/node/nunjucks/src/environment.js:338:20)

**Comment by jlongster** [comment]
@sambs I know this is confusing, and we need to explain this better... but you don't need to be async the callback. If you are doing only synchronous stuff, just do `var result = env.render(...)`. If you are doing async stuff, you need to use the callback, and in that case it won't be caught by our handler.

We should make this clearer somehow... async templates were kind of an experiment.
