### ISSUE TITLE
set tag doesn't work with async filters

### ISSUE THREAD

**Issue by tucan** [mozilla/nunjucks#200]
Hello!

I have one issue which doesn't allow me go further with my main work.

Here is sample filter code which I use for testing:

```
_resource = (url, callback) ->
  console.log(arguments)
  callback?(null, 12345)

  'Hello'

env.addFilter('resource', _resource, true)
```

If somewhere in template I write `{% set user = "/users/12345" | resource %}` where `resource` is async filter nunjucks calls my filter as it would be usual sync filter, i.e. w/ callback and uses returned value from my filter. Thus, I have `user` var set to `Hello`.

But if I write something like this `{{ my_macro("/users/12345" | resource) }}` all work as expected. And I in my macro I see `12345` as first param.

**Comment by jmls** [comment]
I'm struggling trying to get some of the built-in filters working with async. For example

```javascript
{% asyncAll property in model.properties | sort (attribute="name") %}
```

doesn't, well, sort ;)

**Comment by etx** [comment]
I'm having the same issue. Nunjucks rocks, I hope this gets looked at soon. 

Basically my filter is not getting a callback when it is used in a set tag.

**Comment by jlongster** [comment]
@jmls we don't use keywards args in our sort yet... this was fixed in https://github.com/mozilla/nunjucks/issues/377
