### ISSUE TITLE
Infinite loop in replace filter

### ISSUE THREAD

**Issue by novaugust** [mozilla/nunjucks#201]
Replace will cause an infinite loop if the new string contains the old string, for example, if you're using replace to escape double-quotes like below.

    replace( '"', '\\"')   

Would there be any problem with just using the built-in javascript replace?

**Comment by jlongster** [comment]
https://github.com/mozilla/nunjucks/pull/321

**Comment by saml** [comment]
Can still reproduce in v1.3.4

Steps to reproduce:

```
$ cd /tmp
$ rm -rf node_modules/
$ npm install nunjucks
$ node
> require('nunjucks').renderString('{{ x|replace("a", "ab") }}', {x:'a'});
```
