### ISSUE TITLE
Render variable as html

### ISSUE THREAD

**Issue by vtsurka** [mozilla/nunjucks#204]
I want render variable content like html.

var export = '<input type="hidden" name="FeedProduct[export]" value="0"><input type="checkbox" id="feedproduct-export" name="FeedProduct[export]" value="1">';

{{ export }} 

but when i call this rendered as string, not html

**Comment by missyjcat** [comment]
@jlongster @garygreen I think I have a similar issue. I have a Nunjucks template `strings.html` and am importing it into `page1.html` (and other places, eg `page2.html`) (just some sample names). Autoescape is false (default) and want to keep it that way.

`strings.html` has:
{% set st1 = '<a href="http://www.google.com">go find it yourself</a>' %}

`page1.html` has
{% from "strings.html" import st1 %}
If you can't find it here, {{ st1 }}

What I expect to see is:
If you can't find it here, __go find it yourself__

What I actually see is:
If you can't find it here, <a href="http://www.google.com">go find it yourself</a>

If I change `page1.html` to 
If you can't find it here, {{ st1|safe }}

I see:
If you can't find it here, __go find it yourself__

BUT, I would like to mark it safe in `strings.html` not in each place where I'm importing it. Doign this doesn't work (nor would I expect it to, but is there some way to mark a string as safe when setting?):
{% set st1 = '<a href="http://www.google.com">go find it yourself</a>'|safe %}

**Comment by Rajdeepc** [comment]
I am returning an html string from a method util.markdown.render(component.description)

How can I render this method as an html objects inside DOM. 

Right now it is printing as string like <p>Some text....

I want it to be printed as a DOM element

**Comment by nsheff** [comment]
@Rajdeepc try using `{{ variable | safe }}`
