### ISSUE TITLE
Custom tag

### ISSUE THREAD

**Issue by arcanis** [mozilla/nunjucks#209]
Hi,

I'm working on a data-binding custom tag. A nice syntax would be :

```
{% dyn user.name | truncate(10) %}
```

I've started a JSFiddle, and read a good part of the doc and other tags source code, but I'm still unsure about how to start parsing this kind of expression. If I'm not mistaken, I'm looking for :

- Parse the `dyn` keyword (by using `.nextToken`)
- Peek the `user.name` expression
- Parse the `user.name | truncate(10)` expression
- Return a CallExtension pointing to a custom function which, when called :
    - Calls `user.on( 'change:name', listener )`
    - Return a text somewhat like `<span id="foo235523"></span>`
    - When called, the `listener` function would do a `$('#foo235523').html(env.renderString("user.name | truncate(10)", { user : user }))`

This approach has unfortunately some issues :

- The DOM tree would be quickly cluttered by 'random' id elements
- The template wouldn't be updated as long as it is not in the DOM document
- I don't know how to peek the `user.name` expression (`parsePostfix()` returns undefined) :(

I think that Angular.js solves the first two issues by manually creating a DOM node (`createTextNode`) in what would be a CallExtension target in nunjucks, then by using this element to update the text. This solution seems hard to achieve with Nunjucks, since it is not DOM-bound.

Have you got any idea which could help me ? Maybe I'm on a totally wrong track !

Thanks,

**Comment by jlongster** [comment]
Hi @arcanis, so sorry nobody replied here. Do you still need help?

fwiw, you can't easily parse an arbitrary expression and then turn it back into a string. You will have to do this instead: {% dyn user template="user.name | truncate(10)" %} or something like that.
