### ISSUE TITLE
IE8 Support for Nunjucks

### ISSUE THREAD

**Issue by DavidBindloss** [mozilla/nunjucks#22]
There is a few issues with nunjucks and cross-browser compatability, namely, IE8 holds no support for Object.create(), so code crashes on line 8 

```
(function() {
var modules = {};
(function() {

// A simple class system, more documentation to come

function extend(cls, name, props) {
    // not supported in IE8
    var prototype = Object.create(cls.prototype);
    var fnTest = /xyz/.test(function(){ xyz; }) ? /\bparent\b/ : /.*/;
    props = props || {};
```

I've made a few changes myself, but nothing to warrant a pull request, all my solutions seem to concern with implementing a custom Object.create method to put in place instead of what Nunjucks is expecting to find in Object.create.

Like so:

```
if (!Object.create) {
    Object.create = function (o) {
        if (arguments.length > 1) {
            throw new Error('Object.create implementation only accepts the first parameter.');
        }
        function F() {}
        F.prototype = o;
        return new F();
    };
}
```

However, this just produces "NaN" in my template when rendered.

Thanks,

David.

**Comment by hyperking** [comment]
Im getting the same error message in IE8 
SCRIPT438: Object doesn't support property or method 'create'
SCRIPT5009: 'nunjucks' is undefined

apparently this isn't fixed??

**Comment by hyperking** [comment]
To those needing explicit directions to resolve this issue using ec5-shim.

**Include both of the following files before loading nunjucks.**
https://raw.githubusercontent.com/es-shims/es5-shim/master/es5-shim.min.js
https://raw.githubusercontent.com/es-shims/es5-shim/master/es5-sham.min.js

**best to combine the two into one js file and load conditionally if browser is ie8 and below**
