### ISSUE TITLE
precompileString() should use the Environment that is passed in

### ISSUE THREAD

**Issue by richard-flosi** [mozilla/nunjucks#229]
When precompiling my templates I am using precompileString and passing in my nunjucks environment with custom filters added like:
`nunjucks.precompileString(content, {name: name, asFunction: true, env: env});`

Currently in `precompile.js` the `_precompile()` method adds the following if `asFunction` is true:
```
if(asFunction) {
    out += 'return function(ctx, cb) { return nunjucks.render("' + name + '", ctx, cb); }';
}
```
As such, filters that were added to the environment `env` that were passed into `precompileString()` are lost. `env.render()` should be used to preserve the Environment.

To work around this for now I'm doing the following in my precompilation step:
```
template = nunjucks.precompileString(content, opts);
template = template.replace('nunjucks.render', 'window.nunjucksEnv.render');
```

And this in my JS app initialization step:
```
// Add nunjucks custom filters
window.nunjucksEnv = new nunjucks.Environment();
window.nunjucksEnv.addFilter('uuid', function(prefix) {
    return prefix + '-' + UUIDjs.create(1).toString();
});
window.nunjucksEnv.loaders[0].precompiled = window.nunjucksPrecompiled;
```

I see 2 possible solutions:
1. Update the `if(asFunction)` check to handle the case when `asFunction` is a string and use that string value instead of the default one.
2. Update `_precompile` to set a `window.nunjucksEnv` much like `window.nunjucksPrecompiled` is being set, then have `asFunction` use `window.nunjucksEnv.render`.

As far as I can tell there isn't an easy way to call `precompileString` without `asFunction` and add our own `asFunction` wrapper which would be another option I'd be open to if someone has a way of doing that. Option 1 above would make such a thing easy.

**Comment by jlongster** [comment]
Sorry never responding :( we will have a wrapper option for precompilation when this lands: https://github.com/mozilla/nunjucks/pull/418
