### ISSUE TITLE
Consider using Browserify for building

### ISSUE THREAD

**Issue by garygreen** [mozilla/nunjucks#238]
I notice in the build it's regex parsing the `require()` statements and building a file for the slim and non-slim versions -- have you considered using Browserify as this is exactly what it does (minus the non-ideal regex parsing)?

**Comment by jlongster** [comment]
Yeah, I definitely want to do this. I'm a webpack fan myself, but to be frank soon I hope to move more responsibility off to contributors, so I'll go with whatever you all want.

**Comment by popomore** [comment]
Which one do you prefer, browserify or webpack? I want to give it a try.

**Comment by jlongster** [comment]
I personally prefer webpack, but mostly because it has all sorts of incredible features for complex sites. Browserify would probably be fine for nunjuck's simple use case of bundling files together for a library.

Go ahead and try webpack, and if someone is really opinionated about browserify they can come convince us to switch.

**Comment by jlongster** [comment]
Good news everybody! I integrated webpack (I found it easier than browserify, and it produces smaller builds). The minified files are quite a bit smaller now:

```
before:
64K    browser/nunjucks-slim.js
32K    browser/nunjucks-slim.min.js
160K   browser/nunjucks.js
88K    browser/nunjucks.min.js

after (w/ webpack):
 68K    browser/nunjucks-slim.js
 24K    browser/nunjucks-slim.min.js
172K    browser/nunjucks.js
 68K    browser/nunjucks.min.js
```

So non-minified files are slightly large, but I guess it uses a more recent/better minifier, and the files are quite a big smaller. I'm quite surprised how much smaller `-slim.min.js` is actually, it dropped by 8K!

**Comment by carljm** [comment]
Awesome! Thanks for all your work on nunjucks, both in writing it and recently getting things back in shape.
