### ISSUE TITLE
Appending to a list

### ISSUE THREAD

**Issue by jbergstroem** [mozilla/nunjucks#240]
I'm trying to append to a list. Jinja2 docs suggest a similar pattern:

```
{% do navigation.append('a string') %}
```

Neither `do` nor `list.append()` seems to exist in nunjucks.

**Comment by rambo-panda** [comment]
```
<<set a = [1,2]>>
<<set a = (a.push(3),a) >>
```

**Comment by tk-codes** [comment]
@rambo-panda 
Your solution works. but how efficient is that?
