### ISSUE TITLE
Mysterious context for 'this' with invoked functions, doesn't include actual context

### ISSUE THREAD

**Issue by rektide** [mozilla/nunjucks#244]
When functions are invoked off the root context, the `this` context does not contain anything I recognize or know what to do with. I haven't found any documentation for the context.

I've poked around with this, but I also cannot seem to find the global context in this.

This is via `myTemplate.render(myContext)`.

**Comment by jlongster** [comment]
Can give an actual code example? Should `this` be one of your objects or are you use wondering what `this` is?
