### ISSUE TITLE
Warn when iterating over an object like an array

### ISSUE THREAD

**Issue by jlongster** [mozilla/nunjucks#28]
It should warn (or do something) when someone tries to do `{% for foo in bar %}` if `bar` is an object instead of an array. Currently, because `bar.length` doesn't exist, it does nothing.

**Comment by jmls** [comment]
did this get implemented ? from the docs (http://mozilla.github.io/nunjucks/templating.html#for) it says " iterates over arrays and dictionaries"

**Comment by jlongster** [comment]
@jmls I forget what was implemented at this point, but `for` can implement over objects with the `for k, v in obj` now, yes.

**Comment by ricordisamoa** [comment]
@jlongster: @devoidfury's Jinja example (iterating over keys only) does not work in Nunjucks.
