### ISSUE TITLE
`length` filter should also handle objects

### ISSUE THREAD

**Issue by jlongster** [mozilla/nunjucks#283]
Make `length` return the number of a keys an object has.

**Comment by ricordisamoa** [comment]
Right, that'd match Jinja2's behaviour given how JavaScript objects are often used as Python dictionaries. But what about objects with a `length` property? That'd be a breaking change...

**Comment by carljm** [comment]
It'd be a minor breaking change, but I still think it's the right thing to do. Marking this as a 3.0 change, since I don't want the breaking change in a 2.x release.

**Comment by carljm** [comment]
I don't think "object with length property" is really a reasonable thing for someone to be taking advantage of currently, so I'm going to consider this a bugfix rather than a breaking change.
