### ISSUE TITLE
Set violates scope of block

### ISSUE THREAD

**Issue by fetis** [mozilla/nunjucks#286]
According Jinja documentation every 'block' creates new scope http://jinja.pocoo.org/docs/dev/templates/#block-nesting-and-scope

But this isn't true for Nunjucks. This code works incorrect on my opinion
```
    {% block test %}
        {% set a = 11 %}
        {% block test2 %}
            {% set a = 12 %}
            {{ a }}
        {% endblock %}
        {{ a }}
    {% endblock %}
```
It produce '12 12' but should '12 11'

**Comment by jlongster** [comment]
Every block does create a new scope, but the way `set` works is that it resolves to the outermost variable. So here you declared and set `a` in the `test` block, so the inner block `test2` sees that `a` exists in the outer block and resolves to it.

It wasn't like this a while back, but was changed after discussion in an issue. I wish I could find it right now but I can't.

If you did `{% set b = 12 %}` and then used `b` in the outer block is would be undefined.

**Comment by ricordisamoa** [comment]
@jlongster the above example definitely outputs '12 11' in Jinja.
