### ISSUE TITLE
Feature Request: make macros better with regard to caller() usage.

### ISSUE THREAD

**Issue by iamjochem** [mozilla/nunjucks#292]
I wanted to create a macro that could be either by passing an argument or by using the `{% call %}` syntax so that template developers could choose which to use depending on what was better suited to the current context (e.g. do they need to generate a big block of HTML or just pass in some object property), additionally it means not having to remember which way is the "correct" way to call a particular macro.

### part 1. Where caller() is not always defined 

currently you need to know whether a macro makes use of the `caller()` function, if it does then using that macro in the "normal" manner e.g.:

```twig
{{ import "macros/foo.html" as "foomacros" }}
{{ foomacros.render_something('bar', 'qux') }}
```
will "explode" with a `caller not defined` error. I think this is a bit of a leaky abstraction ... it would be nice if it made no difference how a macro was called with regard to the macro's internal implementation (i.e. make `caller()` always available and return an empty string by default) .

### part 2. Where the caller() return value only looks like a string

in order determine whether to output anything from a macro I often use the `trim` filter and then check the length of a string, doing this caused me some confusion when applying the technique to the return value of `caller()` ... in turns out that `caller()` returns an object with a `val` property and a custom `toString()` implementation but no `length` property.

-----

I did manage to work around these issues and make a macro do what I want, it ended up looking like this:

```twig
{% macro content_section(title, content) %}
{% set html = content | d('') | trim %}
{% if not html %}{% if caller %}{% set html = caller() | d('') | trim %}{% endif %}{% endif %}
{% set html = html + '' %}{# force caller() value to a string #}
{% if html.length %}
    {# MACRO MEAT GOES HERE #}
{% endif %}
{% endmacro %}
```

I was hoping to do it with somewhat less code:

```twig
{% macro content_section(title, content) %}
{% set html = content | caller() | d('') | trim %}
{% if html.length %}
    {# MACRO MEAT GOES HERE #}
{% endif %}
{% endmacro %}
```

Am I barking up the wrong tree with this request? either way, thanks for reading!

**Comment by carljm** [comment]
Thanks for the suggestion, but the current behavior matches Jinja2, and I think it's reasonable. A macro that uses `caller()` is expecting to be used via a `call` block, and having `caller()` return an empty string if it's not could mask usage errors too easily. If you want a macro that can work either way, I don't think checking another argument's value before trying to use `caller()` is too onerous.
