### ISSUE TITLE
Modify object

### ISSUE THREAD

**Issue by ArmorDarks** [mozilla/nunjucks#313]
Hello

Let's imagine we're having an object:

``` twig
{% set object = {
    title: 'title',
    content: 'content'
} %}
```

Is there any way to modify it's properties without overriding whole object?

For example, like:

``` twig
{% set object.title = 'New title' %}
```

or to add another key:

``` twig
{% set object.test = 'New key value' %}
```

Currently such attempts will return error `TypeError: Cannot call method 'charAt' of undefined`, of course.

Now I wonder, is there any workaroud for it, or it isn't possible and won't be ever possible too?

If I do understand it right, jinja has such possibility, with `do` block
http://stackoverflow.com/questions/11047886/modifying-dictionary-attributes-in-jinja2

**Comment by ArmorDarks** [comment]
Information for those who might stuck with same problem — solution is quite simple — to write few custom filters, they will work like a charm for modifying of arrays or objects.

Few very basic examples for arrays modifications (CoffeeScript):

``` coffee
          # Replace last value of array with `value`
          # @example {% set modifiedArray = myArray|popIn('myValue') %}
          env.addFilter 'popIn', (array, value) ->
            array.pop()
            array.push(value)
            array

          # Add `value` to the end of array
          # @example {% set modifiedArray = myArray|pushIn('myValue') %}
          env.addFilter 'pushIn', (array, value) ->
            array.push(value)
            array
```

With same approach you can write filters for setting objects properties too.

**Comment by jan-dolejsi** [comment]
This does seem to work for this case:

```JavaScript
env.addFilter('setAttribute', function(dictionary, key, value) {
            dictionary[key] = value;
            return dictionary;
        });
```

Usage
```JavaScript
{% set myDict = {"key1": 0, "key2": 0, "key3": 0}%}
{% set myDict = myDict|setAttribute('key2', 123) %}
{{myDict['key2']}}
```
... prints "123"

**Comment by ArmorDarks** [comment]
@jan-dolejsi the output is correct. You've set `key2` to `123`, and it prints `123` afterward. What did you expect?

**Comment by efiand** [comment]
> This looks simpler and sufficient for this case:
> 
> ```js
> env.addFilter('setAttribute', function(dictionary, key, value) {
>             dictionary[key] = value;
>             return dictionary;
>         });
> ```
> 
> Usage
> 
> ```js
> {% set myDict = {"key1": 0, "key2": 0, "key3": 0}%}
> {% set myDict = myDict|setAttribute('key2', 123) %}
> {{myDict['key2']}}
> ```
> 
> ... prints "123" as expected.

Thank you! I had the same problem, this filter solves it!

**Comment by dinhanhthi** [comment]
> This looks simpler and sufficient for this case:
> 
> ```js
> env.addFilter('setAttribute', function(dictionary, key, value) {
>             dictionary[key] = value;
>             return dictionary;
>         });
> ```
> 
> Usage
> 
> ```js
> {% set myDict = {"key1": 0, "key2": 0, "key3": 0}%}
> {% set myDict = myDict|setAttribute('key2', 123) %}
> {{myDict['key2']}}
> ```
> 
> ... prints "123" as expected.

Works like a charm!
