### ISSUE TITLE
Nunjucks docs !== jinja docs

### ISSUE THREAD

**Issue by nelsonpecora** [mozilla/nunjucks#314]
I was looking through the docs for the `replace` filter, since it now supports regex, but couldn't find anything in Jinja about it. After diving into the [github issues](https://github.com/mozilla/nunjucks/pull/279) I finally figured out the syntax (`r/body/flags` rather than javascript's `/body/flags`), and I wanted to add that to the documentation, but it looks like nunjucks just links to Jinja's docs.

It seems like, at least for the filters, Nunjucks is diverting from Jinja. Probably more than just the little issue I saw. Should separate api docs be maintained, or should there be a push to update Jinja to conform to Nunjucks' spec?

**Comment by rhengles** [comment]
I think this needs to be reopened.

See /docs/templating.md#regular-expressions

**Comment by carljm** [comment]
@rhengles Can you clarify specifically what it is that you think needs to be done about the regular expressions docs?

**Comment by carljm** [comment]
Probably opening a new ticket with a clear description of the problem and the preferred resolution (or even better, a PR to fix the issue) would be more useful than reopening this one.
