### ISSUE TITLE
Multi-Tenant templates

### ISSUE THREAD

**Issue by mickr** [mozilla/nunjucks#320]
Hello,
I am building a multi-tenanted application where there may be a different set of templates that need to be rendered per request. I am creating a new environment obj for each request, but I was wondering if there was a way to use a single object, but load different templates on a per request basis.

Thanks!

**Comment by jlongster** [comment]
The infrastructure is not really there for this. Note that you are losing caching by doing this. We just don't support it. If there's anything we can do to help, let us know. I'll be happy to look over a PR.
