### ISSUE TITLE
Access to a the templating context object in global functions

### ISSUE THREAD

**Issue by peleteiro** [mozilla/nunjucks#327]
Just like #109, It would be quite useful to have access to the render context object inside global functions.

A use case:

I have a CMS system and I need a function which returns the url for content. The code bellow should work, as it works if it were a filter.

```javascript
env.addGlobal("urlFor", function (content) {
    return this.ctx.baseUrl + "/" + content.slug;
});
```

Thanks

**Comment by yoshokatana** [comment]
This would also be helpful just in templates themselves. If my context is `{ 'some-random-property': {} }` I'd like to grab the whole context object and do stuff with it (looping, `Object.keys()`, etc). Is this possible at all?

**Comment by ArmorDarks** [comment]
Would be great feature :+1:

**Comment by devoidfury** [comment]
In the meantime, you can work around some of it.

```js
var nunjucks = require('nunjucks');
var env = new nunjucks.Environment();
var nunjucks_globals = require('nunjucks/src/globals.js');

// give access to globals through a global
nunjucks_globals.globals = function() { return nunjucks_globals }


env.addFilter('setCtx', function() { 
    var self = this;
    this.ctx.ctx = function() { return self.ctx }
})
env.addFilter('json', JSON.stringify)

env.addGlobal('test', 'hello')
env.addGlobal('another', 'world')
env.addGlobal('helper', function(ctx) { console.log(ctx().foo) })

env.renderString(
    'This is a test! See full context:\n' +
    '{{ $|setCtx }} \n' + // adds a function to the context that exposes the context
    '{{ globals() }}' + // gives access to the globals object
    '{{ helper(ctx) }}', // pass ctx getter to helper
    {foo: 'bar'}
);
```

**Comment by yoshokatana** [comment]
Yup, I also worked around this with a filter, but it's a little hacky.

```js
env.addFilter('getContent', function () {
  return this.ctx;
}
```

You have to pass _something_ into the filter, which confuses other devs:

```
{% set foo = ""|getContext %}
{{ foo }}
```

**Comment by ArmorDarks** [comment]
Thanks for sharing those workaround. @devoidfury is quite tricky one :)

Is there any chances to see native support?

Thanks in advance!

**Comment by jlongster** [comment]
This wasn't too hard, sorry it took so long!

**Comment by ArmorDarks** [comment]
Nice! Thanks a lot!

**Comment by valtido** [comment]
Isn't this really dangerous security wise?

` return this.ctx;`  would it not also return the settings? as in `this.ctx.settings`? or in template {{ getContext .settings }}

Which in turn has access to the following JSON.stringify object:

`"{"x-powered-by":true,"etag":"weak","env":"development","query parser":"extended","subdomain offset":2,"trust proxy":false,"views":"...\\views","jsonp callback name":"callback","view engine":"njk"}"`


Also not to mention if anything else is exposed to the context, also I wonder why settings has been put on the ctx in the first place?

Any advise?

**Comment by nelsonpecora** [comment]
Hmm! Good point. The native implementation should probably strip that stuff out

**Comment by carljm** [comment]
In general, nunjucks doesn't intend to support untrusted template authors. There are too many ways for a malicious template author to at the very least DoS the system.

That said, I'm not sure either why settings are stored on the context. Convenience maybe?

**Comment by ArmorDarks** [comment]
So far I don't see how those settings could be used in malefic way. Any examples?

**Comment by valtido** [comment]
here is what the object looks like,
```

env                 :"development"
etag                :"weak"
etag fn             :wetag(body, encoding)
jsonp callback name :"callback"
query parser        :"extended"
query parser fn     :parseExtendedQueryString(str)
subdomain offset    :2
trust proxy         :false
trust proxy fn      :trustNone()
view                :NunjucksView(name, opts)
view engine         :"njk"
views               :"C:\Users\..\dev\views"
x-powered-by        :true
```

I was more focused, on the `view` method, they can serve a different view with a bit of hacking.

but what's to say you leave that on, forget all about it, and one day `nunjucks`, decides to extend the settings object to include more sensitive information, the context should display the settings period (as a principal).

I mean security wise, you do not want to expose anything you have explicitly decide to do so.
