### ISSUE TITLE
extending with "../layout.html" results in "template not found" 

### ISSUE THREAD

**Issue by zaach** [mozilla/nunjucks#33]
I'm using express and have my templates set up as:

```
views/
  layout.html
  account/
    create.html

```

Attempting to render `account/create.html` from express results in `Error: template not found: ../layout.html
    at Object.extend.getTemplate (/Users/zcarter/moz/gombot/node_modules/nunjucks/src/environment.js:54:23)`

It seems like this should work.

**Comment by jlongster** [comment]
https://github.com/mozilla/nunjucks/pull/349

**Comment by ndugger** [comment]
@jlongster Hey, this is closed, but I'm still getting this error, and I had just grabbed nunjucks from NPM. Are we sure this is actually fixed?

**Comment by jlongster** [comment]
@ndugger It should be. You may have a different problem. I'd suggest opening a new issue with more details. (Other maintainers are more active than me right now)

**Comment by Toooy** [comment]
same error

**Comment by shanshangzhiren** [comment]
same error

**Comment by fdintino** [comment]
@Tinyuen @shanshangzhiren you almost certainly don't have the same error. Please open a new issue and provide exact details so we can reproduce whatever issue you are having.

**Comment by Tinyuen** [comment]
@fdintino  okay  THX！
