### ISSUE TITLE
Order of block execution suggestion

### ISSUE THREAD

**Issue by michaeldewayneharris** [mozilla/nunjucks#334]
when using template inheritance you usually end up with index.html that looks like something this 
```
{% extends "layout.html"}

{% block content %}
   insert some html here
{% endblock %}
```
and a layout.html that looks like this 
```
<html>
<head>
</head>
<body>
{% block content %}{% endblock %}
</body>
```
What seems to happen is that it first goes out to the layout and it down till it hits a a block then looks in index.html to render that block.  

which makes sense until you have this in your content block in index.html
```
{{ addStyle("someCss.css") }}
```

and layout.html does this in the head of the document
```
{% for style in styles %}
 <link type="text/css" rel="stylesheet" href="{{style}}" />
{% endfor %}
```

because of the way rendering happens the head of the layout gets rendered before the content block renders so the styles never get added to the document.

What would be nice would be if it would render index.html first and store the blocks to later be injected into layout.html in the proper locations.

this can be alleviated slightly with the current code by putting the extends code at the end of index.html instead of at the beginning.  This does however cause it to render twice which is not really ideal and has some other hacks that have to be done to get around it.

**Comment by jlongster** [comment]
Sorry, I agree with others that this goes against how the proposed block inheritance works. You should just create multiple blocks that you can override as @garygreen suggests. I'm glad you found a way to do it in swig.
