### ISSUE TITLE
Async Extensions and Filter in NodeJS environment

### ISSUE THREAD

**Issue by etx** [mozilla/nunjucks#335]
Do async methods work in Nodejs? I cannot get them working with Extensions or Filters.

```this.nunjucksEnv.addFilter('lookup', function(name, callback)```
This gets no callback function passed to the anonymous function.

When trying an Extension the run method does get a callback function but if I do not call it immediately nunjucks just skips over it. If I add a console.log() to the async call in the run method, and in the nunjucks.render callback the log from the render callback ALWAYS fires first. I cannot figure out if this functionality just isn't well tested. '

Sorry, I cannot post code examples as they are fragments scattered throughout the framework (Sails.js)

**Comment by etx** [comment]
I managed to figure this out, kind of. I was wrapping the main layout file with a big {if} to test for an XHR request. After removing that if the async tags work as expected. 

I'm not sure if it's a bug or I'm simply doing something wrong. My setup is Sails.js->Consolidate.js->Nunjucks

**Comment by imjoshholloway** [comment]
@etx It seems you have a similar requirement to mine (being able to do a database query based on what's specified in the template) How's that working? I'm just evaluating templating solutions and nunjucks seems to be the closest to meeting the requirements.

**Comment by etx** [comment]
@imjoshholloway I actually have that working now, after removing the wrapping if tag as mentioned above. I figure maybe the if tag is not async safe. 

But it works well aside from that problem. Also checkout Dust.js as it is also async. I like the nunjucks/twig syntax so I wanted to stick with it.

**Comment by jlongster** [comment]
@etx can you try it again? if should be async safe. if you could paste more examples that would be helpful

**Comment by etx** [comment]
Just tested it. Working now in the master branch. Thanks for the fix!!
