### ISSUE TITLE
Whitespace control

### ISSUE THREAD

**Issue by jbergstroem** [mozilla/nunjucks#34]
Implement proper whitespace control (`{% for item in seq -%}`). Reference implementation found [here](http://jinja.pocoo.org/docs/templates/#whitespace-control).

(I know this is on the missing features list, but its always good to have a specific issue for each case)

**Comment by daslicht** [comment]
how to get rid of the whitespace withoutout wrting all code inline ?

eg:
```
        {% if data.page and
               (apos.pages.isAncestorOf(tab, data.page) or tab._id == data.page._id)
        %}
               current
        {% endif %}
{% endif %}
```

turn into this:

```
<li class="
        
          current
        
      "><a href="/home">New Page</a></li>
```

**Comment by ArmorDarks** [comment]
```jinja
{%- if data.page and
    (apos.pages.isAncestorOf(tab, data.page) or tab._id == data.page._id)
-%}
    current
{%- endif -%}
```
