### ISSUE TITLE
Can I assign values to an object?

### ISSUE THREAD

**Issue by 7nights** [mozilla/nunjucks#343]
e.g.
```
item.value = '100';
item.name = 'apple';
```

I've tried something looks like this: ```{% set item.value = 100 %}``` and got ```TypeError: Cannot call method 'charAt' of undefined```

**Comment by garygreen** [comment]
Sorry but this kind of setting of data in the templating engine isn't supported (jinja doesn't either). I would suggest to do this before rendering in your controller

**Comment by dfcreative** [comment]
That’s unfortunate, as far I can check `{% if settings.flag %}`, but I can’t preset it `{% set settings.flag = 'default_value' %}`

**Comment by ArmorDarks** [comment]
You can do that with custom filters or global functions

**Comment by dfcreative** [comment]
I know, but this is not convenient method. Typically I would like to pass variables to _{% include %}_ to customize it's rendering behavior in a way. For example, with django I do _{% include "picture.html" with class="item-preview" size="m" %}_. The picture.html detects passed variables and falls back to default values like _{% with class=class|default:"picture" %}_. I can't do the same with jinja, and I expect to pass include variable as _{% set picture={ class: "item-preview", size:"m"}_. But in that case I can't ensure defaults in include like so: _{% if not picture.class %}{% set picture.class = "picture" %}{% endif %}_

**Comment by ArmorDarks** [comment]
Well, you still can use filters as workaround. Not ideal, but works.

Jinja has `do` optional extension, which allows you, among other things, to define new properties in objects. But it isn't available for Nunjucks so far, unfortunately.
