### ISSUE TITLE
Whitespace control with comments causing linebreak

### ISSUE THREAD

**Issue by MadLittleMods** [mozilla/nunjucks#345]
I believe comments should not cause the [whitespace control characters](https://github.com/mozilla/nunjucks/issues/34) to stop at the comment block. It should extend to the outer tag ignoring the comment.

**Nunjucks template**
```
<ul>
	{# comment here causes a line break to be left between ul and first li #}
	{%- for item in itemList -%}
		<li>item</li>
	{%- endfor -%}
</ul>
```

**Current Output:**
```
<ul>
	<li>item</li><li>item</li><li>item</li></ul>
```

**Desired Output:**
```
<ul><li>item</li><li>item</li><li>item</li></ul>
```

**Comment by garygreen** [comment]
Duplicate of #332
