### ISSUE TITLE
Autoescape and filter tags

### ISSUE THREAD

**Issue by SamyPesse** [mozilla/nunjucks#350]
I'm currently looking to switch from [Swig](http://paularmstrong.github.io/swig/docs/) to Nunjucks, but it looks like there is no equivalents to:

- autoescape: http://paularmstrong.github.io/swig/docs/tags/#autoescape
- filter: http://paularmstrong.github.io/swig/docs/tags/#filter
- Applying a filter to a string, for example: `{{ "/test.png"|resizeImage(100) }}` is failing on Nunjucks

**Comment by popomore** [comment]
Autoescape: http://mozilla.github.io/nunjucks/api.html#autoescaping

You can set true by default, and use `safe` filter to ignore it http://mozilla.github.io/nunjucks/templating.html#autoescaping

**Comment by popomore** [comment]
filter: http://mozilla.github.io/nunjucks/templating.html#filters

Maybe `resizeImage` is not defined before you use it. You can [custom filters](http://mozilla.github.io/nunjucks/api.html#custom-filters) or use [buildin filters](http://mozilla.github.io/nunjucks/templating.html#builtin-filters).

**Comment by SamyPesse** [comment]
Yes, but if I disable the `autoescape`option, I'll have to escape all my variables in the templates.

I guess the solution is to keep `autoescape: true` then use the `safe` filter, but the problem is then related to the point 2 of my first message (filter tag: http://paularmstrong.github.io/swig/docs/tags/#filter).

I know `resizeImage` is not defined (it's just an exemple), my problem is that there is no tag to apply a filter to all the content,.

My solution to the first 2 points will be:

```
{% filter safe %}
This is a <b>test</b> with a non escaped variable: {{ nonEscapedVariable }}
{% endfilter %}
```

But there is currently no `filter` tag.

**Comment by SamyPesse** [comment]
I'll make a PR for this.

**Comment by popomore** [comment]
You don't want to use filter with every variable, just want a tag apply all vars?

Now solution

```
This is a <b>test</b> with a non escaped variable: {{ nonEscapedVariable1 | safe }}  {{ nonEscapedVariable2 | safe }} 
```

You want

```
{% filter safe %}
This is a <b>test</b> with a non escaped variable: {{ nonEscapedVariable1 }}  {{ nonEscapedVariable2 }} 
{% endfilter %}
```

**Comment by SamyPesse** [comment]
First: the autoescape extension that adds a tag `autoescape`: https://gist.github.com/SamyPesse/409cd5777825099ed445

Do you me to do a PR to add it in the core or do you prefere to keep this as an extension ?

I'm going to do another extension for the `filter` tag.

If you prefer not to include this in the core, I'll publish this as a module on npm.

**Comment by SamyPesse** [comment]
I've created two extensions to solve these problems:

- https://github.com/SamyPesse/nunjucks-filter
- https://github.com/SamyPesse/nunjucks-autoescape

**Comment by jlongster** [comment]
I think these are 2 features that would be nice to have in core; there is already a bug around about having a `filter` block, so that's definitely in the roadmap. If you don't feel like creating a PR (which is fine, I'll mark this bug as something to look into soon (by merging your extensions)

**Comment by alexisg** [comment]
This definitely looks like something that should be merged into core considering that nunjucks seems like such a great alternative coming from swig/django/jinja.
