### ISSUE TITLE
nunjucks causing 200% CPU usage when used with gulp

### ISSUE THREAD

**Issue by callumacrae** [mozilla/nunjucks#356]
gulpfile.js:

```
var gulp = require('gulp');
var nunjucks = require('nunjucks');

gulp.task('build', function (done) {
  nunjucks.renderString('<p></p>', function () {
    done();
  });
});

gulp.task('default', ['build'], function () {});
```

Running `gulp` runs the default task, which calls the build task (usually ~4ms to run) and then keeps the script running. The script isn't doing anything (in theory), but is using a bit under 200% CPU: usually 160–190%.

I don't know how to debug this but it's fairly easy to replicate. I'm pretty sure it's an issue with nunjucks, and have never seen anything like this happen with gulp before.

**Comment by garygreen** [comment]
Duplicate of #289

**Comment by callumacrae** [comment]
Thanks! `watch: false` fixes my issue.
