### ISSUE TITLE
Why is there no `striptags` filter?

### ISSUE THREAD

**Issue by philipwalton** [mozilla/nunjucks#359]
I'm just curious because it's in Jinja2, and it seems like there's no good reason not to include it.

**Comment by zacwitte** [comment]
I was wondering the same with some other filters like `map` and `split` which are super easy to add as a custom filter, but that adds other complexity

**Comment by jlongster** [comment]
I'm open to a PR if you get around to it before me!

**Comment by jbmoelker** [comment]
This issue is resolved in #589. Result on [Templating docs > Strip tags](https://mozilla.github.io/nunjucks/templating.html#striptags-value-preserve_linebreaks). 
So this issue should be closed.
