### ISSUE TITLE
How to do readonly for inputs in macros

### ISSUE THREAD

**Issue by Nijikokun** [mozilla/nunjucks#360]
Maybe its easier than I think, however so far no luck... I've tried:

```
<input {{ 'readonly' if readonly }}> {# unexpected token: = #}
<input {% if readonly %}readonly{% endif %}> {# tag name expected #}
<input readonly="{{ readonly }}"> {# always readonly, this is wrong behavior #}
```

**Comment by oyyd** [comment]
This works to me:
```
<input {% if readonly %}readonly{% endif %}>
```
and it seems that, in Chrome, if you don't want the "input" tag "readonly", you should remove the whole "readonly" attribute. I hope this could help you.

**Comment by Nijikokun** [comment]
Try with some additional arguments this is also in a macro

**Comment by Nijikokun** [comment]
I've figured it out, it was the html processor causing the tags to be converted to attributes. Closing, my bad.

**Comment by niftylettuce** [comment]
@nijikokun I filed an issue #686 to help us out here with this issue.
