### ISSUE TITLE
Minify html option?

### ISSUE THREAD

**Issue by Nijikokun** [mozilla/nunjucks#361]
When using as an engine for a server, is there an option to minify or compress the html? I've read the source and it doesn't appear to currently exist.

If that's the case then, I am requesting one, as I would not want to monkey patch the data stream to do this as it would be better implemented here.

**Comment by popomore** [comment]
I think nunjucks should support internally with an option.

**Comment by Nijikokun** [comment]
> I think nunjucks should support internally with an option.

Yes, this is what I was describing.

**Comment by jlongster** [comment]
I've been hesitant to get into formatting too much with nunjucks, but I'm happy to look at a PR that does this. I definitely don't have time to work on it.

**Comment by Nijikokun** [comment]
Closed without resolution?

**Comment by jbergstroem** [comment]
@Nijikokun the resolution was that @jlongster will review a PR if posted. Personally, I don't think it belongs in a template engine. It should be simple enough for you to create a view helper for it.

**Comment by Nijikokun** [comment]
So anyone who wants proper minified output should create their own helpers to do so? That's absurd.

**Comment by popomore** [comment]
I had looked at this, it's easy to set an option let nunjucks switch all
whitespace on. But the HTML that written in template also should be
stripped, but it's hard to do and not nunjucks's job.
Nijiko Yonskai <notifications@github.com>于2015年5月1日 周五下午3:08写道：

**Comment by jlongster** [comment]
Yes, if you want minified output or want to do anything else with the output, do it after you render nunjucks. I'd be happy to accept a PR that runs custom transformers after rendering and you can publish a modules that does whatever minification you want. We're not going to get into personal preferences of the output.

**Comment by jlongster** [comment]
Note that it doesn't really help to minify HTML - gzipping will essentially get rid of all the whitespace already, and you can't change any of the identifiers.

**Comment by paambaati** [comment]
There's also this simple gist that shows you how to do this - https://gist.github.com/marcusgadbem/ddde8a7ad302134e2c18

**Comment by santoshsahoo** [comment]
This issue with the approach is that the html is process for every single request. If we have this option at nunjucks template compiler level, it can be done once and for good.

**Comment by men232** [comment]
May be this is helpful https://github.com/men232/nunjucks-minify-loaders :)

**Comment by niftylettuce** [comment]
@men232 thank youuuuu ❤️ adding this to <https://github.com/crocodilejs/crocodile-node-mvc-framework>
