### ISSUE TITLE
How to default to FileSystemLoader even when window is present?

### ISSUE THREAD

**Issue by DanielApt** [mozilla/nunjucks#363]
We're testing our components with `mocha-phantomjs` and are pointing it to an html file.

Due to this setup, `window` is present, which forces nunjucks to use `WebLoader`.

The html file we are loading is however *not on a server*, but merely in a filesystem. WebLoader renders its template via `ajax`, and *this* leads to issues. 

Ajax calls return a `NETWORK_ERROR: XMLHttpRequest Exception 101` error, as ajax calls are not allowed to local files.

To address this we'd need to default to the FileSystemLoader. How would we achieve this?

Thank you in advance.

**Comment by jlongster** [comment]
I'm not clear; if you are using phantomjs aren't you still really in a browser? You won't have access to the node APIs required by FileSystemLoader.

Regardless, you can always construct the environment yourself and use `FileSystemLoader`:


```js
var env = new nunjucks.Environment(new FileSystemLoader('views, true));
```

**Comment by DanielApt** [comment]
Thanks @jlongster. I'm not sure if I explained myself correctly, but we basically need a way to load a template file in the browser, without using AJAX. I'm not sure if this is actually possible.

We're simply using phantomjs to look at an html file, not a server. As a result AJAX requests don't work, as it is requesting a local file instead of a file on a server.

**Comment by jlongster** [comment]
The simple way to do that is precompile your templates, then you can just load them in when the page loads.

There is simply no way to external data without AJAX. You can't get access to the filesystem. I can't think of another way that you'd be able to get it, you have to precompile.

**Comment by DanielApt** [comment]
@jlongster Thanks, actually it seems somebody has exactly addresses this scenario for us, as we're using webpack. Check out [jinja-loader](https://github.com/pierreant-p/jinja-loader)
