### ISSUE TITLE
Filter "replace" not working with regexp

### ISSUE THREAD

**Issue by felipenmoura** [mozilla/nunjucks#366]
According to the release v1.1.0 ( https://github.com/mozilla/nunjucks/releases/tag/v1.1.0 ), the filter `replace` should accept RegExps for the first argument.
I am trying this

```javascript
... | replace( /(https?:\/\/[^ ]+)/ , "<a href=\"$1\">$1</a>" )
```

And it is triggering:
Template render error:
unexpected token: /

Am I being noob somewhere?

**Comment by arecaps** [comment]
I am having the same problem

**Comment by rbvea** [comment]
Looks like the syntax would be:

```replace( r/(https?:\/\/[^ ]+)/ , "<a href=\"$1\">$1</a>" )```

**Comment by felipenmoura** [comment]
hm...seems like by using the "r", it stop triggering the error.
But did not apply the replacement either!

**Comment by jlongster** [comment]
Yes, you need to prepend the regex with `r`, like `r/foo/`. It probably wasn't matching the regexp which is why the replacement didn't occur. Please reopen/file a new issue if you still have problems!

**Comment by rhengles** [comment]
This needs to be mentioned on the docs!

**Comment by Jialufeng** [comment]
r/   This is a pit.

**Comment by simontom** [comment]
(This info is for others searching for REGEX among issues)

Hello, I know that's darn ol' thread.
Just wanna add little info - you should not be using quotation marks "" but use apostroph marks '' instead.
Otherwise you get some errors.
