### ISSUE TITLE
Sort filter doesn't seem to be working for me?

### ISSUE THREAD

**Issue by kruncher** [mozilla/nunjucks#367]
Hey guys

I have a template which is using the following:
```
{% for post in posts|sort(attribute='title', reverse=true) %}
<section>
	<h1>{{ post.title }}</h1>
</section>
{% endfor %}
```
The posts are being displayed, but no sorting is happening.

So I added a few lines to the **sort** function inside **filters.js** and found the results unexpected:
```javascript
    sort: function(arr, reverse, caseSens, attr) {
console.log(arr);
console.log(reverse);
console.log(caseSens);
console.log(attr);
console.log('----');
        // Copy it
        arr = lib.map(arr, function(v) { return v; });
```
The following was logged to the console:
```
[ { title: 'z' }, { title: 'a' }, { title: 'c' } ]
{ attribute: 'title', reverse: true, __keywords: true }
undefined
undefined
----
```
So it seems like the arguments are being passed into "reverse" rather than into the separate args. Should the implementation of this filter be something like this instead?
```javascript
    sort: function(arr, args) {
        // Copy it
        arr = lib.map(arr, function(v) { return v; });
...
            if(args.attribute) {
...
```
Cheers

**Comment by kruncher** [comment]
Though I am finding that the following template works:
```
{% for post in posts|sort(true, false, 'title') %}
<section>
    <h1>{{ post.title }}</h1>
</section>
{% endfor %}
```
But the docs seem to suggest that the named arguments are the way to go:
http://jinja.pocoo.org/docs/dev/templates/#sort

**Comment by jlongster** [comment]
We need to make it clear that the filters don't always follow the same convections; the best thing to do right now is look at the source: https://github.com/mozilla/nunjucks/blob/master/src/filters.js

We don't use keyword args yet. We need our own filter documentation soon.

**Comment by chitsaou** [comment]
@kruncher Thanks, you saved my day.

It'd be better if there are usage notices in the document. :)
