### ISSUE TITLE
Support for relative paths breaks watch mechanism in FileSystemLoader

### ISSUE THREAD

**Issue by boutell** [mozilla/nunjucks#376]
This code watches for modified files:

```javascript
                    watcher.on("all", function(event, fullname) {
                        if(event == "change" && fullname in this.pathsToNames) {
                            this.emit('update', this.pathsToNames[fullname]);
                        }
                    }.bind(this));
```

It depends on pathsToNames, which can only have one entry for each path (fullname).

However in the presence of relative path support it is possible for the same template to be loaded via many names.

**Comment by boutell** [comment]
I would suggest:

this.pathsToNames[fullpath] = this.pathsToNames[fullPath] || {};
this.pathsToNames[fullpath][name] = true;

And enumerating the keys of this.pathsToNames[fullpath] to do the update call.

**Comment by boutell** [comment]
Cc: @SamyPesse. I think this goes away if your fix for #378 is accepted.

**Comment by jlongster** [comment]
@boutell did that fix fix this? Sorry I missed this issue. This part of the code is getting hard to understand... does it work now?

**Comment by boutell** [comment]
Yes, the implementation looks correct - relative path interpretation is done prior to cache checking. Thanks.

**Comment by boutell** [comment]
```javascript
            var _name = this.resolveTemplate(this.loaders[i], parentName, name);
            tmpl = this.loaders[i].cache[_name];
```
