### ISSUE TITLE
Strict mode and SyntaxError

### ISSUE THREAD

**Issue by SamyPesse** [mozilla/nunjucks#392]
I know almost nothing about consequence of "strict mode" but since #386 has been merged, include Nunjucks in GitbookIO/gitbook crash on OS X and Windows with:

```
/Users/samypesse/Projects/GitBook/nunjucks/src/precompile.js:61
        function addTemplates(dir) {
        ^^^^^^^^
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Am I doing something wrong?

**Comment by SamyPesse** [comment]
Ok, I think this is not happening in the tests because none of the tests is including `precompile.js` but `index.js`is.

**Comment by SamyPesse** [comment]
@jlongster I can fix this issue as part of #391

**Comment by jlongster** [comment]
Ok, thanks. Just convert it into a `var addTemplates = function() {}`.  I think @popomore was going to fix that in a follow-up PR, but feel free to go ahead and fix it.

**Comment by SamyPesse** [comment]
I fixed it: https://github.com/mozilla/nunjucks/commit/ff075af89dace93044b6f2dde33ee3b3eb68b03e but maybe my solution is not what you expected, just let me know and I'll change it.

I'm also adding a small test for precompile.js (to avoid this kind of situation).

**Comment by Nijikokun** [comment]
:+1: really need this...

**Comment by popomore** [comment]
Yes, that's my fault. There is no testcase for precompile, so I don't see any error about this.

**Comment by popomore** [comment]
Ref https://github.com/mozilla/nunjucks/pull/383#discussion_r25928038

**Comment by popomore** [comment]
Thx @SamyPesse
