### ISSUE TITLE
Object.create IE8 bug

### ISSUE THREAD

**Issue by ernestoferro** [mozilla/nunjucks#394]
This commit https://github.com/mozilla/nunjucks/commit/9d808099f0fab685ffdbf6fdae5cf308f3d5a4f4 introduced Object.create again which is not supported in IE8. I saw that this issue came up before so I'm guessing there's a simple fix for this.

**Comment by lennerd** [comment]
Did you try a polyfill? https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/create#Polyfill

**Comment by garygreen** [comment]
This is a known issue, you may find other's when using IE8 as well. For now you will need shim the functionality like with [es5-shim](https://github.com/kriskowal/es5-shim) which should fix the issue.

**Comment by garygreen** [comment]
Related #171

**Comment by ernestoferro** [comment]
I tried es5-shim, but if I remember correctly Object.bind wasn't implemented. I grabbed an implementation from SO and while it run after that, it failed saying that endif wasn't a valid tag. I ended up using http://ejohn.org/blog/javascript-micro-templating/.

**Comment by adrianstaniloiu** [comment]
any updates on this?

**Comment by jlongster** [comment]
@garygreen what is our IE8 story? I can't quite remember. I thought we did tell people to use es5-shim but according to @ernestoferro that doesn't work?

**Comment by jlongster** [comment]
We've got to have `Object.create`, and apparently es5-shim provides some version of it. I just removed all usages of `.bind`, you could can probably get it working with es5-shim now.
