### ISSUE TITLE
iterating over delimited list

### ISSUE THREAD

**Issue by jmls** [mozilla/nunjucks#396]
is this possible ?

I have a list of items "a,b,c" and need to do a {% for item in "a,b,c" %}

**Comment by lennerd** [comment]
Have a look at custom filters: https://mozilla.github.io/nunjucks/api.html#custom-filters

```` javascript
var nunjucks = require('nunjucks');
var env = new nunjucks.Environment();

env.addFilter('split', function(str, seperator) {
    return str.split(seperator);
});
````

```` jinja
<ul>
{% for item in "a,b,c"|split %}
  <li>{{ item.title }}</li>
{% endfor %}
</ul>
````

**Comment by jmls** [comment]
awesome. thanks so much, will look into those custom filters.

**Comment by jonalex** [comment]
Where would I define those variables?

**Comment by lennerd** [comment]
What do you mean? Which variables?

**Comment by jonalex** [comment]
Sorry, I meant to ask, where would define this new filter before I'm able to invoke it in a file.

I'm working with Apostrophe, which uses nunjucks for templating.

I tried placing this in my app.js, but when I try to use I still get an error that split doesn't exist.

**Comment by jonalex** [comment]
I literaly came across the answer after reaching out. 

[I'll share in case anyone lands here](https://apostrophecms.org/docs/tutorials/howtos/migration.html#adding-nunjucks-helpers-got-easier-and-better)
