### ISSUE TITLE
AngularJS alongside nunjucks?

### ISSUE THREAD

**Issue by mg1075** [mozilla/nunjucks#397]
Nunjucks looks more fully featured than tools like ejs, 
but jutst looking now at the doubly curly brace syntax - `{{ }}`, 
won't that cause conflicts if you are using AngularJS?
If so, what are the work-around options? Changing 
Angular's syntax to be something other than `{{ }}`
would feel very kludgy.

**Comment by devoidfury** [comment]
Yes, you can customize the tag syntax. 

Documentation here: https://mozilla.github.io/nunjucks/api.html#customizing-syntax

**Comment by mg1075** [comment]
Awesome. Thanks for pointing that out.

**Comment by arman-anwar** [comment]
@devoidfury Can add steps here to change double curly braces to something else? I want to use angularjs instead of nunjucks with Adonis.

**Comment by devoidfury** [comment]
@arman-anwar You just pass different options to the nunjucks configuration, like the link shows

```js
var env = nunjucks.configure('/path/to/templates', {
  tags: {
    blockStart: '<%',
    blockEnd: '%>',
    variableStart: '<$',
    variableEnd: '$>',
    commentStart: '<#',
    commentEnd: '#>'
  }
});

// use env
```

If it's part of some other framework, there may be something in their documentation about passing view settings.

**Comment by arman-anwar** [comment]
@devoidfury 
I tried this in 'adonis-framework\src\View\index.js' at line 28
    this.viewsEnv = nunjucks.configure(viewsPath, {
      tags: {
        blockStart: '<%',
        blockEnd: '%>',
        variableStart: '<$',
        variableEnd: '$>',
        commentStart: '<#',
        commentEnd: '#>'
      }
    })

But it does not work. Anyone can suggest right way to implement this?

**Comment by arman-anwar** [comment]
Someone said "use raw tag instead of above changes"
http://adonisjs.com/docs/3.2/templating#_raw

**Comment by dennischow** [comment]
I have tried those solutions in above, and the solution that @arman-anwar mentioned "use raw tag instead of above changes" really did the job well, its clean and simple.

{% raw %} 
-code-
{% endraw %}

**Comment by utsav-upendra** [comment]
> Yes, you can customize the tag syntax.
> 
> Documentation here: https://mozilla.github.io/nunjucks/api.html#customizing-syntax

Thanks a ton
