### ISSUE TITLE
What's the meaning of Nunjucks

### ISSUE THREAD

**Issue by yanxyz** [mozilla/nunjucks#398]
Sorry, this is not a bug report. Could anybody tell me what is the meaning of Nunjucks? I don't find the definition in dictionary or web.

**Comment by ricordisamoa** [comment]
It might be a misspelling of [nunchucks](//en.wiktionary.org/wiki/nunchucks#English), which is in turn derived from [nunchaku](//en.wiktionary.org/wiki/nunchaku#English). Nunchaku's two sticks might be a reference to the logos and names of two popular templating engines, [Handlebars](http://handlebarsjs.com) and [Mustache](//mustache.github.io).
Just taking a wild guess.

**Comment by yanxyz** [comment]
Thx. Google give me this search tip, but I'm not sure.

**Comment by jlongster** [comment]
It is a play on the word "nunchucks", because this engine is [jinja](http://jinja.pocoo.org/) inspired which is a play on the word "ninja".

**Comment by ricordisamoa** [comment]
Thank you! I can finally get to sleep now.
