### ISSUE TITLE
Question about creating tags without parameters

### ISSUE THREAD

**Issue by patrickarlt** [mozilla/nunjucks#402]
@jlongster Here is yet another question about custom tags.

I've been working a pair of helpers for a static site generator I'm working on to make it easier to declare custom helper by wrapping the existing custom tag functionality. I setup a small demo of all this https://github.com/patrickarlt/nunjucks-debug/blob/master/index.js.

Currently I can create a custom tag that highlights block of content. It can accept an optional param to hint the highlighter as to the language, this works great. https://github.com/patrickarlt/nunjucks-debug/blob/master/index.js#L8-L42

```html
{% highlight %}
console.log('no params!');
{% endhighlight %}

{% highlight 'js' %}
console.log('with params!');
{% endhighlight %}
```

However when I try to replicate this for a custom tag that doesn't need a block of content I end with a error I can't seem to work around.

```html
<!-- setup default metadata (title, description) with the defaults from the local variables. -->
{% meta %}

<!-- set metadata overriding local variables -->
{% meta "Title", "Description" %}
```

This example might be a little pointless but you get the idea. Currently I'm stuck on this part https://github.com/patrickarlt/nunjucks-debug/blob/master/index.js#L47-L71. I've figured out that I can see if any arguments are defined by doing `parser.peekToken().type === 'block-end'` if that is `true` then there are no arguments, if its false I can handle it with`parser.parseSignature` and `parser.advanceAfterBlockEnd` just fine.

But when there are no args I cant figure out how to get past certain errors.

```js
parser.skip('meta');
parser.skip(lexer.TOKEN_BLOCK_END);

```

```js
parser.skip(lexer.TOKEN_BLOCK_END);
```

```js
parser.parseSignature(null, true);
parser.advanceAfterBlockEnd(token.value);
```

```js
parser.advanceAfterBlockEnd(token.value);
```

All 4 of those attempts resulted in this error.

```
/Users/patricklocal/code/nunjucks-scratch/node_modules/nunjucks/src/lib.js:39
        throw e;
              ^
Template render error: (/Users/patricklocal/code/nunjucks-scratch/templates/meta-no-params.html)
  SyntaxError: Unexpected token )
```

I'm having trouble figuring out what this error is. Is it possible to define a custom tag like `{% meta %}` with no arguments?

**Comment by sbtoledo** [comment]
Did you found a solution for this?

**Comment by dtothefp** [comment]
@sbtoledo @patrickarlt this hack suggested in issuecomment-34919343 will fix your issue for a tag without an end tag `{% meta %}`

```js
    const args = parser.parseSignature(null, true);
    // You must include this if there are no args to prevent errors
    if (args.children.length === 0) {
      args.addChild(new nodes.Literal(0, 0, ''));
    }
```

Seems it is suggested here https://github.com/jlongster/nunjucks/blob/master/tests/compiler.js#L721 that for a tag with an end tag `{% meta %}{% endmeta %}` you could do

```js
    const args = parser.parseSignature(true);
```
but this does not seem to work without the above hack for no ending tag

**Comment by patrickarlt** [comment]
@dtothefp The first suggestion you made works perfectly for my use case thank you! Im sure someone else will find the other solution useful as well.

What is the issue # for  issuecomment-34919343? I would like to read through the whole issue there as well.

Closing this since my initial question is resolved! Thanks again.
