### ISSUE TITLE
Relative paths in extend

### ISSUE THREAD

**Issue by ArmorDarks** [mozilla/nunjucks#409]
I may be missing something, but relative paths in extend doesn't work for me, despite #349 mentions it as example.

It always returns

```
>>   Error: template not found: ./base.html
```

or

```
>>   Error: template not found: ../base.html
```

I've made branch with test for it:

https://github.com/ArmorDarks/grunt-nunjucks-2-html/tree/feature/relative-extend/tests/extend

**Comment by jlongster** [comment]
Looks like you fixed it?

**Comment by ArmorDarks** [comment]
Unfortunately no... does it work for you?

Maybe it has something to do with fact, that pages rendered into static ones with Grunt tasks, but in theory it shouldn't mess with relative paths resolving.

**Comment by jlongster** [comment]
Ok, I can't remember why I thought you fixed it. I'll play with it and see if I can reproduce.

**Comment by ArmorDarks** [comment]
Thanks, that would be great :)

**Comment by jlongster** [comment]
I just tried `{% extends "./base.html" %}` in `index.html`, and it found `base.html` find. I suspect you have an issue in your paths. I couldn't find a way to run that repo. If you tell me how to run it so I can see that issue, I can try to figure out what's wrong.

**Comment by ArmorDarks** [comment]
@jlongster Sorry for the delay

I've made minimalistic repository, with nothing but needed for testing dependencies:

https://github.com/ArmorDarks/test-relative-paths

Instructions how to run it can be found in readme.

Nunjucks templates in `layouts` should build into `build` directory.

However, since Nunjucks will encounter error due to `./base.nj` and `../outsideBase.nj` extends, it will probably successfully build only 2 of 4 files.

Maybe I'm somehow wrongly understanding concepts of relative paths in extends...

For example, `extends './layouts/sub/base.nj'` will work, but then it makes no difference with just plain '/layouts/sub/base.nj'`. Dot should make it look inside current folder, where extends executed, is it correct?

Though, situation with `..` still unclear... I doubt that it was intended to make it start looking from project root too.

Please, note that you can also provide `paths` for `grunt-html-2-nunjucks` in Gruntfile which will be passed as `paths` to Nunjucks during configuration of Environment, but it doesn't make any difference.

To do that, just uncomment `paths: 'layouts',` in Gruntfile

**Comment by ArmorDarks** [comment]
@jlongster one of devs posted similar issue here https://github.com/mozilla/nunjucks/issues/463

It gave me a thought — maybe it has something to do with fact, that Grunt plugin using `nunjucks.renderString()` method?

In mentioned above issue said, that changing method to `render` actually solves issue. So, maybe for some reason `renderString` method doesn't support relative paths.

I can't test it with `render` method, since Grunt task wasn't designed to work with it, but maybe it will give a clue why it doesn't work on Node and Grunt.

**Comment by ArmorDarks** [comment]
Tested — indeed, for some reason relative paths don't work with `renderString()` method.

@jlongster Is it intentional, or bug?

**Comment by SamyPesse** [comment]
Did you provide a `opts.path` ? (https://github.com/mozilla/nunjucks/blob/master/src/environment.js#L310)

```js
env.renderString('test', {}, { path: path.resolve(__dirname, 'test.html') });
```

**Comment by ArmorDarks** [comment]
Yes, `grunt-nunjucks-2-html` passes it in here: https://github.com/vitkarpov/grunt-nunjucks-2-html/blob/master/tasks/nunjucks.js#L48

In Grunt relative option defined properly

I've tested it once again with [Kotsu](https://github.com/LotusTM/Kotsu) and it's default method set to `render()` — it works as expected. But as soon as I replace `render()` method with `renderString)` in `grunt-nunjucks-2-html` — it throws error related to paths
