### ISSUE TITLE
Expose undefined or missing values

### ISSUE THREAD

**Issue by magnethy** [mozilla/nunjucks#412]
As of #14 undefined values are silently dropped. It would be useful to know if there are any undefined / missing values. E.g. either have an option for throwing an Error object when that happens, or have some meta data passed along to the result object describing which values were undefined.

Any thoughts on this matter and how it would add the most value?

**Comment by ArmorDarks** [comment]
Emitting an non-fatal error (or more kind of warning) sounds great, especially when Nunjucks used in conjuration with Grunt

**Comment by bjrmatos** [comment]
+1 
an option for throwing an Error would reduce a lot of common errors when testing output

**Comment by jlongster** [comment]
It would be neat to do this. I can try to get around to it, would probably be a good first bug for somebody though!

**Comment by jlongster** [comment]
I thought this was a pretty cool feature, so I implemented it. Try it out. Just specify `throwOnUndefined: true` in your options.

**Comment by bjrmatos** [comment]
Is this feature published on NPM?

**Comment by jlongster** [comment]
Not yet, only on master for now. Getting ready to release 2.0.
