### ISSUE TITLE
renderString not working ?

### ISSUE THREAD

**Issue by YoleYu** [mozilla/nunjucks#413]
```javascript
var items = [{ title: "foo", id: 1 }, { title: "bar", id: 2}];
var t="<h1>Posts</h1> <ul> {% for item in items %} <li>{{ item.title }}</li> {% endfor %} </ul>";
var res = nunjucks.renderString(t, items);
console.log(res);
```

The result in console is: 
```
<h1>Posts</h1> <ul>  </ul>
```

There is not content in ul, shouldn't it contain two li element?

I am new for nunjucks and I don't know where is wrong, I am using the latest nunjucks in npm with node.js

**Comment by rhengles** [comment]
You need to pass `var res = nunjucks.renderString(t, {items: items});`, because you're only passing the array to nunjucks, so there's no `items` variable in scope.

**Comment by YoleYu** [comment]
Thanks @rhengles  :)
