### ISSUE TITLE
Calling nested function on variable does not work

### ISSUE THREAD

**Issue by tylkomat** [mozilla/nunjucks#415]
## this works ##
Variable: `test = function() {return 'test'}`
Template: `{{test()}}`

## this not ##
Variable: `test = {test: function() {return 'test'}}`
Template: `{{test.test()}}`
`Error: Unable to call 'test["test"]', which is undefined or falsey`

**Comment by ricordisamoa** [comment]
> Variable: test = {test: function() {return 'test'}

Typo?

**Comment by tylkomat** [comment]
In my example yes. I fixed that. My issue still exists.

**Comment by ricordisamoa** [comment]
@tylkomat did you fix it?

**Comment by tylkomat** [comment]
Yes, sorry, the problem was in another place. Fridays are bad days to create issues ;)
