### ISSUE TITLE
allow suppressing missing-file error on include

### ISSUE THREAD

**Issue by jmls** [mozilla/nunjucks#437]
if you are {% include "someFile.js" %} and someFile.js doesn't exist is it possible to suppress the error and just return an empty string ?

I have a template that makes some includes, and if the included file doesn't exist I don't want the renderer to crap out on me ;)

**Comment by jlongster** [comment]
I'd rather not. Suppressing errors typically is way more frustrating than magically trying to make stuff work. I'd suggest just making sure that file exists but is empty. Open a PR if you want to add an option to the `include` tag to suppress the error, I suppose that could work.

**Comment by MMore** [comment]
I am interested in the same feature, but I am not really familiar with JS and templates for JS at all. I would add an optional parameter like `skipNonExistent`:

`{% include "someFile.js" skipNonExistent %}`

What do you think, @jlongster?

**Comment by carljm** [comment]
Jinja2 has this feature: http://jinja.pocoo.org/docs/dev/templates/#include

I wouldn't have any problem with a pull request implementing it, using the same syntax as Jinja2 (`ignore missing`).

**Comment by MMore** [comment]
It seems I am not deep enough. I am able to do the parsing and I can pass the parameter. But to take care of this parameter and not throw a exception is kind of tricky. Can anyone help me with this part?

**Comment by carljm** [comment]
@MMore I don't have time to look at it in-depth right now, but based on a brief glance it looks to me like `Environment#getTemplate` (in `environment.js`) will need to grow a new boolean parameter to support this feature. The parser should store a new boolean attribute on the include node indicating that missing templates should be ignored, and then in `compiler.js` in `compileInclude` you'd emit the appropriate additional parameter to `getTemplate` depending on the value of the node attribute.

You'll need to check all the loaders (web, filesystem, precompiled) to make sure they return `null` and don't throw an error internally when a template is missing. Then `getTemplate` just needs to return some kind of null template object (whose render method just always returns the empty string) if it gets a null value back from the loader's `getSource` method, and the "ignore missing" flag is set.

That's the direction I'd start in, anyway. Good luck!

**Comment by carljm** [comment]
Fixed with merge of #559
