### ISSUE TITLE
Can I have one template engine with dynamic basepaths (depending on the request)

### ISSUE THREAD

**Issue by mannyvergel** [mozilla/nunjucks#439]
For my specific use case for nunjucks: I have a multiple domains and one web server, can I just use one template engine? The idea is I want to change the base path dynamically depending on the host from the request.

I have this code:

```
nunjucks.Loader.extend({
    async: true,
    init: function(basePath) {
        this.pathsToNames = {};
        this.basePath = basePath;

    },
   
    getSource: function(name, callback) {
        var fullpath = web.fileUtils.joinPath(this.basePath, name);
       
        this. [fullpath] = name;

        dmsUtils.retrieveDoc(fullpath, function(err, doc) {
          if (err) {throw err}
          if (!doc) {
            callback(new Error('Path not found '+ fullpath));
          } else {
            callback(err, {src: doc.content.toString('utf-8'), path: fullpath, noCache: web.conf.isDebug});
          }
        })
      }
  });
```

The problem is, I cannot get any more information in the getSource function other than the name. I cannot pass other parameters e.g. the host name from the request, so I can server the front end depending on that.

Sure, I can pass the dynamic path to ```templateEngine.render(name, options, func)``` however, the problem is when it extends to a template (```{% extends 'templates/plain.html' %}```), this goes directly to the loader's getSource and I don't know where it came from so I wouldn't be able to load a dynamic path for the parent file.  

Is the only way to do this is to dynamically create the template engine when I have the request, and have one template engine per base path? Seems a costly operation. Please advise.

e.g.
```
var templateEnginesCache = {};
function(req, res, next) {
  var hostname = getHostFromRequest(req);
  if (!templateEnginesCache[hostname]) {
    templateEnginesCache[hostname] = loadTemplateEngineBasedFromRequest(req);
  }
  ...
}
```

**Comment by devoidfury** [comment]
You might try pass the dynamic path to `render` and then use relative paths in the templates where you need them: `{% extends './plain.html' %}`

**Comment by mannyvergel** [comment]
Oh, I didn't know nunjucks supported dynamic paths. Thank you.
