### ISSUE TITLE
Using Nunjucks on static sites

### ISSUE THREAD

**Issue by hyperking** [mozilla/nunjucks#440]
Hello, Im considering using nunjucks on my static html site for rendering events.
How would I render the template block directly into the html?
**My index.html**
``` html
<!DOCTYPE html>
<html>
<head>
    <title>My site</title>
</head>
<body>
     <div id="container">
{% block event_widget %}
{% endblock %}
</div>                
</body>
</html>
```

**Within my template file ( views/event_layout.html ) i have the following:**
``` javascript
{% block event_widget %}
<div id="event_list">
<ul>
{% for event in events %}
       <li><a href="{{event.url}}">{{event.name}}</a></li>
	{% endfor %}   
</ul>
{% endblock %}
</div>
```

**my javascript is added in the footer of my index.html file:**

``` javascript
//Initialize template view
nunjucks.configure('views',{ autoescape: false });
//collect data from ajax request
var events = jdata.pages;
//assign data into nunjucks template
var data = nunjucks.render('events.html', {events:  events.entries});

```

**Comment by ArmorDarks** [comment]
You can make your life much easier by using Grunt task [grunt-nunjucks-2-html](https://github.com/vitkarpov/grunt-nunjucks-2-html), for example.

Alternatively, you can learn from it's code how to properly render static websites with Nunjucks.

**Comment by hyperking** [comment]
@ArmorDarks I determined that to render the data into the html layout I needed to call

$('#container').append(data);

grunt method is neat but not what i was seeking.
