### ISSUE TITLE
Escape logic tags in {% raw %}

### ISSUE THREAD

**Issue by iyn** [mozilla/nunjucks#441]
I know that I can use `{% raw %}` to escape `{{ output tags }}`, but it doesn't work with `{% logic tags %}`. Is there a way that `ninjucks` would output `{%`? Like:
```
{% extends "client-base.html" %}
```

My use case is rather unusual: I want to use `nunjucks` to output Django template. I need to use `nunjucks` (or any other JS template engine), because I'm using `webpack` to build static assets and I want to "insert" dynamic script names into the Django template.

**Comment by devoidfury** [comment]
There is an option to change the syntax for nunjucks that would remove the need to use `{% raw %}` in your case, see here: http://mozilla.github.io/nunjucks/api.html#customizing-syntax

Though I do agree that `{% raw %}` should work the same way on logic tags (and comment tags!)

**Comment by iyn** [comment]
Thanks for the reply. Sadly, I can't get it to work. This is my code:
```
 var env = nunjucks.configure(
     { 
       watch: false, 
       tags: {
         blockStart: '<%,
         blockEnd: '%>',
         variableStart: '<$',
         variableEnd: '$>',
         commentStart: '<#',
         commentEnd: '#>'
       }
     }
 );
 var res = env.render('./templates/test.html', templateParams);
```
and this `test.html`:
```
this is a test template
<% raw %>
{{ test }}
{% test2 %}
<% endraw %>
```

I get the error:
```
SyntaxError: Unexpected identifier
```
It still works fine with only `{{ test }}`, but using `{%` or `%}` results in error (`SyntaxError: Unexpected token ILLEGAL` if only one of `{%`, `%}` is used, `SyntaxError: Unexpected identifier` if both).

Any suggestions?

**Comment by devoidfury** [comment]
If you change the syntax of the nunjucks template tags, you shouldn't need the `raw` tag at all, right?

**Comment by iyn** [comment]
I tried both versions. However I realized that it's not the problem with `nunjucks` but with the `webpack` plugin I'm using (`html-webpack-plugin`), `nunjucks` works perfectly fine. I still didn't solve the problem, but I'm closing this issue, since it's not related to `nunjucks`. 

Thank you for your time and sorry for not researching the problem enough.

**Comment by iyn** [comment]
If, by any chance, somebody stumbles upon similar problem, this is my hacky way to "solve" it: https://gist.github.com/iyn/0177e51ae7e005b19e51

I created very simple `webpack` plugin that processes `webpack` stats (object with the info about the build process, generated files etc) sends the array of files to include to `nunjucks` template which then generates Django template. I don't want to write a long essay here, but long story short, I need this to use in production build, because `webpack` generates dynamic filenames (hash of the content) and I want to include them in the Django template automatically after every build. This is because my production scripts often change and dynamic name makes me sure that every time client sees up-to date version of my app.


Too many times I have had this exact experience: https://xkcd.com/979/ ;)
