### ISSUE TITLE
Precompiled Templates with Custom Syntax

### ISSUE THREAD

**Issue by davidchase** [mozilla/nunjucks#446]
I was wondering if I have this setup correctly to make custom syntax work with precompiled templates.

```js
var env = nunjucks.configure(templateLocation, {
    tags: {
        variableStart: '<$',
        variableEnd: '$>'
    }
});

var compiled = nunjucks.precompile(templateLocation + '/template.html', {
    env: env
});
```

`template.html`

```html
<p>hello <$ world $></p>
```

When i render the template it shows up as `<p>hello <$ world $></p>`

however if i dont use the custom syntax everything works.

any ideas?

**Comment by davidchase** [comment]
any thoughts?

**Comment by hyperking** [comment]
@davidchase How did you resolve templating when using loop tags?
See my example below.
`{% for item in array %}{{item}}{% endfor %}`
into
`{$ for item in array $}<$ item $>{$ endfor %}`
