### ISSUE TITLE
Custom functions?

### ISSUE THREAD

**Issue by felixsanz** [mozilla/nunjucks#449]
How to add custom functions like this guys do here? http://apostrophenow.org/howtos/adding-nunjucks-filters-and-functions.html . Anyone knows? :D

Filters require variables to apple, like: foo | filter
Tags require closing tags

So... how to add functions like:

```
 afterInit: function(callback) {
      site.apos.addLocal('doubleIt', function(a) {
        return a * a;
      });
      return callback(null);
    }
```

```
 Two times four is {{ doubleIt(4) }}.
```

??? Thanks!

**Comment by garygreen** [comment]
[`addGlobal`](https://mozilla.github.io/nunjucks/api.html#addglobal)

**Comment by felixsanz** [comment]
Meh, i was doing this:

```
app.locals = {
  settings: app.settings,
  paginate: paginate
};

app.use(function* (next) {
  this.nunjucks.addGlobal(app.locals);
  yield next;
});
```

When i had to use:

```
app.use(function* (next) {
  this.nunjucks.addGlobal('settings', app.settings);
  this.nunjucks.addGlobal('paginate', paginate);
  yield next;
});
```

Feeling stupid for wasting so much time on this u.u

Thanks
