### ISSUE TITLE
Memory leak EventEmitter / chokidar

### ISSUE THREAD

**Issue by felixsanz** [mozilla/nunjucks#450]
Im getting sometimes lot of this errors. I don't usually get them but when i do i get like 10 in the same request. Any idea why this happens? I'm using a wrapper called koajs-nunjucks but the problem is more related to chokidar lib.

```
(node) warning: possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at StatWatcher.addListener (events.js:236:17)
    at Object.fs.watchFile (fs.js:1339:8)
    at EventEmitter.FSWatcher._watch (/home/developer/node1.local/node_modules/koajs-nunjucks/node_modules/nunjucks/node_modules/chokidar/index.js:251:8)
    at EventEmitter.FSWatcher._handleDir (/home/developer/node1.local/node_modules/koajs-nunjucks/node_modules/nunjucks/node_modules/chokidar/index.js:351:8)
    at /home/developer/node1.local/node_modules/koajs-nunjucks/node_modules/nunjucks/node_modules/chokidar/index.js:385:38
    at FSReqWrap.oncomplete (fs.js:78:15)
```

**Comment by paulmillr** [comment]
Seems like invalid usage of chokidar.

https://github.com/mozilla/nunjucks/blob/f92a5bdcbc373162c0d2eb37192a6d5afc043104/src/node-loaders.js#L40

this should be changed to `chokidar.watch(paths)` or similar.

**Comment by felixsanz** [comment]
@paulmillr Thanks for the input.

Line L40 loops all paths and pass them to L42 -> `var watcher = chokidar.watch(p);`. So dunno whats going on.

Lets see what other guys say here about nunjuck usage because i'm not much familiar with it.

**Comment by jlongster** [comment]
Thanks for the report. Are you sure you are watching multiple paths?

I wasn't aware you could pass multiple paths into chokidar, we should fix that.

**Comment by felixsanz** [comment]
I'm using nunjucks on "views". My "views" folder contains .html files and also another folder called "admin" with more .html inside.

**Comment by jlongster** [comment]
@felixsanz it should recursively watch all of that. I was asking if you were specifically passing multiple root paths to nunjucks.

Still, I'm going to fix the chokidar API call, and maybe that will help.
