### ISSUE TITLE
Lower filter throws error on undefined

### ISSUE THREAD

**Issue by surdu** [mozilla/nunjucks#453]
I don't know if this is a bug or intended behaviour, but in my eyes looks like a bug:

When you try to filter a variable that is undefined as in `{{something_undefined | lower}}` it throws an error that you try to call `toLowerCase` on undefined. I would expect a filter to treat this case as empty string not undefined.

Using nunjucks version 1.3.4 in node.js.

**Comment by devoidfury** [comment]
This has been fixed on master.
