### ISSUE TITLE
Error.name property is read-only

### ISSUE THREAD

**Issue by furkanmustafa** [mozilla/nunjucks#454]
I was getting `Uncaught TypeError: Cannot set property name of [object Object] which has only a getter` for a reason I cannot track (an exception raised while nunjucks itself trying to handle an Error).

I've traced it back to here:
https://github.com/mozilla/nunjucks/blob/2c46c55052caf630d8a1df56de81852cadde651b/src/lib.js#L44

Line 45 replaces `err` object with the received `Error` object (if message is an `Error` object).

But later on, it tries to assign `name`, `message`, `lineno`, .. etc. But these properties are apparently read-only on the original/native `Error` object, and it's causing the error I've mentioned.

To make it work for me, I've had to remove line 45 as below.

```diff
exports.TemplateError = function(message, lineno, colno) {
    var err = this;

    if (message instanceof Error) { // for casting regular js errors
-        err = message;
        message = message.name + ': ' + message.message;
    } else {
```

*Disclaimer: I do not understand inner-workings enough to propose a proper solution to merge, that's why I didn't make a PR. I also do not know how to provide an environment to re-produce this problem for you.*

**Comment by jlongster** [comment]
Can you tell me which environment you were hitting that in? Which browser version?

**Comment by furkanmustafa** [comment]
Wow, sorry I forgot to answer. Thanks for the fix.
