### ISSUE TITLE
how to get outer index

### ISSUE THREAD

**Issue by yuyang041060120** [mozilla/nunjucks#456]
res.render('index.html', {list: [['zzz', 'xxx', 'yyy'], ['aaa', 'bbb', 'ccc']]});

    {% for item in list %}
        {% for i in item %}
            {{loop.index}}-{{loop.index}} {{i}}
        {% endfor %}
    {% endfor %}

**Comment by devoidfury** [comment]
Try this:

    res.render('index.html', {list: [['zzz', 'xxx', 'yyy'], ['aaa', 'bbb', 'ccc']]});

    {% for item in list %}
         {% set outeridx = loop.index %}
         {% for i in item %}
            {{outeridx}}-{{loop.index}} {{i}}
         {% endfor %}
    {% endfor %}

**Comment by yuyang041060120** [comment]
It is helpful. Thank you ! But I have another question:how to use layout with Nunjucks? I do like this

default.html

    <!DOCTYPE html>
    <html>
    <head lang="en">
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
    {% block body %}{% endblock %}
    </body>
    </html>
index.html

    {% extends 'layouts/default.html' %}
    {% block body%}
	    //bala bala
    {% endblock %}
If I have 10 pages.I have to write these codes 

    {% extends 'layouts/default.html' %}
    {% block body%}
	    //bala bala
    {% endblock %}
for 10 times.It is trrible,how to solve this problem.

**Comment by devoidfury** [comment]
Nunjucks is designed that way; it uses extends/blocks instead of layout style.

**Comment by yuyang041060120** [comment]
But we have to write the same codes for many times.I think It is not conducive to maintenance!

**Comment by roll** [comment]
It's the same as `layout: layouts/default.html` for maintenance but much more powerful (the jinja way).

**Comment by jlongster** [comment]
Nunjucks (like jinja) is more explicit which make it much easier to override various parts of template and make it clear what's going on. Nothing to do here.
