### ISSUE TITLE
While the file is over 1000KB, It will return a error

### ISSUE THREAD

**Issue by Xuanwo** [mozilla/nunjucks#458]
looks here, https://github.com/hexojs/hexo/issues/1333

**Comment by jlongster** [comment]
Any chance you can attach a reproducible test case, and information about which environment (node, browser, version, etc)?

**Comment by Xuanwo** [comment]
https://github.com/jserme/mahua/blob/gh-pages/ace/worker-xquery.js

With
```
os: Windows_NT 6.3.9600 win32 x64
http_parser: 2.3
node: 0.12.4
v8: 3.28.71.19
uv: 1.5.0
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
```

**Comment by jlongster** [comment]
I don't know what that js file is. Are you trying to render that through nunjucks?

**Comment by Xuanwo** [comment]
Yes

**Comment by jlongster** [comment]
I don't know what is running out of space. This seems like an edge case, so I don't have time to prioritize it. If someone else wants to pick this up, that'd be great.
