### ISSUE TITLE
Overriding a block within an include

### ISSUE THREAD

**Issue by roll** [mozilla/nunjucks#460]
`base.html`
```
{% include 'partial.html' %}
```

`partial.html`
```
{% block contents %}
partial.html
{% endblock %}
```

`extension.html`
```
{% extends 'base.html' %}
{% block contents %}
extension.html
{% endblock %}
```

---

Nunjucks 1.3.4 actual:
```
partial.html
```

Expected (?):
```
extension.html
```

**Comment by devoidfury** [comment]
I'm not sure that using blocks in includes is a good idea -- how should the block resolution be handled?

For example, what happens here?

`partial.html`
```jinja
{% block main %} included {% endblock %}
```

`base.html`
```jinja
{% include 'partial.html' %}
<main>
{% block main %} base {% endblock %}
</main>
```

`example.html`
```jinja
{% extends 'base.html' %}
{% block main %} example {% endblock %}
```

**Comment by roll** [comment]
I suppose the same as here:

```jinja
{% block main %} included {% endblock %}
<main>
{% block main %} base {% endblock %}
</main>
```

It's more a question than a bug report but I thought about includes like macroses to build a template on the first step. May be it works the other way internally.

**Comment by devoidfury** [comment]
I think you're on to something, and that it's something that should be discussed further.

There are some complexities to it, however -- how to handle blocks defined in includes in top level templates, blocks in includes inside top level template blocks[1], blocks in includes in child templates, error messages when there's a block name conflict in included templates where the block should be top level in both places.


[1]
base
```jinja
{% block main %}{% include 'partial' %}{% endblock %}
```

partial
```jinja
{% block extra %}
```
child
```jinja
{% extends 'base' %}

{% block main %}
// some code
{{ super() }}
{% endblock %}

{% block extra %}extra extended{% endblock %}
```

**Comment by jlongster** [comment]
`include` does not create an inheritance so there are lot of complexities with how the inheritance chain for blocks should work. This is simply something I'm not interesting in, honestly, I don't think the return would be enough for the high amount of complexity it would introduce to the code.

Please re-open if you really want to see this. I can label is as an enhancement request if there is further discussion. Closing for now.

**Comment by carljm** [comment]
Not only would this be complex, but it would also break existing uses. Right now an included template has its own totally separate inheritance hierarchy, so it can extend its own base and override blocks from there. So making included templates participate in the inheritance hierarchy of the parent template instead would be a major change that would break existing templates.

**Comment by sbussard** [comment]
[How] Does this relate to #539 ?

**Comment by carljm** [comment]
It doesn't relate to #539, IMO.

**Comment by est** [comment]
is this a bug in JInja2? 

Because this seems related

https://stackoverflow.com/questions/21729864/jinja2-how-to-use-named-blocks-inside-included-templates-inside-extendable-tem

**Comment by candu** [comment]
This reminds me of React's `children` or Vue's slot mechanism, which in turn would suggest a syntax like:

```njk
{% include 'component' %}
  {% block main %}
    <!-- block content here -->
  {% endblock %}
{% endinclude %}
```

which avoids the name collision issue by scoping blocks within the context of the included template.  (I don't know how parser internals work here, though, so no idea how feasible this would be.)

**Comment by stepanjakl** [comment]
+1 for scoping blocks within included template, like @candu suggests
