### ISSUE TITLE
extends relative paths not working in 1.3.4

### ISSUE THREAD

**Issue by waynebloss** [mozilla/nunjucks#463]
In a node.js project, the `extends` tag does not work with paths that are relative to the current file. Instead, all paths have to be relative to the search path that was passed to `nunjucks.configure`.

My setup is pretty simple. I call `env = nunjucks.configure('src/', {watch: false});` and then I call `env.renderString` ~~with an absolute path to~~ for each htm file.

## Update

_Thinking about this just now, the issue occurred to me. I'm not passing an absolute path to nunjucks at all, I'm getting the file text and passing that to env.renderString. This is most likely where the issue lies._

My project structure looks like this:

- project-root/
  - src/
    - index.htm
    - layout.htm
    - sub/
      - index.htm

When I run express or gulp, the `process.cwd` is the project-root.

Inside of the file `src/sub/index.htm`, if I do `{% extends "../layout.htm" %}`, it does *not* work. However, if I do `{% extends "layout.htm" %}` it does work. On further testing, if I move `layout.htm` into it's own sub-directory (like `src/other-dir`), then I have to do `{% extends "other-dir/layout.htm" %}` for things to work...

Can someone please advise?

**Comment by waynebloss** [comment]
I changed my code to use `env.render` and I also changed all relative paths that are being passed to the `extends` tag to use the following form: `extends "./template.htm"` or `extends "../template.htm" because I noticed that if you don't start the path with a dot, then nunjucks seems to treat the path as relative to the search path(s).

**Comment by ArmorDarks** [comment]
Hi

See very similar issue here: https://github.com/mozilla/nunjucks/issues/409

**Comment by waynebloss** [comment]
Thank you.

You know, I had seen that issue earlier and that's not the only one either. In my long journey with Nunjucks, the issue that I've run into the most is with paths and relative paths because every plugin (for express, gulp, grunt, etc) uses a different method and that's why there are like 7 plugins to use nunjucks with gulp alone.

I'm hoping that the one that I released this weekend, [gulp-nunjucks-api](https://github.com/devoptix/gulp-nunjucks-api), will be the last one I have to look at for a while!

**Comment by ArmorDarks** [comment]
@waynebloss I hope so too :) Though, we have to use Grunt.

The thing is that it shouldn't work differently in different environments.

So, maybe it worth reopen issue.
