### ISSUE TITLE
How to access context variable in macro?

### ISSUE THREAD

**Issue by SpringNyan** [mozilla/nunjucks#464]
I have a macro to render csrf token field:
```
{% macro csrf_field() %}
    {% if csrf_token %}
        <input type="hidden" name="_csrf" value="{{ csrf_token }}">
    {% endif %}
{% endmacro %}
```
And then, I import it and call csrf_field() in my view:
```
{% import "../utils.html" as utils %}
<form class="form-horizontal" role="form" method="post">
    {{ utils.csrf_field() }}
</form>
```
I provide 'csrf_token' as a context variable to render function:
```
res.render('index.html', {csrf_token:'23333'});
```

But it won't render csrf token field in my view. Is there any way to access context variable in a macro?

Thanks

**Comment by devoidfury** [comment]
Imported templates (using `import` instead of `include`) don't have access to the current context. Using `import`, you'll probably need to explicitly pass the `csrf_token` to the macro:

```jinja
{% macro csrf_field(csrf_token) %}
    {% if csrf_token %}
        <input type="hidden" name="_csrf" value="{{ csrf_token }}">
    {% endif %}
{% endmacro %}
```

```jinja
{% import "../utils.html" as utils %}
<form class="form-horizontal" role="form" method="post">
    {{ utils.csrf_field(csrf_token) }}
</form>
```

**Comment by garygreen** [comment]
Another option could be to use `addGlobal` which returns the csrf token so it's always available (most likely relates to whole application, so makes sense it's globally available). Then access it like crsf_token() in your macro.
