### ISSUE TITLE
Unable to see a macro defined in an included file

### ISSUE THREAD

**Issue by boutell** [mozilla/nunjucks#466]
Please see:

https://github.com/mozilla/nunjucks/pull/465

For a pull request that adds a unit test for this. It seems pretty straightforward: a macro defined in a file fetched with a simple "include" is not visible after the "include."

**Comment by ArmorDarks** [comment]
Hm, I thought it should work that way...

I've mentioned about it in very old issue https://github.com/mozilla/nunjucks/issues/309, but nobody paid any attention to it, so I thought it's just as per design.

I'm glad that in fact it isn't.

**Comment by boutell** [comment]
Serj, when you found this didn't work, what version of Nunjucks were you
using? I ask because it looks like it ought to work in the 1.x series,
based on the fact that Apostrophe depends on the 1.x series (using the ^ in
package.json).

On Mon, Jun 22, 2015 at 2:37 PM, Serj Lavrin <notifications@github.com>
wrote:

> Hm, I thought it should work that way...
>
> I've mentioned about it in very old issue #309
> <https://github.com/mozilla/nunjucks/issues/309>, but nobody paid any
> attention to it, so I thought it's just as per design.
>
> I'm glad that in fact it isn't.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/nunjucks/issues/466#issuecomment-114211246>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
I can verify this feature works in nunjucks 1.3.4.

On Mon, Jun 22, 2015 at 3:02 PM, Tom Boutell <tom@punkave.com> wrote:

> Serj, when you found this didn't work, what version of Nunjucks were you
> using? I ask because it looks like it ought to work in the 1.x series,
> based on the fact that Apostrophe depends on the 1.x series (using the ^ in
> package.json).
>
> On Mon, Jun 22, 2015 at 2:37 PM, Serj Lavrin <notifications@github.com>
> wrote:
>
>> Hm, I thought it should work that way...
>>
>> I've mentioned about it in very old issue #309
>> <https://github.com/mozilla/nunjucks/issues/309>, but nobody paid any
>> attention to it, so I thought it's just as per design.
>>
>> I'm glad that in fact it isn't.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mozilla/nunjucks/issues/466#issuecomment-114211246>.
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by ArmorDarks** [comment]
Can't tell for sure. Something around `1.1.0`, maybe few minor versions less, but definitely not higher

**Comment by boutell** [comment]
My test passes in v1.3.4. Just verified that.

On Mon, Jun 22, 2015 at 3:15 PM, Serj Lavrin <notifications@github.com>
wrote:

> Can't tell for sure. Something around 1.1.0, maybe few minor versions
> less, but definitely not higher
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/nunjucks/issues/466#issuecomment-114225005>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by boutell** [comment]
(I also updated my test to avoid a false positive due to testing for the
wrong result string.)

On Mon, Jun 22, 2015 at 3:43 PM, Tom Boutell <tom@punkave.com> wrote:

> My test passes in v1.3.4. Just verified that.
>
> On Mon, Jun 22, 2015 at 3:15 PM, Serj Lavrin <notifications@github.com>
> wrote:
>
>> Can't tell for sure. Something around 1.1.0, maybe few minor versions
>> less, but definitely not higher
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mozilla/nunjucks/issues/466#issuecomment-114225005>.
>>
>
>
>
> --
>
>
> *THOMAS BOUTELL, *DEV & OPS
> P'UNK AVENUE | (215) 755-1330  |  punkave.com
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by ArmorDarks** [comment]
Just for the clarity: https://github.com/mozilla/nunjucks/pull/465
