### ISSUE TITLE
Custom tags inside if blocks don't handle errors properly

### ISSUE THREAD

**Issue by stldo** [mozilla/nunjucks#467]
When a custom async tag inside an if block returns an error, it stops the rendering and don't return the error to env.render():

```
Function Test() {
    this.tags = ['test'];

    this.parse = function (parser, nodes, lexer)
    {
        var token = parser.nextToken();
        var args = parser.parseSignature(null, true);
        parser.advanceAfterBlockEnd(token.value);
        return new nodes.CallExtensionAsync(this, 'run', args);
    };

    this.run = function (context, options, callback)
    {
        return callback(new Error('error'));
    };
};

env.addExtension('test', new Test());
```

Template

```
{% if true %}
<img src="{% test attr=true %}" />
{% endif %}
<div></div>
```

will return

```
<img src="<div></div>
```

and no error is received in env.render().

**Comment by jlongster** [comment]
Can you try this on the latest 2.0? The async/if problem should be fixed.

**Comment by sbtoledo** [comment]
Updated to 2.0.0 and still the same behaviour.

**Comment by ivan-kleshnin** [comment]
For me, something weird happens with errors in nested blocks even for sync rendering.
They just silently fail, no console logs, no exceptions... leaving HTML in broken half-rendered state.
I use 2.x.

**Comment by carljm** [comment]
A simplest-case reproduction (or even better, test case in nunjucks suite) would be the next step here.
