### ISSUE TITLE
obj.hasOwnProperty undefined is not a function nodejs

### ISSUE THREAD

**Issue by fotisp** [mozilla/nunjucks#468]
Hello,

I was noticing some discrepancies in some of the rendering of the nunjuck templates. After enough digging around I boiled it down to different nodejs versions between development and production. However the production machine has a more resent version of nodejs.

```
~ > node --version
v0.12.2
```

With version v0.12.x of node, this line

https://github.com/mozilla/nunjucks/blob/master/src/lib.js#L271

fails with **TypeError: undefined is not a function.**

Has anyone encountered this, is there any know workaround?

**Comment by fotisp** [comment]
Sorry,

An example that  causes problems is 
```
        {% for key,value in extra  %}
          <input type="hidden" name="{{ key  }}" value="{{ value }}" />
        {% endfor %}
```
Where extra is just a JSON object.

**Comment by waynebloss** [comment]
@fotisp What do you mean that extra is a JSON object?

I tried the following in node 0.12 and it works fine:

```js
var extra = require('./extra.json');
console.log(extra.hasOwnProperty('key'));
```
and the output is `true`.

This also shows that `extra` has a working `hasOwnProperty` method: `var extra = JSON.parse('{"key": "val"}');`.

**Comment by devoidfury** [comment]
Does the JSON object you've got have a property `hasOwnProperty`? That's the only way I could reproduce that error, `TypeError: undefined is not a function.`

`extra = { hasOwnProperty: undefined }`

**Comment by devoidfury** [comment]
This could also happen if the object does not have `Object` in it's prototype chain, for example:
```js
extra = Object.create(null)
```

The safer way to handle this case would be to change https://github.com/mozilla/nunjucks/blob/master/src/lib.js#L271 to this:
```js
 if(Object.prototype.hasOwnProperty.call(obj, k)) {
```

--- the only issue with that is that it may break some older browser compatibility, so we'd need to add extra logic for that.

**Comment by jlongster** [comment]
@fotisp, can you check out @devoidfury's comments above?

**Comment by fotisp** [comment]
Hi @jlongster, 

I will try to take a look during the weekend and report back.

**Comment by xtr0** [comment]
>This could also happen if the object does not have Object in it's prototype chain, for example:

>```extra = Object.create(null)```

Please note: For example in `express.js` res.locals is created in exactly this way [intentionally](https://github.com/strongloop/express/issues/2771). So if one is using res.locals in `renderString` as a context there is an issue with migration to nunjucks 2+ (yeah, it is possible to replace res.locals with something like _.extend({}, res.locals), but...)

(and sorry for my English)

**Comment by carljm** [comment]
I'm not convinced this is worth fixing, but if someone wanted to look into the browser-compatibility implications of the `Object.prototype.hasOwnProperty.call(...)` solution suggested above, I'd consider it.

**Comment by asprouse** [comment]
@carljm This is enough of a problem that ESLint has a rule about it. http://eslint.org/docs/rules/no-prototype-builtins This setting was enabled in v4 of Airbnb's widely (43k+ stars) used ESLint config. I have noticed some libraries, notably `graphql-js`, creating objects with `Object.create(null);`passing them into nunjucks throws this error.
