### ISSUE TITLE
"replace" filter (and other string-based default filters) not working with undefined strings

### ISSUE THREAD

**Issue by ohmance** [mozilla/nunjucks#471]
I'm using nunjucks as an email templating library where I can put in variables that correspond to user data.  Say a user looks something like this:

{ "first_name": "Bob", "last_name":"Dylan" }

Sometimes a user has a middle name, sometimes they don't have a first name, etc.

I'm attempting to use the "replace" filter (and various other string-based filters).  It works well in most cases unless the property doesn't exist for the user, then it throws an error because the input property is undefined.

Look at nunjucks.js line 4249 where the replace method is defined.  The parameter str will be undefined and thus not have the "replace" method in it's prototype if the input parameter is undefined.

I suggest that a better experience for this and other string-based filters is to add a line line this as the first line:
`str = (str || '')`

This would silently create an empty string if one is not defined.

**Comment by jlongster** [comment]
Can you try on master? I believe the filters have been updated. For example `replace` has all these tests for bad inputs: https://github.com/mozilla/nunjucks/blob/master/tests/filters.js#L307

I'm going to push out 2.0 soon which includes these fixes.

**Comment by carljm** [comment]
Closing due to lack of confirmation that the issue still exists.
