### ISSUE TITLE
custom loader with dynamic includes

### ISSUE THREAD

**Issue by felipenmoura** [mozilla/nunjucks#473]
Hi.
This is more of a question, but couldn't fine more information about custom loaders on the docs!

I have created my own loader, which returns a template from a subscribed list of mine(from memory).
But when I try to load templates with dynamic includes(like "tpl-1", "tpl-2", "tpl-x"), it simply does not work, neither sends the information to the loader!
For example:

```
{% include "tpl-{{tplNum}}" %} // prints "tpl-1" instead of THE template tpl-1's content
{% set theTpl="tpl"+tplNum %}{% include theTpl %} // also prints "tpl-1"
{% include "tpl-" + tplNum %} // throws a "Template render error"
```
In my `getSource` function, I only receive the template itself, with no variables.
Debugging into nunjucks itself, I noticed it is even used to store a cache version of the template(in which case the variable include would not fit).

What is the best suggestion here?

**Comment by garygreen** [comment]
What does your loader look like?

**Comment by felipenmoura** [comment]
I have a TemplateManager, which has all the available templates in memory.
When someone tries and render something using nunjucks, with an included template, my loader simply "bypasses" it:

```javascript
var NunLoader = nun.Loader.extend({
    async: false,
    getSource: function(name){
        return { src: name };
    }
});
```

The name variable here, is actually the template string itself(passed by the TemplateManager).
It comes from a build task that "embeds" some scripts from different projects into the TM.
Yep, I am really not sure if that is the best solution at all, but this is the one that is working now! :p 

But inside this loader, I only receive the template string itself. It doesn't get the variables the user is binding to this render call.

What could be(if there is some) the best solution for such thing?

**Comment by jlongster** [comment]
@felipenmoura You are literally returning the name of the template as the source, so the results you are seeing are consistent with that. You need to return `{ src: lookup(name) }` where `lookup` is the function that looks up into your `TemplateManager` or whatever you have.

**Comment by felipenmoura** [comment]
Oh, great! That makes sense!
I couldn't find such info in any docs! Thanks for clarifying it! :)
