### ISSUE TITLE
CallExtension with no arguments generates incorrect code

### ISSUE THREAD

**Issue by NikolayLiber** [mozilla/nunjucks#477]
I'm trying to write extension that can have no arguments in block signature. CallExtension constructor has check for empty arg parameter and it is been replaced with empty NodeList instance

```javascript
this.args = args || new NodeList();
```

But in *compileCallExtension()* check for empty args looks like

```javascript
       if(args) {
            if(!(args instanceof nodes.NodeList)) {
                this.fail('compileCallExtension: arguments must be a NodeList, ' +
                          'use `parser.parseSignature`');
            }
```

**if (args) is true for empty NodeList instance**. That produces incorrect code. I think args.children.length > 0 condition should also be checked.

**Comment by jlongster** [comment]
An empty NodeList should still fail for `args instanceof nodes.NodeList` though, right? What incorrect code is produced, and for what output? Are you saying that you see that error?

**Comment by carljm** [comment]
Closing due to lack of follow-up.
