### ISSUE TITLE
how to prevent template cache with configrue in express?

### ISSUE THREAD

**Issue by movever** [mozilla/nunjucks#479]
I have tried to 
```
console.log("NODE_ENV: " + process.env.NODE_ENV) //develop
console.log("view-cache-disabled: " + app.disabled("view cache")) //true
nunjucks.configure('views', {
    autoescape: true,
    express: app,
    watch: true,
    noCache: true
});
```
And the page is still old when the template has modified.
hope help

**Comment by movever** [comment]
Sorry to open thi issue, it may be my develop environment's promblem.

**Comment by mikermcneil** [comment]
Hey @movever, do you happen to remember what was happening here?  Someone had a [similar issue](https://github.com/balderdashy/sails/issues/3513) in our project.  Thanks!

**Comment by rrsIPOV** [comment]
I know this is an old issue which was closed, but I ran into something similar.  

For me, I believe it is actually an issue with documentation of the nunjucks.Environment + nunjucks.FileSystemLoader.  nunjucks.FileSystemLoader 

What worked for me was to pass the path or array of paths in as a first argument to then pass a options hash as a second:

<code>
var env = new nunjucks.Environment( new nunjucks.FileSystemLoader(viewsPath, {
        noCache: true,
        watch: true
    }), {
        autoescape: false
    });
</code>
