### ISSUE TITLE
Append/Prepend to blocks

### ISSUE THREAD

**Issue by arieljake** [mozilla/nunjucks#484]
Allow to prepend or append to blocks instead of replace. Suppose for example you have default scripts in a "head" block that you wish to utilize on every page and then add additional scripts into the block while keeping the default/standard ones.

jinja2 has super() but I don't see it in the docs for nunjucks.

For example: http://jade-lang.com/reference/inheritance/

**Comment by carljm** [comment]
I think this is covered by the existing `super()` function. It allows you to include the "parent" block contents anywhere you like in a child block - at the beginning, at the end, or even wrapped by additional content front and back. So the existing feature is actually more flexible than what you've proposed.

**Comment by carljm** [comment]
Oh - I just noticed that you did mention `super()`. Yes, nunjucks has it. The nunjucks docs are not complete, especially where nunjucks' behavior is identical to jinja2 (as is the case with `super()` AFAIK). The nunjucks docs were originally written as more of a "delta from Jinja2" than an attempt at complete docs. Though I don't think there's any objection to making them more complete, so if you'd like to send a pull request to add `super()` to the docs, that'd be great!

**Comment by ricordisamoa** [comment]
> jinja2 has super() but I don't see it in the docs for nunjucks.

#435
