### ISSUE TITLE
Env add functions should ideally return env object

### ISSUE THREAD

**Issue by robgraeber** [mozilla/nunjucks#485]
Sometimes when configuring Nunjucks I want to just chain the addFilter / addGlobal functions etc. Does anyone else think it would make sense if addFilter / addGlobal would return the env object? 

So code like this would be possible:
```
Nunjucks.configure(templateDir, {
    autoescape: true,
    trimBlocks: true,
    lstripBlocks: true,
    express: app
}).addGlobal('func1', function(arg) {
    return 'asdf'
}).addGlobal('func2', function(arg) {
    return 'asdf'
}).addGlobal('func3', function(arg) {
    return 'asdf'
}).addGlobal('func4', function(arg) {
    return 'asdf'
});
```

I could do the PR if others thought it was a good idea. These are the functions I was thinking of making chainable:
```
addFilter
addGlobal
addBlock
addExtension
express
```

**Comment by devoidfury** [comment]
Yes, this would be a nice touch, I agree.

**Comment by jlongster** [comment]
Works for me, feel free to open a PR!
