### ISSUE TITLE
Document the dangers of watch: true option.

### ISSUE THREAD

**Issue by stefanmaric** [mozilla/nunjucks#486]
I know nunjucks 2 is coming soon and it will have the `watch` option disabled by default as opposed to current 1.x series.

Anyway, dangers of `watch: true` should be documented for both, current 1.x versions and next 2.x versions, no matter is it is the default or not.

I spent a good amount of time debugging a script that didn't exit. Here some threads about `watch: true` issues:

* #369 
* #429 
* #356

**Comment by jlongster** [comment]
Just pushed 2.0 where watch is disabled by default. I don't see any dangers if you explicity opt in. Plus it's not really "dangerous" as much as just a process that doesn't exit, which is clearly documented.
