### ISSUE TITLE
Filters and simple API

### ISSUE THREAD

**Issue by slavafomin** [mozilla/nunjucks#490]
Hello!

When Nunjucks is used via Simple API methods it internally creates an environment and uses it to render templates, etc. I have a code that uses Simple API that I can't control and I want to add filters to this global environment. If I call `configure()` manually and provide the filters it then gets called again by the third party code and my filters are gone.

Maybe there is a way to extend design of the Nunjucks in order to overcome this issue? For example Nunjucks could leave the existing environment when `configure()` is called and merge new configuration into it, instead of dropping the previous environment and creating a new one.

Thanks!

---

P/S: right now I have to use this somewhat ugly workaround:

```javascript
// Overriding nunjucks configuration function.
var nunjucks = require('nunjucks');
var parentConfigure = nunjucks.configure;
nunjucks.configure = function () {
  var env = parentConfigure.apply(nunjucks, arguments);
  env.addFilter('foo', function () {
    return 'FOO';
  });
  return env;
};
```

**Comment by jlongster** [comment]
The use case is to capture the environment at the point `configure` is called originally. Why can't you do it where it was called at first? I don't want to make the API too complex.

**Comment by carljm** [comment]
The answer here is to submit a pull request to the third-party project to make their use of nunjucks more configurable. The simple API is only intended for simple cases.
