### ISSUE TITLE
Error while trying to use filter

### ISSUE THREAD

**Issue by niksy** [mozilla/nunjucks#493]
I have module which precompiles template using [nunjucksify](https://github.com/rotundasoftware/nunjucksify):

```javascript
var template = require('template.nunj');
function render ( data ) {
    return template.render(data);
}
```

And template used in that module is:
```
Capitalize: {{ capitalize("aaa") }}
```

When trying to use capitalize filter I get this error:

```
Uncaught Template render error: (unknown path)
Error: Unable to call `capitalize`, which is undefined or falsey
```

Application uses slim version of nunjucks. Is this something related to nunjucks or nunjucksify?

**Comment by ricordisamoa** [comment]
Aren't you looking for `{{ "aaa"|capitalize }}`?

**Comment by niksy** [comment]
Huh, it really works. Must have missed something. Closing issue.
