### ISSUE TITLE
Includes and extends are cached, and aren't updated when watch=false

### ISSUE THREAD

**Issue by ismay** [mozilla/nunjucks#496]
Test case [here](https://github.com/ismay/ismaywolff.nl/tree/11ccc2106d542f3377b8c36ad2cc6c884e20f195)

With the test-case, when running `make watch`, the nunjucks watcher is disabled with:

```javascript
nunjucks.configure({
  watch: false
});
```

since it conflicted with the watcher I'm using. Everything works fine, except for updates to included and extended templates. Any changes to these templates aren't picked up by nunjucks (it seems to be caching them), other templates are updated just fine. I couldn't find a way in the documentation to simply disable all caching. Is there a way to do such a thing?

I would expect just a `cache: false` option to allow you to disable caching, like with other templating languages.

**Comment by jlongster** [comment]
There is, it's `noCache`: http://mozilla.github.io/nunjucks/api.html#configure Does that help?

**Comment by ismay** [comment]
I've tried that. `noCache` needs to be configured on the loader right? That didn't work for me (not sure what the specific error was). But I've switched to swig in the meantime, so I'm fine with closing this question. Thanks anyway :)!

**Comment by jlongster** [comment]
`noCache` can be used with `nunjucks.configure`, and it should work. You can also pass it into a loader instance if you are manually creating them, yes, and it will tell the environment not to cache it.

**Comment by ismay** [comment]
Ok, then it’s probably a configuration mistake on my part. If I encounter it again I’ll report back with a more detailed description of what’s happening.
