### ISSUE TITLE
TypeError: Cannot read property 'compile' of undefined

### ISSUE THREAD

**Issue by gig177** [mozilla/nunjucks#498]
I use nunjucks-slim with precompiled templates. My loader looks like this:
```
var MyLoader = nunjucks.Loader.extend({
    getSource: function(name) {
        return {
            src : nunjucksPrecompiled['layouts/some-app/tpl/' + name]
        }
    }
});
```
And use like:
```
var env = new nunjucks.Environment(new MyLoader());
env.render('some.html')
```
What i was wrong?

**Comment by jlongster** [comment]
You need to return `{ src: { type: 'code', obj: nunjucksPrecompiled[name] } }` if you want to return a precompiled template from `getSource`.

**Comment by gig177** [comment]
Where can i read about this behavior? This is not obviously.

**Comment by jlongster** [comment]
It's internal, not meant to be documented. You should just use the `PrecompiledLoader` in addition to your own loader to load precompiled templates: https://github.com/mozilla/nunjucks/blob/master/src/precompiled-loader.js

**Comment by gig177** [comment]
Many thanks.
