### ISSUE TITLE
Maintain changelog in the repo?

### ISSUE THREAD

**Issue by carljm** [mozilla/nunjucks#505]
This is a question for the other maintainers ( @jlongster @SamyPesse @AaronO @jgerigmeyer):

Currently the `CHANGELOG.md` file just links to https://github.com/mozilla/nunjucks/releases

Personally I would prefer to maintain a changelog in the repo itself, for several reasons:

* I find it easier to write a changelog entry when merging a change (so the important user-facing aspects of the change are fresh in my mind) than to have to look back over the entire commit history at release time.

* I prefer to minimize the amount of work necessary to make a release, and "scan the entire commit history since the last release and try to remember what each change was about" is too much work for me :-)

* I prefer to have the changelog version-tracked with the code than sitting in a GitHub-locked area (we can still copy from the repo's changelog into the GitHub release description at release time).

So specifically I am proposing that starting at version 2.0 we maintain an actual change-log in `CHANGELOG.md`. It would only include a summary of user-facing changes; it's not just a copy of the git commit history.

Any thoughts or objections?

**Comment by jgerigmeyer** [comment]
:+1:

**Comment by AaronO** [comment]
:+1: I think it's nicer to have the changelog consolidated in `CHANGELOG.md` it allows a user to grasp the project's history simply by looking at a single file.

Ideally we probably want to import the old changelogs from Tumblr and the release pages for completeness sake (and to avoid further fragmentation).

**Comment by carljm** [comment]
I consolidated the changelog from the two existing locations into `CHANGELOG.md`. PR at #506. Will merge in a day or so, unless anyone notices a problem.

**Comment by jlongster** [comment]
+1 for this. Github's release docs are nice because it's easy to reference to issues and comments, which was the main reason I started using it. I had a CHANGELOG at some point, and I can't remember exactly why I converted over. But I agree that a normal file has benefits, particularly being able to tell PRs to make an entry in it.

**Comment by SamyPesse** [comment]
:+1: Good idea

**Comment by carljm** [comment]
Thanks for the feedback, everyone. Fixed with merge of #506.
