### ISSUE TITLE
the raw

### ISSUE THREAD

**Issue by atmjs** [mozilla/nunjucks#508]
header.html
```html
<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>raw</title>
</head>
<body>
```
footer.html
```html
</body>
</html>
```
index.html
```html
{% include './layout/header.html' %}
<h1>
    {{title}}
</h1>
<div>
    {% raw %}
    {{test}}
    {% endraw %}
</div>
{% include './layout/footer.html' %}
```
the html after compile
```html

<!doctype html>
<html>
<head>
    <meta charset="UTF-8">
    <title>raw</title>
</head>
<body>

<h1>
    Express
</h1>
<div>
    
    {{test}}
    {% endraw %}
</div>
{% include './layout/footer.html' %}
```
when i remove the include codes in index.html , it turned to be ok!

**Comment by atmjs** [comment]
the version of nunjucks is 2.0.0

**Comment by ricordisamoa** [comment]
The latest nunjucks from Git works as expected, likely fixed by #503.

**Comment by atmjs** [comment]
it works expected after i added the code 
```html
{% include './layout/footer.html' %}
```

**Comment by atmjs** [comment]
@ricordisamoa  yes,it is! but why not public the latest version on npm?

**Comment by ricordisamoa** [comment]
@AaronO @carljm  @SamyPesse

**Comment by AaronO** [comment]
@carljm I think we should bump and ship a new release with Samy and my PRs merged, that fix some important issues. Do you have NPM access ?

**Comment by carljm** [comment]
@AaronO According to `npm owner ls nunjucks`, I don't; only @jlongster does still. James, could you add some of us? If so, I could roll a release sometime during this next week.

**Comment by jlongster** [comment]
Will do!
