### ISSUE TITLE
Browser build

### ISSUE THREAD

**Issue by arthurjamain** [mozilla/nunjucks#515]
Hi there !

There seems to be an issue with the browser build. Whenever i require it inside a project, I get an empty object.

After skimming through the file it feels like a webpack-related problem as the module.exports lines seem to be at fault. I can dig more if needed / if you don't have an obvious solution.

Thanks for reading,

**Comment by ricordisamoa** [comment]
#507?

**Comment by arthurjamain** [comment]
Yep, hadn't seen, my bad. Thanks !
