### ISSUE TITLE
verbose error messages with dev mode broken

### ISSUE THREAD

**Issue by tpetry** [mozilla/nunjucks#516]
Hi,
it seems there's a bug with the ``prettifyError`` function in dev-mode. ``prettifyError`` needs the ``withInternals`` param to display verbose error messages [1]. If compiling a template fails, ``prettifyError`` is called with the ``dev``-flag in the ``env``-object [2].

The problem is now that setting the ``dev``-flag (with ``nunjucks.configure({dev: true})``) changes ``this.env.opts.dev``, so a lookup for the flag is done at the wrong object and the dev-mode is never activated.

[1] ``exports.prettifyError = function(path, withInternals, err) {``
[2] ``var err = lib.prettifyError(this.path, this.env.dev, _err);``

**Comment by carljm** [comment]
@soswow looks like you've fixed this in your fork? Fix looks pretty good, any interest in submitting it as a PR?

**Comment by soswow** [comment]
@carljm it is in PR for a month already

**Comment by carljm** [comment]
Ha, sorry for that! I guess I went through all the issues yesterday, but forgot that GH no longer includes PRs in the issues list, and never actually went through the open PRs :-) I'll do that now.

**Comment by carljm** [comment]
Fixed in 0b2fb96ae27e9ad34d32e7b1786cbc6ece190603
