### ISSUE TITLE
nunjucks exception handling obscures the throw site for exceptions not thrown by nunjucks itself

### ISSUE THREAD

**Issue by novocaine** [mozilla/nunjucks#52]
Hey,

when an error is thrown during tryTemplate we have a fairly reasonable try/catch block that rethrows the error so some error information is recorded.

unfortunately this is often quite cryptic, and often it is better to see the exact point in generated template code where it was thrown, particularly if it is a js error thrown during rendering rather than an error explicitly thrown by nunjucks (theres no line, col info).

in chrome I can get the behaviour i want if i enable 'pause on exceptions' and then comment out the try/catch block. this causes a pause in the generated code itself, even though its a dynamically created Function(). quite nice. 

![Screen Shot 2013-02-04 at 12 35 47 PM](https://f.cloud.github.com/assets/57377/122538/629a863c-6e6b-11e2-9439-f2d1e48cadab.png)

would you accept a patch that makes a dont_catch variable available (similar to .dev), which causes thrown exceptions to not be caught the nunjucks handler?

**Comment by jlongster** [comment]
let me know if you're still interested in doing this :)
