### ISSUE TITLE
Unknown path in errors from `renderString()` method

### ISSUE THREAD

**Issue by ArmorDarks** [mozilla/nunjucks#529]
Seems that `renderString()` method doesn't pass `path` properly in case of errors, which results in `unknown path`:

![2015-09-19_12-24-52](https://cloud.githubusercontent.com/assets/4460311/9975590/80594982-5ec9-11e5-80c0-4cdd6524e9ee.png)

If `render()` used instead, everything works fine and we can see full path:

![2015-09-21_09-25-32](https://cloud.githubusercontent.com/assets/4460311/9986234/caca4b4a-6042-11e5-9677-66e23ba96d8e.png)

That behavior can be reproduced with that Grunt task: https://github.com/vitkarpov/grunt-nunjucks-2-html

Just ensure that you have Grunt. then run `npm install` and then `grunt test`

Don't forget to introduce any error in templates (for example here https://github.com/vitkarpov/grunt-nunjucks-2-html/blob/master/tests/base/input.html) to enforce error appereance.

**Comment by ArmorDarks** [comment]
Well stop... Only know I have realized... how `renderString` could know about any path at all, if it's a plain string passed inside function?

So, it seems to be correct behavior, though, slightly confusing.

**Comment by carljm** [comment]
Hmm, I thought it was a crash in case of the missing path, but now that I look more carefully it's not. I agree this is expected behavior.
