### ISSUE TITLE
Add new gloabal filter to get keys from object

### ISSUE THREAD

**Issue by hyperking** [mozilla/nunjucks#530]
example filter to be added globally. Jinja has an extension for calling iteritems() that returns an object array keys only.

```JS
env.addFilter('getkeys',function(object){
        if(Object.prototype.toString.call( object ) === '[object Array]')
        for (var i = object.length - 1; i >= 0; i--) {
            return Object.keys(object[i])
        }else{
            return Object.keys(object)
        };
        // return Object.keys(object);
    })
```

**usage**
```jinja
{% for key in data|getkeys() %}
<li>{{key}}</li>
{% endfor %}

```

**Comment by carljm** [comment]
You can do this by running `nunjucks.installJinjaCompat()`, at which point objects will have both `.keys()` and `.items()` (as well as `.iterkeys()` and `.iteritems()`) methods you can use in the template. So your usage example would look like:

```
{% for key in data.keys() %}
  <li>{{ key }}</li>
{% endfor %}
```

I don't think we need to also add a filter to do the same thing.

**Comment by hyperking** [comment]
@carljm How would I include my new filters without calling them on every project?

```JS
//Build Nunjucks
var data = instance.settings.collection;
var env = nunjucks.configure('/file/hyperking/templates');
//Custom Nunjucks filters
env.addFilter('sortby', function(array, key){
return array.sort(function(a, b) {
    var x = a[key]; var y = b[key];
    return ((x < y) ? -1 : ((x > y) ? 1 : 0));
    });
});

env.addFilter('tostring', function(obj, type){
	if (type == 'json'){
	return JSON.stringify(obj,null,'\t')
	}else{
		return String(obj)
	}
});
env.addFilter('getkeys',function(object, cursorPos){
    var keys;
    if(Object.prototype.toString.call( object ) === '[object Array]'){
        keys = Object.keys(object[0]);
    }else{
        keys = Object.keys(object);
    }
    return (cursorPos === undefined)?keys : keys[cursorPos]
})
env.addFilter('date',function(input, format){
    var d = new Date(input);
    return moment(input).format(format);
});
var hypertable = env.render('examples.html', {"data":data});
$('#js-view').prepend(hypertable);
```

**Comment by carljm** [comment]
@hyperking You can package the functions up in a reusable module, and then just have `addFilter` one-liners on each project. If you have too many of the latter, your reusable module could even expose a function that takes an `env` and then adds a bunch of stuff to it, so you've only got a single call you need to make on each project. Hard to say more details without knowing how you package your JS, since there are so many different options in that area. In any case, this is getting a bit off-topic for this bug...

**Comment by hyperking** [comment]
@carljm Im not running Node or express if thats what your asking.

the documentation leaves a lot to be desired when it comes to instructions. I primarily use nunjucks on the frontend of static sites to show events and blogs.

The more i can learn about nunjucks the more i could contribute.

**Comment by carljm** [comment]
@hyperking It's not `env.installJinjaCompat()`, it's `nunjucks.installJinjaCompat()`.

The docs could definitely use some love, especially in the getting-started area.

**Comment by hyperking** [comment]
`nunjucks.installJinjaCompat()` doesn't work either. Probably why i decided to build filters.

**Comment by carljm** [comment]
You might be using an older version of nunjucks; `installJinjaCompat()` was only added in 2.0, which was released just a few weeks ago.

**Comment by what1s1ove** [comment]
I still think it would be a useful feature
