### ISSUE TITLE
Add support for "tests".

### ISSUE THREAD

**Issue by andrewchernow** [mozilla/nunjucks#532]
I was wondering if there is any plan to include tests, like `{% if number is even and items is empty %}` just like Twig has. Twig also offers custom tests, which my project uses quite a bit. I only ask because for the most part my server-side Twig templates work with nunjucks (with a few custom filters), but its missing tests.

**Comment by carljm** [comment]
No, nunjucks currently doesn't have tests. Nunjucks' primary inspiration is Jinja2, and if tests were added they should be fully Jinja-compatible: http://jinja.pocoo.org/docs/dev/templates/#tests

If Twig tests work just like Jinja tests, then that would mean they'd be Twig-compatible, too.

I'm not opposed to adding this, if somebody submitted a PR for it. In practice I just use functions or filters instead and it works fine; tests are just a bit of syntactic sugar that isn't strictly necessary.

**Comment by andrewchernow** [comment]
Yes, Jinja and Twig appear to work the same in regard to tests. Some name differences but that can be solved with custom tests. 

But no, they are  a "needed" feature; although nice to have for readability and in this case compatibility.

I was trying to avoid changing around 20 twig templates I am sharing between nunjucks and twig that use tests. Around 30 templates worked without any changes at all to the Twig templates but needed some filters for nunjucks: like `| raw` instead of `| safe` which just returns a SafeString, or `| date` which I implemented using php.js's version (since Twig is a wrapper to php `date()`), `number_format` again using php.js's version, and around 5 other ones. 

Good news is, nunjucks is pretty well compatible with Twig (at least the features my projects use).

**Comment by andrewchernow** [comment]
>>But no, they are a "needed" feature
But no, they are NOT a "needed" feature

**Comment by carljm** [comment]
Looks like Twig was originally created by Armin Ronacher, the author of Jinja2. So it's not surprising they are fairly compatible :-)

**Comment by ogonkov** [comment]
Already implemented
