### ISSUE TITLE
How to handle a skeleton structure?

### ISSUE THREAD

**Issue by kamlekar** [mozilla/nunjucks#535]
This is a question. Suppose I have a skeleton structure, which I need to apply to all the pages as follows:

**skeleton.nunjucks**

    <!DOCTYPE html>
    <html>
         <head>
               <title>skeleton</title>
         </head>
         <body>
                 {{ content }}
         </body>
    </html>

How to use the above skeleton structure in the below page:

**index.nunjucks**

      <div class="page">
             <div class="content">Hello</div>
      </div>

I got this requirement, while I was using https://github.com/carlosl/gulp-nunjucks-render

**Comment by ricordisamoa** [comment]
See https://mozilla.github.io/nunjucks/templating.html#template-inheritance, for example:

**skeleton.nunjucks**
```jinja
<!DOCTYPE html>
<html>
     <head>
           <title>skeleton</title>
     </head>
     <body>
             {% block content %}{% endblock %}
     </body>
</html>
```

**index.nunjucks**
```jinja
{% extends "skeleton.nunjucks" %}
{% block content %}
  <div class="page">
         <div class="content">Hello</div>
  </div>
{% endblock %}
```

**Comment by kamlekar** [comment]
Thank you very much. I saw this but somehow I was confused on how to pass parameters, which is not required.
