### ISSUE TITLE
render a string inside another string

### ISSUE THREAD

**Issue by kamlekar** [mozilla/nunjucks#547]
This is a question. I have a situation where I need to render a string inside another string. I am actually trying to include the svg content inside the html. Like this

    {% for svgContent in svgs %}
      <div style="display: none">
  	    {{ fs.readFileSync('site/assets/images/{{ svgContent }}.svg', 'utf8') }}
      </div>
    {% endfor %}

where `svgs` holds array of names of the svg files. This isn't working. Is there any other way?

**Comment by ricordisamoa** [comment]
```jinja
{% for svgContent in svgs %}
  <div style="display: none">
    {{ fs.readFileSync('site/assets/images/' ~ svgContent ~ '.svg', 'utf8') }}
  </div>
{% endfor %}
```
Of course you need to pass `fs: require( 'fs' )` to `render()`.

But you'd better use real JavaScript to read the files asynchronously and render the template when done.

**Comment by kamlekar** [comment]
@ricordisamoa I am still seeing errors and the file is not rendering. The error is as follows:

> Template render error: expected variable end.......

I am using [gulp-nunjucks-render](https://github.com/carlosl/gulp-nunjucks-render) to use nunjucks.

**Comment by ricordisamoa** [comment]
The string concatenation operator is new in Nunjucks 2.0, you could try replacing it with `+`.

**Comment by kamlekar** [comment]
Thanks for your help. I can still see error:

>Template render error: parseSignature: expected comma after expression
    at Object.exports.withPrettyErrors

**Comment by carljm** [comment]
Try setting a variable to the full path first, and then using that variable in the call, e.g.

```
{% set filepath = 'site/assets/images/' ~ svgContent ~ '.svg' %}
{{ fs.readFileSync(filepath, 'utf8') }}
```

If that works, then maybe we have a bug in the parser?

**Comment by kamlekar** [comment]
Here is some of the excerpt of error:

>events.js:141
      throw er; // Unhandled 'error' event
      ^
Template render error: (unknown path)
  Template render error: Template render error: Template render error: (/Applications/XAMPP/xamppfiles/htdocs/HTML-Skinning-Boilerplate/templates/sections/_head.html)
  Template render error: Template render error: (/Applications/XAMPP/xamppfiles/htdocs/HTML-Skinning-Boilerplate/templates/variables/_svg-sprite.html)
  Template render error: Error: ENOENT: no such file or directory, open 'site/assets/images/[.svg'
    at Object.exports.withPrettyErrors (/Applications/XAMPP/xamppfiles/htdocs/HTML-Skinning-Boilerplate/node_modules/gulp-nunjucks-render/node_modules/nunjucks/src/lib.js:35:17)
    at Obj.extend.render (/Applications/XAMPP/xamppfiles/htdocs/HTML-Skinning-Boilerplate/node_modules/gulp-nunjucks-render/node_modules/nunjucks/src/environment.js:374:20)
    at Obj.extend.renderString (/Applications/XAMPP/xamppfiles/htdocs/HTML-Skinning-Boilerplate/node_modules/gulp-nunjucks-render/node_modules/nunjucks/src/environment.js:261:21)

**Comment by carljm** [comment]
I think if you read that carefully (particularly the line containing the `ENOENT` error), it should be pretty clear what the problem is, and it isn't a problem with nunjucks, it's a problem with your data.

**Comment by kamlekar** [comment]
I realized it was my stupid mistake. I was actually `JSON.strigify`'ing the array variable to pass to nunjucks. Hence, the variable was not array but a string.
