### ISSUE TITLE
Using variable in a macro

### ISSUE THREAD

**Issue by Zubrik** [mozilla/nunjucks#549]
Hi,

I want to use a macro in a layout, that renders a link list. I then want to pass a variable to that macro in every template that extends that layout, in order to add a class of "active" to one of the list links.

To do this, I have a nunjucks file with this code, which extends a layout and sets the variable:

```
{% extends "layout.nunjucks" %}
{% set activePage = "actualitat" %}
```

I'd like to use the value of the variable activeMenu in my layout.nunjucks file, where there's this code, which doesn't work:

```
{% import 'macros/navigation.nunjucks' as nav %}
{{nav.active({{ activePage }})}}
```

The macro I'm importing is:

```
{% macro active(activePage='home') %}
  <ul class="menu">
    <li><a href="/" class="{%if activePage == 'home' %}active{% endif %}">Home</a</li>
    <li><a href="/actualitat/" class="{%if activePage == 'actualitat' %}active{% endif %}">Actualitat</a></li>
    <li><a href="/estils/" class="{%if activePage == 'estils' %}active{% endif %}">Estils</a></li>
    <li><a href="/contacte/" class="{%if activePage == 'contacte' %}active{% endif %}">Contacte</a></li>
</ul>
{% endmacro %}
```

How should I pass the value of the variable to the macro, so I have my link list with the class "active" added to the link I want?

Thanks.

**Comment by carljm** [comment]
Just remove the inner set of brackets; brackets are never nested. Once you're inside brackets already you can just refer to the variable by name. `{{ nav.active(activePage) }}`

**Comment by CSFlorin** [comment]
this doesn't always seem to work.

`{% macro get_view_name(name) %}
                                        "views/{{name}}.html"
                                        {% endmacro %}
                                        {% set view_name = get_view_name(view.name) %}
                                        {{view_name}} 
                                        {{includeFile(view_name)}}`
But the it errors on the last line saying Template render error: TypeError: path must be a string or Buffer.

However, just running 

` {{includeFile("views/file.html")}}`

works just fine. Any idea?

**Comment by devoidfury** [comment]
What's the `includeFile` function you're calling there?

Nunjucks is probably passing you a SafeString object instead of a regular string. If you call `.toString()` on it (or do an equivalent op like `'' + str`) it'll cast to a string and you can use it normally.

**Comment by CSFlorin** [comment]
Just added the includeFile function/macro at the top of my comment. I'm not exactly sure how to do that in the template; can you give an example?

**Comment by devoidfury** [comment]
```js
environment.addGlobal('includeFile', (src) => fs.readFileSync('' + src));
```
