### ISSUE TITLE
Nunjucks needs an icon/logo 

### ISSUE THREAD

**Issue by builtbylane** [mozilla/nunjucks#550]

**Comment by ricordisamoa** [comment]
A clipping from http://mozilla.github.io/nunjucks/?

**Comment by builtbylane** [comment]
![nj](https://cloud.githubusercontent.com/assets/149081/10471339/f1ffdff2-71e2-11e5-9c2e-a9c012ad888f.jpg)
?

**Comment by carljm** [comment]
I'm not sure what the next step is here. Personally I don't have any use for a nunjucks icon or logo, nor am I a designer, so I don't think I should be the one to decide on a logo. I don't love the "Nj" option above, but I don't really care either. I'm inclined to close this issue, but I'll happily reopen it if there seems to be a lot of community energy around defining a process to select a logo.

**Comment by xxd3vin** [comment]
@carljm Use case is: 

- I'm a beginner of Nunjuncks
- I open https://mozilla.github.io/nunjucks/templating.html page, and pin this tab in Chrome, for quick search in API docs.
- I saw this ![workspace1_001_107e](https://cloud.githubusercontent.com/assets/5204106/17538391/71ca3ce0-5e6a-11e6-9634-6a0da7898eae.jpg). From left to right is Jenkins, Teambition, Trello, ... , and the last one is Nunjuncks. The icon for this tab will help me quickly find it.

TODO:

I think we should modify this file: https://github.com/mozilla/nunjucks/blob/master/docs/_layouts/page.html

```diff
    <link rel="stylesheet" type="text/css" href="{{ site.baseurl }}css/app.css" />
+    <link rel="shortcut icon" href="{{ site.baseurl }}img/favicon.ico">
  </head>
```

The `img/favicon.ico` file could use  https://cloud.githubusercontent.com/assets/149081/10471375/3e6b4c78-71e3-11e5-90c9-77916b5b13de.jpg created by builtbylane

**Comment by carljm** [comment]
@xxd3vin I'd accept a PR to add something as favicon to the site. The Nj option above is fine.
