### ISSUE TITLE
Nunjucks appears to be stomping a previously set session variable in a race condition

### ISSUE THREAD

**Issue by pennyfx** [mozilla/nunjucks#552]
Hey James, 

This is a strange issue that showed up when I connected to a remote staging DB instead of a local dev DB.  I think the increased latency creates a race condition with Nunjucks and asap().

My app setup is express + knex + passport + nunjucks.

It took me a while to track this down, but it looks like the passport session object is being stomped shortly after it is set, with stale session data.

```
The following output is from the KnexStore set function. 
`KnexStore.set (/Users/arron/programming/sr-71/node_modules/connect-session-knex/index.js:157:8):`

# This console.log was right after a successful auth with passport.   
SET {"cookie":{"originalMaxAge":2399999,"expires":"2015-10-14T06:58:02.152Z","httpOnly":true,"path":"/"},"passport":{"user":{"id":1,"username":"fooobarr"}}}`

# The following KnexStore.set call is missing the passport obj.
SET {"cookie":{"originalMaxAge":2399999,"expires":"2015-10-14T06:58:02.337Z","httpOnly":true,"path":"/"}}

Notice the time difference between the two requests?  

```

When I fired off an exception, I discovered this stack trace, which points at nunjucks use of asap.  I'm not familiar with the internals of nunjucks, so I'm not sure what this is doing. 

```
at KnexStore.set (/Users/arron/programming/sr-71/node_modules/connect-session-knex/index.js:157:8)
    at Session.save (/Users/arron/programming/sr-71/node_modules/express-session/session/session.js:71:25)
    at Session.save (/Users/arron/programming/sr-71/node_modules/express-session/index.js:327:15)
    at ServerResponse.end (/Users/arron/programming/sr-71/node_modules/express-session/index.js:285:21)
    at ServerResponse.send (/Users/arron/programming/sr-71/node_modules/express/lib/response.js:204:10)
    at done (/Users/arron/programming/sr-71/node_modules/express/lib/response.js:957:10)
    at /Users/arron/programming/sr-71/node_modules/nunjucks/src/environment.js:22:23
    at RawTask.call (/Users/arron/programming/sr-71/node_modules/nunjucks/node_modules/asap/asap.js:40:19)
    at flush (/Users/arron/programming/sr-71/node_modules/nunjucks/node_modules/asap/raw.js:50:29)
    at doNTCallback0 (node.js:408:9)
    at process._tickCallback (node.js:337:13)
```

After discovering this, I removed Nunjucks and now the problem is gone.   

Any idea what could be causing this?

**Comment by devoidfury** [comment]
Are you doing anything async inside the nunjucks template? If so, can you provide an example template?

I've seen this session stomping issue happen using Chrome-based browsers (possibly because of a prefetch/odd request); just to verify that this is not the case, can you duplicate the issue in Firefox?

**Comment by pennyfx** [comment]
My templates aren't doing anything yet and are completely serverside.   I
always dev in firefox, but I verified it chrome for giggles.

**Comment by devoidfury** [comment]
nunjucks shouldn't be modifying on the request/session -- it seems like a race condition that's just visible with enough delay.

Can you provide a minimal example that duplicates the issue, or some of the user-code that seems to trigger this?

I might suggest, for debugging, replacing any nunjucks calls (e.g. `render`) with a timer, for example `setTimeout(function() { res.send() }, 40)` -- if you can duplicate it without `render`, `renderString`, or invoking nunjucks it may help to isolate the issue.

**Comment by pennyfx** [comment]
You are right, this is a session issue from express-session.   The stack trace led me to believe that nunjucks+asap were holding a stale copy of the session and then submitting it later.    

It was actually [this](https://github.com/expressjs/session#resave) default value in express-sessions.

thanks,
