### ISSUE TITLE
XMLHttpRequest cannot load file:///path/to/template.html

### ISSUE THREAD

**Issue by andysaini** [mozilla/nunjucks#554]
'Cross origin requests are only supported for protocol-schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource'

I'm trying to render a template from index page, with the following code, after importing jquery 1.11.0 and nunjucks 2.1.0:-

    nunjucks.configure('views');
    var res = nunjucks.render('template.html');

Works **fine** with firefox developer edition, but not with chrome 42.0/chromium latest. I'm using nunjucks in the browser only, and the template.html resides in views directory.

**Comment by carljm** [comment]
Can you check the browser console and see what URL each browser is requesting to get the template?

I think you may want to use an absolute url path (see the note in the doc example at http://mozilla.github.io/nunjucks/api.html#configure).

**Comment by jlongster** [comment]
It's probably trying to AJAX in the template but you are on a file:// protocol, which some browser like Chrome don't allow. You either need to precompile the templates or run a local static server (a simple `python -m SimpleHTTPServer` works)

**Comment by andysaini** [comment]
@jlongster makes sense, I'll try it!

**Comment by andysaini** [comment]
Yupp, it's the file protocol that doesn't work with chrome due to security reasons!
