### ISSUE TITLE
We should start a slack group

### ISSUE THREAD

**Issue by jitendravyas** [mozilla/nunjucks#555]

**Comment by ArmorDarks** [comment]
I think https://gitter.im/ will fit better in that case

**Comment by jitendravyas** [comment]
Yes that is also good

**Comment by carljm** [comment]
I'm not personally interested in monitoring another channel besides GitHub and the mailing list (https://groups.google.com/forum/#!forum/nunjucks), but obviously anyone can start and advertise whatever they like. The right place to discuss this is the mailing list, not the issues list.
