### ISSUE TITLE
How to build list of variables found in a template

### ISSUE THREAD

**Issue by ohmance** [mozilla/nunjucks#557]
First off, awesome library, folks.

I have a situation where I use nunjucks to generate a template thousands of times that can contain anywhere between 1 to 50 variables in it.  These templates can sometimes be 10-20k of html (sizable yes, a lot can be just repeated style attributes, etc when pasted from Word or elsewhere... a fairly user friendly and common way to do this).  I need to archive all of these generated templates to be able to be looked up later.  Context data is subject to change from time to time.  Currently the most effective way of doing this is to store each rendered template, compressed of course, but still 20k * 5000 can add up significantly.

My first attempt at addressing this issue was to write a simple regex that would look for every occurrence of {{.*}} and extract the name of the key.  This works well for static variables, but I find that some of my users are doing some of these things:
```
{{currentTime()}}
{{first_name | capitalize}}
{{age + 3}}
```

There is no easy way to use a regex to calculate these values.  It's occurred to me that I could just create templates for each regex value and then interpolate those templates with nunjucks, but there are times I need to generate 80-100k templates for my customers in a matter of minutes and doing this slows things down.

Is there some sort of method or filter I can create that is run each time a property of the context is referenced that would allow me to store a list of all the keys or variables referenced?
For example, from the above I would get output like this:
```
{{currentTime()}} => this would not yield anything but since I have access to the currentTime() function I can handle this manually
{{first_name | capitalize}} => first_name
{{age + 3}} => age
```

Even better than that, what would really be cool is if it were possible to get the content of each variable as well as the rendered value like this:
```javascript
{
  "currentTime()": "2015-10-21:00:00:00Z",
  "first_name | capitalize": "BEN",
  "age + 3": "32"
}
```

**Comment by carljm** [comment]
This may be possible, but it will probably require running a modified version of nunjucks, and you'll have to get dirty in the code. I don't think a GitHub issue is the right place to discuss this, as there's no issue with nunjucks here.

**Comment by jlongster** [comment]
You can look in `lexer.js` and `parser.js` and you may be able to build your own parser to generate a different format that you can leverage.
