### ISSUE TITLE
Inconsistent scoping behavior in "macro", "include" and template inheritance.

### ISSUE THREAD

**Issue by legutierr** [mozilla/nunjucks#561]
This template...

    {% macro setval() %}{% set val = 22 %}{% endmacro %}{{ setval() }}{{ val }}

...evaluates to "" (i.e., the empty string).  The value set inside the macro doesn't leak out of the the local macro scope.  However, this template...

    {% macro setval() %}{% set val = 22 %}{% endmacro %}{% set val = 44 %}{{ setval() }}{{ val }}

...evaluates to "22". The value set inside the macro leaks out of the macro scope.  In Jinja, these two templates evaluate to "" and "44", respectively.

**Comment by legutierr** [comment]
There's a similar weirdness happening with the include tag as well.  Given this simple template...

    {# template.html #}
    {% set var = 22 %}

...you get two very different results when you include it.  First...

    {% include "template.html" %}{{ var }}

...evaluates to "" (the empty string).  The value of var does not leak out of the included template's scope.  This template, however, does leak its scope...

    {% set var = 44 %}{% include "template.html" %}{{ var }}

...evaluating to "22".  In Jinja, these two templates evaluate to "" and "44", respectively, as before.

**Comment by carljm** [comment]
Thanks for tracking this down! This is definitely something that should ideally be fixed, though without diving into the details I have no idea how invasive the fix will be. It's something I'd enjoy looking into if I find some time, but not sure when that will be - pull requests definitely welcome! (Even just a PR with failing tests for these issues would be a really good start.)

**Comment by legutierr** [comment]
I discovered more of the same weirdness with template inheritance.  Given this base template...

    {# base.html #}
    {% block k %}{% set var = 'parent' %}{% endblock %}

...when you execute the following template...

    {% extends “base.html” %}{% block k %}{% set var = 'child' %}{{ super() }}{{ var }}{% endblock %}

...you get the expected result: ‘child’.  This is the same value that Jinja emits.  However, when you execute the following template...

    {% extends “base.html” %}{% block k %}{{ super() }}{{ var }}{% endblock %}

...you get ‘parent’.  Again, the problem is a leaking scope (in this case, that of “super()”), but only when the value is set.  With Jinja, in this second case, you get ‘’ (i.e. the empty string).

And there is also a fourth inconsistency.  Given this base template...

    {# base2.html #}
    {% set val = 'parent' %}{% block k %}{% set val = ‘inner’ %}{% endblock %}{{ val }}

...when you execute the following template...

    {% extends “base2.html” %}{% block k %}{% set val = 'child' %}{% endblock %}

...you get ‘child’.  The child block is leaking into the parent template.  However, when you render the “base2.html” file directly, the block scope does not leak, and the template renders ‘parent’, as expected.  In Jinja, both templates render to the string ‘parent’.

I hope that I will be able to help with this.  If I have time, I will definitely work on it, but I'm not sure if I will.

**Comment by carljm** [comment]
The macro portion of this should be fixed with the merge of #653 -- the `isolate` frame attribute added there might also help with fixing the rest of this, just needs someone to try it out and write a test.

**Comment by carljm** [comment]
Merge of #667 improves the macro component of the fix from #653, and also fixes the include portion.

**Comment by carljm** [comment]
Ok, I think that concludes the last of this bug, finally! Thanks again @legutierr for digging up these issues; please feel free to dig some more and see what you find :-)
