### ISSUE TITLE
Allow compiled templates to be imported, included, and extended.

### ISSUE THREAD

**Issue by legutierr** [mozilla/nunjucks#562]
Currently, Nunjucks only permits expressions that evaluate to strings to be passed into the import, include and extends tags.  Jinja and Twig both permit compiled templates to be passed into the import, include and extends tags, in addition to strings.  This is useful, for instance, in situations where templates are generated programmatically and are inserted into the context at runtime.  For instance:

    >> var template = nunjucks.compile("Hello {{ name }}!");
    >> nunjucks.compile('{% set name = "Mark" %}{% include tmpl %}').render({'tmpl':template});
    "Hello Mark!"

Including this feature will make Nunjuck's implementation more consistent with Jinja's.

**Comment by carljm** [comment]
Closed with merge of #581.
