### ISSUE TITLE
Cannot get custom loader to work

### ISSUE THREAD

**Issue by tcurdt** [mozilla/nunjucks#563]
Based on the docs I tried both

    // TypeError: loader.getSource is not a function
    var loader = Nunjucks.Loader.extend({
      async: true,
      getSource: function(name, cb) {
        console.log('loading', name);
        var src = 'LOADED';
        cb(err, src);
      }
    });

and

    // TypeError: Cannot assign to read only property 'loader' of LOADED
    var loader = {
      async: true,
      getSource: function(name, cb) {
        console.log('loading', name);
        var src = "LOADED";
        cb(null, src);
      }
    };

then

    var env = new Nunjucks.Environment(loader, {
      autoescape: true,
      noCache: true,
      trimBlocks: true,
      throwOnUndefined: true
    });

    var res = Nunjucks.compile("...", env);

but both both variants just throw an error (see above as comment).

What am I missing?

**Comment by carljm** [comment]
You're missing this part of the custom loader docs:

```
    // return an object with:
    //   - src:     String. The template source.
    //   - path:    String. Path to template.
    //   - noCache: Bool. Don't cache the template (optional).
```

Your loader code is simply returning (or calling the async callback with) a string, the source of the loaded template. You're supposed to return (or call the async callback with) an object, of which `src` is just one property.

**Comment by tcurdt** [comment]
Doh! Thanks!
