### ISSUE TITLE
Where to locate custom filters ?

### ISSUE THREAD

**Issue by MartialSeron** [mozilla/nunjucks#565]
Hi,

I just started a project with sails.js and nunjucks.
It works well but I don't know where to locate the custom filters file.

I tried to create a service but I think consolidate just ignores it.

Thanks

**Comment by carljm** [comment]
You can put custom filters in any file you want, nunjucks doesn't care about your file organization at all. You just need to create a nunjucks env object somewhere, call `env.addFilter(...)` with each of your filters, and then render templates using that env's `env.render(...)`. It sounds like whatever problems you are having here are unrelated to nunjucks - probably related to consolidate or sails.js, neither of which I know anything about.
