### ISSUE TITLE
Outdated warning when using default filter

### ISSUE THREAD

**Issue by kaylynb** [mozilla/nunjucks#566]
When using a default filter without specifying boolean, nunjucks displays an outdated deprecation warning.

Ex:
```
{{ x | default('y') }}
```

produces the following warning:
```
[nunjucks] Warning: the "default" filter was used without specifying the type of comparison. 2.0 changed the default behavior from boolean (val ? val : def) to strictly undefined, so you should make sure that doesn't break anything. Be explicit about this to make this warning go away, or wait until 2.1. See http://mozilla.github.io/nunjucks/templating.html#defaultvalue-default-boolean
```

The warning says 'or wait until 2.1.', and the documentation says it will be removed in the next version.

Appears to still be in master as of today: https://github.com/mozilla/nunjucks/blob/90e39138f63dd01e2be49b3cc89e5ff309401c6a/src/filters.js#L70-L77

Does this need a PR to update documentation and/or remove the warning?

**Comment by carljm** [comment]
Closed with merge of #567.
