### ISSUE TITLE
Output incomplete html

### ISSUE THREAD

**Issue by elantion** [mozilla/nunjucks#568]
It's weird. I render a value include 'svg' tag. It will only output part of it. The html is incomplete.
Look at this incomplete html:
![29x 3l ln4s v0bc0qys_q](https://cloud.githubusercontent.com/assets/1912695/10782565/50e56884-7d8c-11e5-8775-ac994befe11c.jpg)
The html is break here:
![69 ej01eva _84temr2er t](https://cloud.githubusercontent.com/assets/1912695/10782573/5c02e3b8-7d8c-11e5-86f6-12832d24a425.png)

This is the source page: http://www.w3cplus.com/svg/creating-cel-animations-with-svg.html
This is my page: http://www.mentry.cn/page/creating-cel-animations-with-svg
I already check the database and the value both fine.
More strange, It's totally OK in Windows.  It only have problem in CentOS.
If I describe not clear please let me know. Thanks for your reading.

**Comment by elantion** [comment]
The code is very simple:
```
        <article>
            {{ content|safe }}
        </article>
```
no matter I use 'safe' filter or not , it still have the problem.

**Comment by carljm** [comment]
Given the OS variability, I highly doubt this is a nunjucks issue. More likely the data is getting truncated at some other point in your code. If you believe it is a nunjucks issue, please provide a minimalist self-contained reproduction case, all in code (i.e. no dependency on a database, and no unrelated cruft in the code).

**Comment by elantion** [comment]
For finding the reason of this problem, I have tried three type of ways to serve the page:
1. Nunjucks: Rendered the raw html without any processing. It still can not output completely.
2. Nginx: Used nginx to serve the html directly and it is fine.
3. Node.js: Used expressjs static middleware to serve the html, It's not complete.
So I guess this is a nodejs problem , not a nunjucks problem. But have you seen this kind of problem before? If you can tell me any clue will save my life. 
Good day.

**Comment by elantion** [comment]
I try to use node.js serve the page directly without expressjs and it's fine. So I can locate the problem is expressjs.
```
var http = require('http'),
    fs = require('fs');


fs.readFile('./public/html/nunjucks.html', function (err, html) {
    if (err) {
        throw err;
    }
    http.createServer(function(request, response) {
        response.writeHeader(200, {"Content-Type": "text/html"});
        response.write(html);
        response.end();
    }).listen(3201);
});
```

**Comment by devoidfury** [comment]
Is the file encoded as utf-8? Express and nunjucks both open using that encoding.

**Comment by devoidfury** [comment]
Maybe there should be an option for setting the encoding for the node loader? A ucs2 option could be useful.

**Comment by elantion** [comment]
All my files are UTF-8.

**Comment by elantion** [comment]
What is node loader? How can I set that option.
Thanks for your reply.
