### ISSUE TITLE
[Macros] TypeError: Cannot read property '__keywords' of undefined

### ISSUE THREAD

**Issue by devoidfury** [mozilla/nunjucks#57]
I found the issue I was having before. Test case:

    s = render('{% macro foo(x, y) %}{{ x.x }}{{ y.x }}{% endmacro %}' +
        '{{ foo(bar, baz) }}');
    s.should.equal('');

The error is `TypeError: Cannot read property '__keywords' of undefined`

Macros should have the same behavior with undefined names as regular templates.

(Edit: I don't have this issue in v0.1.7)

**Comment by jlongster** [comment]
Haven't heard this reported in forever, so closing until we find a test case
