### ISSUE TITLE
Block set

### ISSUE THREAD

**Issue by ElChupacabra26** [mozilla/nunjucks#582]
Obviously this would be an enhancement, but a block setter like they have in [Jinja](https://github.com/mitsuhiko/jinja2/issues/232) would be super useful. For instance, we could do things like this:

```jinja
{# Set modal content #}
{% set modalContent %}
    {% include 'partials/sku-page/bundle.nunj' %}
{% endset %}

{# Cache HTML for 'More Choices' modal in hidden field #}
<input type="hidden" class="modalContent" value="{{modalContent | e}}">
```

**Comment by carljm** [comment]
Yes, I think nunjucks should maintain Jinja compatibility here. PR gladly accepted :-)

**Comment by carljm** [comment]
Closed with merge of #656 -- thanks @daniele-rapagnani !

**Comment by ElChupacabra26** [comment]
:+1: to that!

**Comment by jtlapp** [comment]
My apologies, but I need this feature to use nunjucks at all, but it's not in the latest NPM release, and I don't see how to build the source. Is this in the docs somewhere? Thank you! (I have child templates that create variables from variables for use in multiple places in both the parent and child templates.)

**Comment by carljm** [comment]
Yes, instructions for building are in the MAINTENANCE doc (really its as simple as `npm run browserfiles`). I'm hoping to get a new release out soon.

**Comment by jtlapp** [comment]
Okay thank you. I guess I was thrown by the term "browserfiles" and the language "ready-made files for the browser." But of course if it works in the browser, it'll work on the server. In any case, I found the necessary soup of curly brackets confounding the readability of the variable assignments and am now opting for front matter JSON and two-pass variable assignment. Thanks for your help.
