### ISSUE TITLE
Support vdom output (react or others).

### ISSUE THREAD

**Issue by DylanPiercey** [mozilla/nunjucks#584]
Instead of compiling into a string it would be awesome if nunjucks could also compile into a react compatible vdom or even just JSX (which would be compiled again).

Currently the only other templating language for react is Jade, it would be nice to see some competition.

Thoughts?

**Comment by devoidfury** [comment]
Well, as it stands nunjucks isn't really "for" HTML, it's for any kind of macro templating, and it has no knowledge of the HTML or it's semantics. I even use it for generating javascript and plaintext sometimes.

That's pretty far outside the scope of the project, IMO.

**Comment by DylanPiercey** [comment]
Yeah, makes sense. This is probably something for an external lib.

**Comment by carljm** [comment]
Agreed.
