### ISSUE TITLE
Loop probleme with integer keys in array

### ISSUE THREAD

**Issue by fkroockmann** [mozilla/nunjucks#591]
Hello,

I try to do this:

```
{% for key, value in ['foo', 'bar'] %}
   {{ key }} - {{ value }}
{% endfor %}
```

That show : "f - o b - a" instead of "0 - foo 1 - bar"

Do you have  a suggestion ?

Thanks a lot

**Comment by carljm** [comment]
Arrays in nunjucks aren't like JS arrays with integer keys you can loop over like that. They are just lists of values. You just do `for val in list`. If you need the index use the magic `loop.index` var.

**Comment by fkroockmann** [comment]
Thanks for answer
