### ISSUE TITLE
nunjucks inline templates ?

### ISSUE THREAD

**Issue by daslicht** [mozilla/nunjucks#592]
Hi,
is there a way to use inline templates which are placed in a script text/template tag ?
Or how should that be approached in the browser?

**Comment by carljm** [comment]
Nunjucks allows you to handle this however you want, via the `loader` abstraction. The built-in WebLoader will load templates via Ajax from a base URL. In production, though, you should always precompile templates into a JS file that you include in your page normally; nunjucks will automatically use precompiled templates if available. (You can also precompile in both dev and production by using a task-runner like gulp or grunt to automate watching for template changes and compiling on the fly.)

See http://mozilla.github.io/nunjucks/api.html#browser-usage for more details.

**Comment by daslicht** [comment]
Interesting!
How would *pjax* compare to client side rendering while using precompile templates ?
By *pjax* I mean that the server just renders the content to display instead of the whole page including layout. Once the client received the new content it just exchange it using js.

I bet anyone dis such teste before, no? ?

**Comment by carljm** [comment]
PJAX and nunjucks rendering using precompiled templates aren't really comparable. The latter allows you to re-render templates on the client side anytime your source data changes (which sometimes you may know about without needing an AJAX request at all). PJAX always requires a server round-trip to update anything.

**Comment by daslicht** [comment]
i see, I was more thinking of traditional webpages not web applications like a BLOB

**Comment by daslicht** [comment]
is there a inline temple example anyways please?
I just want to use a small amount , eg to display an input form or add an element to an existing list

**Comment by carljm** [comment]
No we don't have any such example in the docs, because it's not a recommended use.  You should be able to figure it out though using the documented renderString API.

**Comment by daslicht** [comment]
I am stuck at : 
https://github.com/thlorenz/browserify-shim/issues/207
https://github.com/rotundasoftware/nunjucksify/issues/16

What do I miss please?

**Comment by tomoya92** [comment]
Why this example( https://github.com/gillesfabio/express-pjaxify ) can be used? But I will nunjucks, pjax version of the upgrade will not work
