### ISSUE TITLE
Incorrect Readable Error-Message when calling Function >10 Chars

### ISSUE THREAD

**Issue by MaZderMind** [mozilla/nunjucks#594]
The following Code in the Template:
````
{% set thumbnail_url = env.helper.getImageUrl('foo', first_image.url, 'large' ) %}
````

compiles to sth. like
```` javascript
var t_18;

t_18 = 
(lineno = 11, colno = 45, 
runtime.callWrap(
runtime.memberLookup((
runtime.memberLookup((
runtime.contextOrFrameLookup(context, frame, "env")
),
"helper"
)
),
"getImageUrl"
)
, "env[\"helper\"][\"getImageUr\"]", context, 
[
"foo"
,
runtime.memberLookup((
runtime.contextOrFrameLookup(context, frame, "first_image")
),
"url"
)
,
"large"
])
)
````

If the Call for whatever reasons fail, the printed reable error message will be something like:
````
  Template render error: (/home/peter/AAA-Misc/marcellammon/templates/galleries-index.html) [Line 11, Column 45]
  Error: Unable to call `env["helper"]["getImageUr"]`, which is undefined or falsey
````

which obviously points users into the wrong direction. The Reason is that [`compileFunCall`](https://github.com/mozilla/nunjucks/blob/6a628ae5d1a9d901f4ecd41d13848e4cb293790f/src/compiler.js#L464) uses [`_getNodeName`](https://github.com/mozilla/nunjucks/blob/6a628ae5d1a9d901f4ecd41d13848e4cb293790f/src/compiler.js#L434) to generate the function's name, which [shortens Literals to 10 Chars](https://github.com/mozilla/nunjucks/blob/6a628ae5d1a9d901f4ecd41d13848e4cb293790f/src/compiler.js#L444) without any hint.

**Comment by yash14123** [comment]
I am on it. Please assign me .

**Comment by carljm** [comment]
Consider yourself assigned! :)

**Comment by yash14123** [comment]
Change the documentation mentioning this point right?

**Comment by carljm** [comment]
If there's documentation that needs to be updated to match the changes you're making, then yes, please do update it.

**Comment by ricordisamoa** [comment]
#703

**Comment by carljm** [comment]
I knew this existed, and looked for it awhile yesterday but couldn't find it. Thanks @ricordisamoa! If it's ok with you, I'm adding you as a project collaborator so you can take care of things like this yourself (please submit code changes as PRs and get them reviewed, don't just commit directly).

**Comment by ricordisamoa** [comment]
Wow, thank you @carljm! If you really found help in the little I've done, why would I stop helping... I will restrict myself to issues of course.
