### ISSUE TITLE
Dash tags -%} remove space between tags in an unexpected way

### ISSUE THREAD

**Issue by tdelmas** [mozilla/nunjucks#595]
``` 
{% macro dash(a) -%} {{ a }} {{ a }} {%- endmacro %}
/{{ dash("_") }}/
``` 
Produce /_ _/ as expected (no spaces outside, one inside)
But : 
``` 
{% macro dash(a) -%}{{ a }} {{ a }}{%- endmacro %}
/{{ dash("_") }}/
``` 
Produce /__/ (no space outside, an no inside)

It that the expected behaviour ? "If the tag with tash is not followed by a space, then stip spaces after the next one"

**Comment by curiousdannii** [comment]
I think your code might be being mangled by the markdown parser. Can you put it all in ``` block code tags?

**Comment by tdelmas** [comment]
I've updated if.
You can see the same behavior here : http://www.raymondcamden.com/demos/2014/oct/15/test.html
```
{% macro word(w) %}{{ w }}{% endmacro %}

{% if 1 -%} {{ word('EVERYTHING')}} {{word('FINE')}}{% endif %}
{% if 1 -%}{{ word('SOMETHING')}} {{word('WRONG')}}{% endif %}
```
Do not forget to put {} in the JSON part of the webpage.
```
EVERYTHING FINE SOMETHINGWRONG
```
To clarify the result : there was a space between "SOMETHING" and "WRONG" but the dash (-) removed it.
