### ISSUE TITLE
urlize filter dissolves meaningful whitespace

### ISSUE THREAD

**Issue by curiousdannii** [mozilla/nunjucks#596]
The urlize filter splits by whitespace and then joins with " ", which means any line breaks, tabs etc will be lost.

I can't see why it couldn't instead do something like this, where the replace function is the one currently being passed to map():

```
words = str.replace( /\S+/g, function() )
```

**Comment by carljm** [comment]
The goal for the built-in filters is Jinja2 compatibility, and the Jinja2 `urlize` filter does not collapse whitespace, so this is indeed a bug. Thanks for the report!

**Comment by pbu88** [comment]
I think this issue can be closed now :)

**Comment by carljm** [comment]
Yep, thanks for pointing it out.
