### ISSUE TITLE
Build without chokidar

### ISSUE THREAD

**Issue by thetutlage** [mozilla/nunjucks#600]
I believe `chokidar` is in use for watching purposes only, and i don't think it is required by everyone. While building a project i will have a file watcher which looks for all source files and then restart the server on change. 

This minimizes the need of having views only watcher, and chokidar will install it's own dependencies where everything is useless for me

**Comment by atian25** [comment]
+1 for this.
there is a lib : https://github.com/node-modules/nunjucks
but it's old

**Comment by jgerigmeyer** [comment]
@at0g Any progress on a PR for this?

**Comment by atian25** [comment]
which one?

**Comment by jgerigmeyer** [comment]
In https://github.com/mozilla/nunjucks/issues/507, @at0g had mentioned submitting a PR for a build without chokidar.

**Comment by at0g** [comment]
Hello, sorry I completely forgot about this - work has been hectic.
I will give it a crack this weekend.

**Comment by carljm** [comment]
see #610 for a more drastic option.

**Comment by thetutlage** [comment]
Are we getting any build for this ?

**Comment by carljm** [comment]
@thetutlage There's a pull request (#607) with an unaddressed comment. If you'd like to file an updated PR that addresses that comment, that'd be great!

**Comment by thetutlage** [comment]
@carljm I read the entire thread and didn't found something not being addressed. It will be great if you can share some context of what is holding you back from merging the PR. I will be more than happy to make all the required changes

**Comment by carljm** [comment]
@thetutlage the latest version of the PR failed linting, and I also agree with @ricordisamoa that it should be an error, not a warning. Both small changes, but the PR author closed the PR, so I guess a new one would need to be opened, with those minor changes.

**Comment by thetutlage** [comment]
Great, I will go ahead and create a PR with same changes and making sure the linter is happy

**Comment by atian25** [comment]
@thetutlage any good news?

**Comment by MH15** [comment]
Any updates on this? Chokidar really shouldn't be included in this package.

**Comment by fdintino** [comment]
@MH15 yes, chokidar is no longer a dependency. See the last few messages above in this thread for the PR that resolved this issue.
