### ISSUE TITLE
Provide true UMD support for nunjucks-slim

### ISSUE THREAD

**Issue by at0g** [mozilla/nunjucks#608]
It would be preferable if there was a true UMD build of nunjucks that can render templates in both the browser, AMD, or server environments from a single file.

My use case is that as [an author of a package that depends on nunjucks](https://www.npmjs.com/package/nunjucks-loader), I cannot bundle my library with UMD support as different versions of nunjucks must be used for both the browser and server. 

Given that the UMD wrapper is a packaging step, it would be acceptable to only have precompiled / slim support.

Any features that are not supported in both environments would be dropped (lowest common denominator) - for example, relative template paths are not supported in the browser, so would not be supported in a UMD build.

**Comment by carljm** [comment]
Closing in favor of #609 to keep the conversation in one place -- we don't need both the issue and the PR.
