### ISSUE TITLE
Two levels of super() do not work

### ISSUE THREAD

**Issue by boutell** [mozilla/nunjucks#61]
Please see this test project, I minimized it as much as possible:

https://github.com/punkave/nunjucks-debug

If you declare a block in layout1.html, extend that from layout2.html (calling super() in the extension of the block), and then extend layout2.html in test.html (calling super() again in your second extension of the block), you get:

Error: no super block available for "footer"

If layout2.html does not call super(), then test.html is able to successfully call super(), but of course the content output by layout1.html is lost.

The bug seems specific to more than one use of super() for the same block in the inheritance tree.

Thanks!

**Comment by keith24** [comment]
Sorry for bumping, but I am having OP's exact problem with ^2.4.2.  

```Error: no super block available for "footer"```

I can nest blocks properly, but the test in #77 doesn't account for `super()`.

**Comment by keith24** [comment]
Whoops!  Disregard that.  I was trying to put a `{% block %}` in a template that was called with `{% include %}`.
