### ISSUE TITLE
Deprecate/remove `watch: true` and the chokidar dependency.

### ISSUE THREAD

**Issue by carljm** [mozilla/nunjucks#610]
The chokidar dependency has been problematic for people, enough so that there was even a `nunjucks-no-chokidar` fork at one point.

Personally I think filesystem watching is way out of scope for a templating engine, and I would like to remove `watch: true` and the chokidar dependency entirely, leaving filesystem watching to tools designed for that (e.g. gulp/grunt).

Thoughts or objections? Is anyone using `watch: true` actively who would have a hard time replacing it with something like gulp? If so, why?

**Comment by atian25** [comment]
+1

**Comment by ricordisamoa** [comment]
:+1:

**Comment by jgerigmeyer** [comment]
:+1:

**Comment by forresst** [comment]
:+1:

**Comment by AaronO** [comment]
@carljm Totally agree with you on this. FS watching shouldn't be the `nunjucks`' responsibility. :+1:

**Comment by rhengles** [comment]
:+1:

**Comment by Saturate** [comment]
This would be a welcome change, I don't see much reason for nunjucks to have this responsibility.

**Comment by ogonkov** [comment]
Is there PR for completely remove watching?
