### ISSUE TITLE
Pass optional parameters and/or headers to the web loader calls

### ISSUE THREAD

**Issue by ingro** [mozilla/nunjucks#616]
Hello! I'm using nunjucks with the web loader but I have a problem. In our app, templates are per-user, and so I need some authentication when returning them by the api. I need to pass the auth token either in a header or a query parameter in the request, but the web loader don't have options for that.

Do you think it will be possible to add this option in a future release or should I look for an alternative? Thanks.

**Comment by carljm** [comment]
I think this is the type of unusual requirement for which it's reasonable to write your own custom loader, perhaps extending WebLoader. The loader API isn't very complex; between the [docs](http://mozilla.github.io/nunjucks/api.html#writing-a-loader) and looking at the WebLoader source code, it should be pretty straightforward.

**Comment by ingro** [comment]
Thanks for the suggestion, didn't think about that, will check it out on the docs!
