### ISSUE TITLE
filter.escape should not escape SafeString

### ISSUE THREAD

**Issue by atian25** [mozilla/nunjucks#618]
https://github.com/mozilla/nunjucks/blob/master/src%2Ffilters.js#L118

```
    escape: function(str) {
        if(typeof str === 'string' ||
           str instanceof r.SafeString) {
            return lib.escape(str);
        }
        return str;
    },
```

**Comment by atian25** [comment]
cc @carljm

**Comment by atian25** [comment]
I'm writing a custom tag lib, and it will not make nunjucks as dependencies but devDependencies.

got some problem when I need to detect some attr is safe string.

such as `{% test attr="<div"|safe %}`

SafeString is only export to `nunjucks.runtime.SafeString`, not ref at env.
now, I use `Object.getPrototypeOf(context.env.filters.safe('') === Object.getPrototypeOf(attr)` ,  got some bad smell.

**Comment by carljm** [comment]
I think this is a bug. In Jinja2, `{{ "foo & bar"|safe|escape }}` does not escape the ampersand.

**Comment by atian25** [comment]
@carljm PR: #623
