### ISSUE TITLE
Dynamic includes aren't working

### ISSUE THREAD

**Issue by mirisuzanne** [mozilla/nunjucks#635]
This works:

```
{% include 'quickstart/_power_on.js.html.j2' %}
``` 

And this fails every time:

```
 {% set template = 'quickstart/_power_on.js.html.j2' %}
 {% include template %} 
```

As far as I can tell, those should be identical.

**Comment by carljm** [comment]
Hmm, I can't reproduce this. Just added a test to master demonstrating that it generally works. Closing worksforme; will reopen if we can dig into what exactly is causing failure in your case. What was the symptom of the failure?
