### ISSUE TITLE
How to update object property with set

### ISSUE THREAD

**Issue by welefen** [mozilla/nunjucks#636]
How to update object property in nunjucks.

When use `set`, it throw errors:

```html
{% set obj.foo = 'xxx' %}
```

**Comment by carljm** [comment]
There is no way to do this in nunjucks (that I know of) without a custom extension tag. I recommend re-thinking your implementation to put less logic in the template and avoid the need for this.

**Comment by gijswijs** [comment]
I am a bit late to this party, but there *is* a way to do this.

```
{% set obj= { foo: 'xxx' } %}
<span>
  {{ obj.foo }}
</span>
```
