### ISSUE TITLE
Error expected variable end

### ISSUE THREAD

**Issue by Paxa** [mozilla/nunjucks#650]
I'm trying to call some function inside `{{ }}` and it gives error.

I was trying to print current year:
```
{{ new Date().getFullYear() }}
```

How to do it right?

**Comment by carljm** [comment]
You can call functions, but you can't run arbitrary JS code (so no `new`), and you can't access arbitrary JS globals, only values you explicitly pass into the template context (so no `Date` unless you pass it in yourself). You can pass `new Date()` explicitly into the template context when rendering; if you give it the name `now` (just as an example) you could then do `{{ now.fullYear() }}` in the template.

**Comment by ganlanyuan** [comment]
I use Gulp with Nunjucks. My solution is appending the `year` value to the data passing to the context.
```javascript
var data = require('./templates/data.json');
data.year = new Date().getFullYear();

gulp.task('nunjucks', () =>
  gulp.src('templates/*.njk')
    .pipe(nunjucks.compile(data), options)
    .pipe(rename(function (path) {
      path.extname = ".html";
    }))
    .pipe(gulp.dest(''))
);
```
Then in the `layout.njk` file I can directly use the year value
```markup
<div class="copyright">&copy; {{ year }}</div>
```
