### ISSUE TITLE
Nunjucks + Harp

### ISSUE THREAD

**Issue by howardroark** [mozilla/nunjucks#651]
This is spam, but I can't help myself :P There is an effort to implement Nunjucks into the asset pipeline that powers the fantastic tool [Harp](http://harpjs.com). I thought some watchers of this repo may be interested to have a look and maybe offer some input...  https://github.com/sintaxi/terraform/pull/126

I think they will make a fantastic combination :)

**Comment by carljm** [comment]
Thanks for the heads-up! There's also a nunjucks Google Group mailing list that would be a reasonable place for this kind of information/discussion.

Closing this issue if there's no specific action item for nunjucks here.

**Comment by howardroark** [comment]
Ah good call!  I always forget about it because the UI makes my head hurt a little bit :p 

I will do the honour and close this baby up.
