### ISSUE TITLE
How to use JavaScript code inside templates?

### ISSUE THREAD

**Issue by kamlekar** [mozilla/nunjucks#655]
I was wondering whether there is a way to manipulate the template using JavaScript functions or statements inside nunjucks templating.

Suppose, for example, I have a nunjucks file where I need to apply different classes based on resolution and I have already have a function `isMobile()` which I am using in many places in JS files. So, I thought to use the same function inside the template file. something as shown below:

index.nunjucks

    <body>
        <div class="{% if(isMobile()) { %}mobile-class {% else{ %} desktop-class {% } %}">
            
        </div>
    </body>

Please help.

**Comment by ricordisamoa** [comment]
index.nunjucks
```jinja
<body>
    <div class="{% if isMobile() %}mobile-class{% else %}desktop-class{% endif %}">
        <!-- content here -->
    </div>
</body>
```

Then pass the function object to your environment's `render()` method:
```javascript
env.render( 'index.nunjucks', { isMobile: isMobile } );
```

**Comment by kamlekar** [comment]
Thanks. This looks like an hack to me. Why can't I use JavaScript code in a straight way?

compiling is happening at runtime then definitely I must be able to use JavaScript straightforward right?

It is just a doubt I have. :)

**Comment by ricordisamoa** [comment]
> Why can't I use JavaScript code in a straight way?

https://github.com/mozilla/nunjucks/issues/419#issuecomment-97087967
> Nunjucks is not JS, even if it looks like a subset sometimes.

https://github.com/mozilla/nunjucks/issues/650#issuecomment-175668301
> You can call functions, but you can't run arbitrary JS code

**Comment by kamlekar** [comment]
hmm seems like a drawback for this template engine. Thanks.

**Comment by ricordisamoa** [comment]
Usually most of the logic is embedded in code, not templates. Compared with many other template engines, Nunjucks is quite powerful.

**Comment by sebringj** [comment]
I do completely see the elegance of not having code logic inside your templates and for the majority of cases this is great. However, it would be nice if there was a specific tag or escape syntax that would allow you to evaluate code for the particular implementation's backing language, in this case JavaScript where nunjucks gets out of the way and just says, OK do your thing, then come back.

For example, something simple like  {{ eval( 'new Date()).getFullYear()') }} so it was intentionally inconvenient to write inline yet for small things, it made sense. The environment has the ability to evaluate that string of code and requires escaping which is slightly annoying but at the same time discourages large swaths of inline code.

**Comment by hughesthatgirl** [comment]
I want to create a ternary operator, like in Twig, where you can say `if the variable exists, output it. Otherwise, output something else.`

Here is the Twig syntax of what I'm trying to accomplish in the code example below:
` bg_color ? bg_color : background--white`
`text_color ? text_color : text--black`
`text_align ? text_align : text--center`

This is the code I have set up in my nunjucks:
How would I write the above statements in nunjucks syntax?
```
<section class="layout-container background--{{ bg_color }} text--{{ text_color }} text--{{ text_align }}">
    {% block content %} {% endblock %}
</section>
```
