### ISSUE TITLE
Is the order guaranteed when using a for loop on an object?

### ISSUE THREAD

**Issue by danieldiekmeier** [mozilla/nunjucks#675]
If I create an object directly in the template, and iterate with a for loop, will the order be guaranteed?

Example:
```html
<div class="CheckoutProgress">
  {% for key, value in {
    'cart': 'Your cart',
    'delivery': 'Delivery options',
    'payment': 'Payment options',
    'confirm': 'Confirmation'
  } %}
    <div class="CheckoutProgress-item {{key}}">{{value}}</div>
  {% endfor %}
</div>
```

Because in general JavaScript objects are not ordered: http://stackoverflow.com/questions/5525795/does-javascript-guarantee-object-property-order

And the documentation doesn't explicitly state it: http://mozilla.github.io/nunjucks/templating.html#for, but it refers to `dictorder()` in the Jinja documentation, which advises to order dicts if a specific order is desired.

When I test it locally, it seems to work, but that may be by chance. Can this be guaranteed or would I be better of using an array of arrays, like

```html
<div class="CheckoutProgress">
  {% for key, value in [
    ['cart', 'Your cart'],
    ['delivery', 'Delivery options'],
    ['payment', 'Payment options'],
    ['confirm', 'Confirmation']
  ] %}
    <div class="CheckoutProgress-item {{key}}">{{value}}</div>
  {% endfor %}
</div>
```

I'd also be happy to create pull request to include the answer in the docs, if that's desired.

**Comment by carljm** [comment]
No, the order is not guaranteed, in either nunjucks/JS or in Python/Jinja. I'm not sure how the Jinja `dictsort` docs gave you the impression that it might be -- the reason the `dictsort` filter exists is because Python dicts do not preserve order either, so you need to use the filter when iterating them if you want to apply a consistent ordering.
