### ISSUE TITLE
Check if variable contains part of a string

### ISSUE THREAD

**Issue by Zubrik** [mozilla/nunjucks#676]
Hi,

I'm defining a variable:

`{% set activePage = "foo bar" %}`

Then I have some html:

`<body class="{{activePage}}">`

Which gives me:

`<body class="foo bar">`

I'd like to check if 'activePage' contains at least 'foo' (and not necessarily 'bar'), but obviously this returns false:

`{%if activePage == 'foo' %}`

How could I check if the variable holds just one of those class names?

Thanks.

**Comment by carljm** [comment]
`{% if 'foo' in activePage %}` should work.

**Comment by kuerbi** [comment]
> `{% if 'foo' in activePage %}` should work.

it seems not to work anymore because statement is always true

  {% if 'foo' in 'bar' %}
    Should not be displayed but it is
  {% endif %}
  
  is there a new syntax?
