### ISSUE TITLE
Indenting blocks and partials

### ISSUE THREAD

**Issue by mrcsmcln** [mozilla/nunjucks#677]
With Nunjucks, it's possible to indent macros like so:

```
{{ mymacro(someData) | indent(4) }}
```

But when I attempt this with blocks and partials, indenting doesn't work, and I'm assuming it's because you can't pass a filter on those directives.

Is there any way to accomplish this? Wouldn't it just make sense to have an option to auto-indent by default?

**Comment by carljm** [comment]
You can apply any filter you like to an arbitrary block of template code using the `filter` tag: http://mozilla.github.io/nunjucks/templating.html#filter

You can't apply that _directly_ to a block or include, but you can just wrap its entire contents with `{% filter indent(4) %}...{% endfilter %}`.

Auto-indenting is an HTML-specific feature that is orthogonal from nunjucks, which is not an HTML-specific templating engine. There's no signifcant benefit to having it inside nunjucks as opposed to as an external post-processor for the generated HTML (especially considering that it's usually something you'd only want in development; generally in production it makes more sense to minify than auto-indent your HTML, if you're going to bother doing anything to it).
