### ISSUE TITLE
whitespace at the beginning of the text

### ISSUE THREAD

**Issue by tk-codes** [mozilla/nunjucks#680]
```
     <div>
          {#add spaces at the beginning of the text#}
          {% for count in range(1,spaces) -%}
            {{ '&nbsp;' }}
          {%- endfor %}
          {{ strText}}
      </div>
```
The div tag shows a string (strText). I need to add few whitespaces in front of the text. I couldn't find a proper function in nunjucks. Could anyone please assist me?

**Comment by carljm** [comment]
I'm not sure I understand the question. If you want to display a non-breaking-space, just do it directly in the template (`&nbsp;`), there's no point in wrapping it up in `{{ '&nbsp;' }}` -- in fact, doing the latter might cause it to be auto-escaped.
