### ISSUE TITLE
blocks defined within "include" partial file ignored by extend

### ISSUE THREAD

**Issue by dkebler** [mozilla/nunjucks#682]
Here is my use case

I have a file that pulls pieces together (holy-grail.njs) that then is extended by the actual page I want (single.njs).  Problem is that the blocks defined in included files are ignored by the actual page template.  You can see the extended sidebar text is not appearing in screenshot  `<p>Here is some additional content for the sidebar extended in</p>`

Just for grins I moved that block code from sidebar.njs to holy-grail.njs and yes it is extended by single.njs so it is indeed as I suspected. 

Is the a bug?, a non-feature?  I assumed that "included" files were just included as is before further processing but maybe they are processed then included?   Without being able to do this my whole groovy way of organizing my template pieces/partials and then extending/customizing the content will be a no go.  

 single.njs
```
{% extends "layouts/holy-grail.njs" %}

{% block sidebar %}
<p>Here is some additional content for the sidebar extended in</p>
{% endblock %}

{% block article %}
  {% raw %}
  {{ Hugo code here to grab the article title and content }}
  {% endraw %}
{% endblock %}

```

holy-grail.njs
```
{% set reg = "regions/" %}
{% set cmp = "components/" %}
 
{% include "regions/head.njs" %}
<body class='page'>
    {% include  reg + "header.njs" %}
     <div class="rollover-wrapper">
        {% include reg + "topbar.njs" %}
        <main>
        {% include reg + "sidebar.njs" %}
        <section id="content">
          {% block article %}
            {# This is where one melds in article content #}
          {% endblock %}
        </section>
          </main>
          {% include reg + "footer.njs" %}
       </div>
      {% include cmp + "javascripts.njs" %}
  </body>
```

sidebar.njs
```
<aside id="sidebar" class="sidebar">
<p> some sidebar content set in the sidebar.njs file </p>
{% block sidebar %}
  {# This is where one melds in more sidebar content #}
{% endblock %}
</aside>
```
![nunjucks](https://cloud.githubusercontent.com/assets/1316185/13163110/1c45da10-d65f-11e5-8c9b-76c603221b57.png)

**Comment by carljm** [comment]
Your guess is correct: includes operate at a "higher level" than template inheritance. So an included template can have blocks, and can have its own "extends" tag, and a totally separate template inheritance hierarchy, but its blocks don't in any way interact with the blocks of the including template's inheritance hierarchy.

**Comment by dkebler** [comment]
so if I preprocessed with another tool putting together all my "partials" then process with nunjucks that should work?

**Comment by carljm** [comment]
Sure. Though that seems like a lot of trouble; I think your main layout would be perhaps even easier to read and maintain if it weren't spread across all those files. But your call.

**Comment by dkebler** [comment]
For those facing the same limitation or coming here from issues  #536  #460

My work around per above here
http://stackoverflow.com/questions/35496514/nunjucks-blocks-defined-within-include-partial-file-ignored-by-extend

@carljm FYI I referenced this issue in the others mentioned.  Hopefully will keep folks like me :-) from recreating this non-issue.   If you'd merge it I'd put a n.b. in the docs in the extend section pointing out this limitation with regards to extend with include in a parent.

**Comment by carljm** [comment]
@dkebler I wouldn't be opposed to adding something about this to the docs, but I will be particular about the wording. This is a design choice, not a "limitation." The design choice made by Jinja2/nunjucks is in some ways _more_ powerful than the design choice you were expecting (because it allows includes to have their own inheritance/block structure, so you can e.g. have a set of component includes that all inherit from a shared base component template).

I took a stab at an explanation here: http://stackoverflow.com/a/35512543/3207

**Comment by dkebler** [comment]
For me (and some others obviously) I think there is an expectation that an
include/import is simply merging and can be chained like in for example
sass.  For me being new to html templates extend is great and I see why now
include doesn't allow access to blocks within or otherwise block namespaces
could collide all over the place especially if including someone else's
library where they intended their blocks names to be "private".

So yes your extended/include explanation at stackoverflow but a bit more
terse in the include section of the docs would have made it clear to me
what I was attempting to do would not work as intended and how include
actually functions.   Put it there and you can imagine this exchange never
happening again :-).




On Fri, Feb 19, 2016 at 10:42 AM, Carl Meyer <notifications@github.com>
wrote:

> @dkebler <https://github.com/dkebler> I wouldn't be opposed to adding
> something about this to the docs, but I will be particular about the
> wording. This is a design choice, not a "limitation." The design choice
> made by Jinja2/nunjucks is in some ways *more* powerful than the design
> choice you were expecting (because it allows includes to have their own
> inheritance/block structure, so you can e.g. have a set of component
> includes that all inherit from a shared base component template).
>
> I took a stab at an explanation here:
> http://stackoverflow.com/a/35512543/3207
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/nunjucks/issues/682#issuecomment-186355825>.
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by carljm** [comment]
Note added at https://github.com/mozilla/nunjucks/commit/988acd9f9bfb8b08a2a83a316b4cb10032e3e848#diff-21628588bec65d836504fdc20804ba63R472
