### ISSUE TITLE
generate less variables

### ISSUE THREAD

**Issue by pinin** [mozilla/nunjucks#684]
I do not know if I have correctly
It can be generated in this case.
```
{% for icon in icons -%}

.@{{{icon.className}}-css-prefix}-{{icon.name}}:before { 
	content: @{{icon.className}}-var-{{icon.name}}; 
}

{% endfor %}
```

the problem here is - less variables as selector
```
.@{{{icon.className}}-css-prefix}
```
I do not know how to write to generate a properly
```
.@{icon-css-prefix}-facebook:before  {  content: @icon-var-facebook; }
.@{icon-css-prefix}-instagram:before  {  content: @icon-var-instagram; }
.......
```
Thank you for your help

**Comment by carljm** [comment]
It may be that the only way to handle this syntactical ambiguity is to change the syntax used by nunjucks to demarcate tags and vars: http://mozilla.github.io/nunjucks/api.html#customizing-syntax

**Comment by pinin** [comment]
Simple - super, thank you, it works
