### ISSUE TITLE
Advice on file extensions and how to handle syntax highlighting?

### ISSUE THREAD

**Issue by joelbschwartz** [mozilla/nunjucks#685]
I'm looking for guidance from the community, and how people deal or don't deal with syntax highlighting. Any advice? Is using a unique extension like `.nunjucks` a misrepresentation of the purpose of Nunjucks? In the absence of prescribing a file extension for Nunjucks, seems like a number of folks have come up with their own. Plugins for Atom, Brackets, Sublime, and Vim use a mix of `.nunjucks`, `.nunjs`, `.nunj`, `.njk`., and `.njs`.

I didn't see anything explicit in the documentation about file extensions, but Jinja is direct about it:

> A Jinja template is simply a text file. Jinja can generate any text-based format (HTML, XML, CSV, LaTeX, etc.). A Jinja template doesn’t need to have a specific extension: .html, .xml, or any other extension is just fine.

I understand the intention, but find it confusing because although Jinja can be anything, HTML cannot be anything. Appending an extra extension such as `*.html.nunjucks` might be more clear (albeit verbose)? If my comments are unwelcome in this pirate community of extension hijackers, please let me know. :)

**Comment by carljm** [comment]
Personally I use the `.j2` extension for both Jinja2 and Nunjucks templates (in some cases I will render the same template with either renderer, so I prefer having a single extension for both). I don't agree with the recommendation in the Jinja2 docs -- an HTML file is not the same thing as a Jinja2 template of an HTML file; I'll often "stack" extensions and use e.g. `.html.j2` for an HTML Jinja2 template.

That's all just my personal preference, though -- I'm not really aware of any community standard here.

For future reference, this type of conversation fits better on the mailing list (groups.google.com/group/nunjucks) than it does as a GH issue.

**Comment by joelbschwartz** [comment]
Thanks, @carljm, and thanks for the note on the mailing list. :+1:

**Comment by sapjax** [comment]
I hope extension should be customize.
