### ISSUE TITLE
how to convert

### ISSUE THREAD

**Issue by atmjs** [mozilla/nunjucks#690]
```
// in route
res.locals.test = function ('fileId', callback) {
  return 'test(' + arg1 + ',' + String(callback) + ');'
}

res.render('index.html', {title: 'index'})

//in template index.html
{{ test('fileId', "function (M) {
    log('{{ title }}');
}") }}
```
how to convert  '{{title}}'  to 'index' in 'index.html'

**Comment by carljm** [comment]
please ask usage questions on the mailing list (https://groups.google.com/forum/#!forum/nunjucks)

**Comment by atmjs** [comment]
my English is poor, please tell me which problem is similar with mine? is [https://groups.google.com/forum/#!topic/nunjucks/Li7YeASHYR0](url) ?
