### ISSUE TITLE
renderString() ignores opts with custom FileSystemLoader

### ISSUE THREAD

**Issue by jtlapp** [mozilla/nunjucks#692]
In v2.3.0, `renderString()` is ignoring the options that are passed to a new `FileSystemLoader`. I've confirmed this for both `autoescape` and `throwOnUndefined`. Here is a demo for `autoescape`:

    var nunjucks = require("nunjucks");
    var templateDir = "./templates";
    var opts = {autoescape: false};
    var render = function(env) {
        return env.renderString("{{text}}", {text: "&mdash;"});
    };

    var loader = new nunjucks.FileSystemLoader([templateDir], opts);
    var env = new nunjucks.Environment(loader);
    console.log(render(env)); // --> "&amp;mdash;"

    env = nunjucks.configure(templateDir, opts);
    console.log(render(env)); // --> "&mdash;"

If this is intended behavior, it should probably be stated in the docs somewhere. However, considering that `renderString` is a method of Environment, I'd expect default environment behavior.

**Comment by carljm** [comment]
`autoescape` and `throwOnUndefined` are env options, not loader options. I wouldn't expect them to ever have any effect at all when passed to a loader. Do they in some circumstances? If not, do we have docs somewhere implying that they should?

**Comment by jtlapp** [comment]
Drats. My mistake. I spent an hour debugging this and never thought to see if `Environment` might have its own options. Thanks.
