### ISSUE TITLE
Allow variable in {% include %}

### ISSUE THREAD

**Issue by jokull** [mozilla/nunjucks#7]
Any reason this can’t be supported? This would make the include statement very dynamic. Jinja2 supports this.

**Comment by daslicht** [comment]
Is there a wa y to import things like this : 

```
{% include myvar %}
```
myvar would be a passed variable as context .

**Comment by carljm** [comment]
@daslicht yes, it works just like that. That's what this ticket is about, and it's been fixed for 3 years :)
