### ISSUE TITLE
Switch from JSHint to ESLint

### ISSUE THREAD

**Issue by ricordisamoa** [mozilla/nunjucks#704]
Some of the options currently used by Nunjucks in `.jshintrc`, e.g. `quotmark`, have been deprecated by JSHint because they don't concern code correctness. We should maybe have a look at [JSCS](http://jscs.info) which is specifically targeted towards code style issues. At first glance, "yandex" seems to be the builtin preset with the fewest errors but a custom one can be easily crafted.

**Comment by jgerigmeyer** [comment]
If we're making a change, I'd seriously consider [ESLint](http://eslint.org/) instead of combining JSCS and JSHint.

**Comment by carljm** [comment]
Yeah, I'd probably also prefer switching to ESLint, which does both in a single tool.

**Comment by ricordisamoa** [comment]
Given that consensus is clear, and most importantly since [most of the JSCS maintainers will join the ESLint team](//medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2), I am going to update the title.

**Comment by fdintino** [comment]
This will be fixed by #1052

**Comment by fdintino** [comment]
Fixed by #1052
