### ISSUE TITLE
Filters cannot be used inside import tags.

### ISSUE THREAD

**Issue by legutierr** [mozilla/nunjucks#709]
Although the documentation says that _"`import` actually accepts any arbitrary expression, so you can pass anything into it, as long as the expression evaluates to a string or a compiled Template object"_, filters don't work inside the `import` tag, nor inside the `from` tag.  For instance, this cannot be parsed:

    {% import "foo/bar.html"|replace("html", "j2") as baz %}

Neither can this:

    {% from nullvar|default("foo/bar.j2") import baz, foobar as foobarbaz %}

Jinja does not have this limitation; neither does Nunjucks' own `include` tag.

**Comment by carljm** [comment]
Fixed with merge of #710.
