### ISSUE TITLE
List of ide/editors that support nunjucks

### ISSUE THREAD

**Issue by puranjayjain** [mozilla/nunjucks#711]
Can we have a list of ide / editors that have autocomplete / grammer support for nunjucks on the website?

**Comment by jbmoelker** [comment]
The syntax of Nunjucks templates is pretty much compatible with the syntax of Twig. I've successfully been using [Twig IDEs integration](http://twig.sensiolabs.org/doc/templates.html#ides-integration).

**Comment by puranjayjain** [comment]
thanks @jbmoelker for the hack but my question is that why dont we have a showcase or links to them on the website itself?

**Comment by carljm** [comment]
Frankly, I don't want to take on responsibility for maintenance of such a list in the nunjucks documentation.

**Comment by puranjayjain** [comment]
@carljim I'll be happy to take on that responsibility if I'm given it. :)

**Comment by carljm** [comment]
@puranjayjain Where on the website would you put it?

**Comment by puranjayjain** [comment]
@carljm possibly in a new section under the documentation section (alongside Getting Started, API, etc.).
With a title 'IDE Support' or a more relevant title. 
Under it all the ide or text editors that support it will be listed.

**Comment by carljm** [comment]
Hmm. I don't think this information is important enough to take up a top-level navigation item. I'm still not fully convinced that we even need it on the site at all.

**Comment by puranjayjain** [comment]
@carljm ok then I shall not pursue this anymore :)

**Comment by ricordisamoa** [comment]
cf. [jinja2](http://jinja.pocoo.org/docs/dev/integration/#textmate)

**Comment by carljm** [comment]
Hmm, I could see doing an "integrations" page like Jinja2. That would cover more than just IDEs/editors with syntax highlighting support, it could also include documentation about integration with e.g. Express, Sails, Consolidate.js, whatever else. Especially if we remove the built-in Express integration, we'll need such a page.

Given that broader purpose, I'd accept a PR to start such a page, even if the initial content is just IDEs/editors (though obviously if it included other framework integration docs that'd be great).

**Comment by puranjayjain** [comment]
great I'll start a pr thanks @ricordisamoa for the idea!

**Comment by carljm** [comment]
thanks @puranjayjain !
