### ISSUE TITLE
Browser bundle of nunjucks 2.4.1 not support ie8 

### ISSUE THREAD

**Issue by tablecell** [mozilla/nunjucks#715]
```
<html>
<head>
<script type="text/javascript" src="//cdn.bootcss.com/es5-shim/4.5.7/es5-shim.js"></script>
<script type="text/javascript" src="//cdn.bootcss.com/es5-shim/4.5.7/es5-sham.js"></script>
<script type="text/javascript" src="http://localhost:8080/nunjucks.js"></script>
</head>
<body>
<script>
alert(nunjucks.renderString('Hello {{ username }}', { username: 'James' }));
</script>
</body>
</html>

```
用户代理: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1) ; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; MALN; .NET4.0E; .NET4.0C; Media Center PC 6.0)
时间戳: Sat, 26 Mar 2016 02:30:49 UTC

消息: 缺少标识符、字符串或数字
行: 6095
字符: 6
代码: 0
URI: http://localhost:8080/nunjucks.js

**Comment by carljm** [comment]
Can you show the error that occurs?

Closing pending further information.
