### ISSUE TITLE
2.2.0 includes a nunjucks-slim.js incompatible with the output of the precompilation API.

### ISSUE THREAD

**Issue by mrehayden1** [mozilla/nunjucks#717]
Self explanatory really. The output of the API when precompiling templates is using calls to getTemplate which are incompatible with the packaged version of nunjucks-slim.js.

I discovered this when using gulp-nunjucks 2.2.0, which is the latest version, therefore I am unabled to upgrade to later version where this is fixed!

Searched the issue history for any reference to this issue but couldn't find anything.

**Comment by mrehayden1** [comment]
Using nunjucks-slim 2.3 on the front end seems to work as a workaround.

**Comment by carljm** [comment]
You should always precompile templates with the exact same version of nunjucks you are using on the front end with the compiled templates. I'm not sure from reading this issue if it's a result of not doing that? 

Even if that's not the case, if this is an issue only in nunjucks 2.2.0, we aren't going to make any retroactive changes to that release, so I don't think there are any action items here.

**Comment by mrehayden1** [comment]
I'm aware of that. I was however stuck with using 2.2.0 for reasons stated
above and needed a work around. The release notes for 2.3 show no API
changes so I went for it.
