### ISSUE TITLE
How to Negate in a if condition?

### ISSUE THREAD

**Issue by kamlekar** [mozilla/nunjucks#718]
I am confused on how to use `!` in if condition of nunjucks templates.

Like: 

    {% if (!pageName) %}
    <span>new page</span>
    {% endif %}

Currently, I am doing like this:
 
    {% if (pageName) %}
    {% else %}
    <span>new page</span>
    {% endif %}

**Comment by devoidfury** [comment]
Use the `not` keyword.

```jinja
{% if not pageName %}
<span>new page</span>
{% endif %}
```

http://mozilla.github.io/nunjucks/templating.html#logic

**Comment by kamlekar** [comment]
Thanks @devoidfury 

This should be definitely mentioned/referenced in `if` condition section of the docs. Because most of us are only interested in some parts of docs to do basic stuff like if, for and using variables.

Honestly, it is hard to figure out that this part is mentioned in the docs.

**Comment by carljm** [comment]
Many templating basics are not covered in the nunjucks docs; they are "covered" by the note up top that nunjucks is a port of Jinja2, which has detailed docs. That said, I wouldn't turn down any improvements to the nunjucks docs.

**Comment by athongintel** [comment]
nunjucks sucks from its name

**Comment by jasonstreet** [comment]
penorp
