### ISSUE TITLE
Cannot read property 'dev' of undefined on render()

### ISSUE THREAD

**Issue by paulxtiseo** [mozilla/nunjucks#719]
So, in one part of my server app, we load and pre-compile email templates at startup:
`api.templates.email[tplName] = nunjucks.compile(fs.readFileSync(tplPath, "utf-8"), {throwOnUndefined:true});`

If I include the `{throwOnUndefined:true}`, I get an error `TypeError: Cannot read property 'dev' of undefined` on the use of `render()`. If I exclude the setting, no error. The one test template we are using has no string `dev` in it, much less `{{dev}}`.

**Comment by carljm** [comment]
What version of nunjucks are you using? We recently fixed an issue related to accessing the `dev` option of a nunjucks environment, which affects handling of thrown errors.

Closing for now as I'm guessing this was fixed by that; will reopen if it is not fixed in the latest nunjucks version.
