### ISSUE TITLE
Support range(start, stop) for string array?

### ISSUE THREAD

**Issue by SimonSun1988** [mozilla/nunjucks#725]
Maybe like this

output data like this

```js
let stringArray = ['a', 'b', 'c', 'd', 'e'];
```

html like this

```js
{% for string in stringArray | limit(3) %}
    <div> {{ string }} </div>
{% endfor %}
```

Resault like this

```html
<div>a<div>
<div>b<div>
<div>c<div>
```

If I set limit, only output limit number data.

**Comment by carljm** [comment]
You can easily implement such a filter yourself, but I don't think it needs to be included in nunjucks.
