### ISSUE TITLE
Nunjucks.render('template.html') returns null

### ISSUE THREAD

**Issue by kevinisaac** [mozilla/nunjucks#728]
I assume that the `render` function is supposed to return the rendered template as a string. However, it returns `null`. The HTML template exists and it contains valid HTML. However, `renderString` works as expected (returns the rendered string).

This is the code:

```
define(
    ['jquery', 'underscore', 'backbone', 'nunjucks', 'text!/static/templates/snippets/account.html'],
    function($, _, Backbone, nunjucks, accountTemplate) {
        var AccountView = Backbone.View.extend({
            el: $('#main-content'),
            render: function() {
                var data = {};
                nunjucks.configure('static/templates', {
                    autoescape: true,
                    web: {
                        async: true
                    }
                });
                // var compiledTemplate = nunjucks.renderString('Hello there');
                var compiledTemplate = nunjucks.render('/snippets/account.html');
                console.log(compiledTemplate);
                this.$el.append(compiledTemplate);
            }
        });
        return AccountView;
    }
);

```

Maybe I'm doing something silly here, but I can't see it.

**Comment by kevinisaac** [comment]
Alright, using a callback function does the trick:

```
nunjucks.render('template.html', function(err, res) {
    console.log(res);  // Prints out the rendered template
});
```

Closing this issue, however, I'm not sure if `render()` returning `null` without using the callback is the expected behavior.

**Comment by carljm** [comment]
It's because you've set `{ web: { async: true } }` -- that declares your intention to use the async rendering API, which means you need to provide a callback to `render`. This should be more clearly noted in the `configure` docs; I'll add it there.

**Comment by carljm** [comment]
Added doc note in 6b200c5f0ee9edede5a1f2f6920b244bf9ec0af7

(BTW, you should probably precompile templates for browser use instead of using the web loader with async.)

**Comment by kevinisaac** [comment]
@carljm Thank you. I'm still experimenting with nunjucks and testing if the same template can be used for jinja2 for server side templating. I will look into precompiling templates.
