### ISSUE TITLE
Include in loop loads the template every time

### ISSUE THREAD

**Issue by softshape** [mozilla/nunjucks#733]
I have a loop -

      {% for student in json %}
	{% include "student.html" %} 
      {% endfor %}

If json has 100 items, there will be 100 get requests to the template, each with random s= parameter. How to avoid that? I tried -

nunjucks.configure('views', { autoescape: true, useCache: true });

- without success.

**Comment by devoidfury** [comment]
You can configure the loader to do that, see here: http://mozilla.github.io/nunjucks/api.html#webloader

It's recommended to precompile the templates in production for client-side usage.

**Comment by carljm** [comment]
Yes, @devoidfury is right. This is by design; every `include` asks the template loader for that template. If you want to cache templates or whatever else, you do that in a custom loader. Nunjucks includes the precompiled-templates loader, which is strongly recommended for use in production in the browser. The default WebLoader (which naively gets templates via Ajax requests) is _not_ recommended for production use.

**Comment by softshape** [comment]
Can you give an example of correct WebLoader usage? So far I've changed its configure to -

var env = new nunjucks.Environment(new nunjucks.WebLoader('views'), { autoescape: true, useCache: true } );

but it breaks the render.

**Comment by carljm** [comment]
You were already using the WebLoader correctly. It always fetches every template every time. To fix that, you should not use the WebLoader. You should use the PrecompiledLoader instead. (The PrecompiledLoader is automatically used if precompiled templates are found on the `window` object.) Please read the documentation on precompiling templates.

**Comment by softshape** [comment]
May I suggest an option like useCache for WebLoader? The one which would disable adding random parameter to template URL. I can't use PrecompiledLoader in development environment because it doesn't include any pre-processing like we do on production. Now any loop of 10-20 elements kills the page. 

To a side note, I try to present nunjucks to my collegues and talk them to use it in our project. Their main argument against nunjucks is that it's complicated 3rd party module I can't handle fully. If they knew that there's no option to disable random numbers in URL, it could be the last day of nunjucks in the project. Please help, I really like nunjucks.

**Comment by carljm** [comment]
There is currently no way to turn off the HTTP cache-busting when the WebLoader fetches templates (though I wouldn't be opposed to a PR providing an option for this). If, however, you call `nunjucks.configure('views', { web: { useCache: true }})`, nunjucks will internally cache each compiled template after the first time it is loaded, so you should never get more than one HTTP request for a given template name.

**Comment by softshape** [comment]
Thanks Carl, this is the solution! Great for dev mode, and even fine for production.
