### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL with unicode in HTML template

### ISSUE THREAD

**Issue by joelanman** [mozilla/nunjucks#736]
Not totally sure if this is a bug in Nunjucks or we're just using it wrong.

If the html template contains the [unicode character 8232](http://www.fileformat.info/info/unicode/char/2028/index.htm) (name: LINE SEPARATOR) then Nunjucks gives the error:

`SyntaxError: Unexpected token ILLEGAL`

**Comment by carljm** [comment]
That seems like a bug to me.

**Comment by zeakd** [comment]
I have same error. Sometime it works when I just cut and paste with out change.

**Comment by kevnk** [comment]
I found the same error with the character (highlighted in Pages.app) shown in the screenshot below. I'm not sure if this is the same character @joelanman is mentioning, but it was throwing the same error for nunjucks.

![screenshot](https://monosnap.com/file/aomFFxvftS1PUggWxlIFcjaVZ6reLk.png)
