### ISSUE TITLE
API consistency (render/precompile)

### ISSUE THREAD

**Issue by felixsanz** [mozilla/nunjucks#744]
Why render is a method on nunjucks environment and precompile is not? Examples:

``` javascript
nunjucks.render // ok
nunjucks.precompile // ok

const env = new nunjucks.Environment()
env.render //  ok
env.precompile // error
```

**Comment by carljm** [comment]
I don't see anything wrong with providing `EnvironmentL#precompile` as a shortcut to calling `nunjucks.precompile` with `env` set in the `opts`. Thanks for the suggestion!
