### ISSUE TITLE
Safe seems to be escaping an ampersand when it should not.

### ISSUE THREAD

**Issue by tylerwgoza** [mozilla/nunjucks#745]
I have code marked as safe that nunjucks is escaping anyway. 
`Welcome{{',&nbsp;' + name if name else '' | safe}}`
And am getting `Welcome,&nbsp;name` (the html output is actually `Welcome,&amp;nbsp;name`) printed instead of `Welcome, name` the way it should print. 
It is possible that I'm missing something here but it seems like a bug.

**Comment by carljm** [comment]
I haven't played with this, but given your sample code it seems like it could be a precedence issue? I.e. the filter pipe might bind more closely than the inline if/else, so you're actually only marking the fallback empty string as safe. See if some parentheses help?

**Comment by tylerwgoza** [comment]
Awesome. I'll give that a shot and let you know, my temporary work around was to just use a regular if and move where I was processing that. (Opening tag above the if closing tag after the endif) and only access the variable I was aiming for. But it would be cool if I could figure out why that didn't work. I'll get you an update as soon as I can play with that.

**Comment by tylerwgoza** [comment]
Dead on! The answer was `Welcome{{ (',&nbsp;' + name if name else '') | safe}}` and it printed as expected. Thanks! Probably one of the easier issues to deal with.

**Comment by carljm** [comment]
Great!
