### ISSUE TITLE
Is partial Rendering of nunjucks templates possible ?

### ISSUE THREAD

**Issue by sirajulm** [mozilla/nunjucks#747]
I'm having a nunjucks template file `template1.nunjucks`, with two variable/partials placeholders

    This is {{ var1 }}
    This is  {{ var2 }}

I wish to render the `var1` placeholder during build time and save the template as `template2.nunjucks`

`{var1: 'Hello World'}`

    This is Hello World
    This is  {{ var2 }}

During run-time `template2.nunjucks` will be picked up and the server will render for `var2` alone and serve the response as

`{var2: 'It Works!' }`

    This is Hello World
    This is  It Works!

By default I could see that nunjucks will replace all the placeholders when asked to render a template, even if we dont provide the value for a placeholder.
Is doing so possible with nunjucks ?

**Comment by carljm** [comment]
I think you might be able to achieve this by using a different nunjucks environment during build time that customizes the block-start and block-end syntax, then wrapping var2 in that alternate syntax.

I think making nunjucks able to automatically do this based on whether the var is set or not would be quite difficult.

**Comment by sirajulm** [comment]
Got that. Thanks :+1:
