### ISSUE TITLE
Async parser to fix "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by SamyPesse** [mozilla/nunjucks#749]
Currently Nunjucks is using a [synchronous parser](https://github.com/mozilla/nunjucks/blob/master/src/parser.js), and an asynchronous/synchronous rendering process.

When parsing a huge file (~300 custom blocks), its failing with `RangeError: Maximum call stack size exceeded`.

The easiest solution will be switch the parser to asynchronous (calling `setImmediate` / `setTimeout` before switch to next token).

I can work on a PR for this, but it might break the API for people using the nunjuck parser directly (I can maybe try to make it both sync/async according to the signature of `render` / `renderString`).

@carljm what do you think?

**Comment by carljm** [comment]
The internal parser API is not documented or supported for direct use, so I don't think we need to be concerned about backwards-compatibility there. I'm open to this if it doesn't introduce any other regressions for normal nunjucks use.

We could also defer it to 3.0 (which I would ideally like to get out soon, there are just a few blocking issues) if we're concerned about the backwards compatibility.

**Comment by SamyPesse** [comment]
The precompiler is using the parser, so switching it to async will force the precompiler (and compiler) to be async as well.

Is the `master` the branch for version 3.0 ?

**Comment by carljm** [comment]
Yes, `master` is the branch for 3.0; I've been manually backporting changes to the `2.x` branch if they are suitable for 2.x releases (ideally we'd have people submit PRs to the right branch and I'd merge forwards instead of backporting with cherry-pick, but getting people to submit PRs to the right branch is more hassle than I wanted to put contributors through :-) )

**Comment by carljm** [comment]
I'm a little concerned about the possible complexity of making both the precompiler and compiler async, but I'll wait to see what the PR looks like.

**Comment by SamyPesse** [comment]
I'm also concerned.. 😕 

I'm trying to determine if only the parser should be sync/async or the lexer as well.

```
 sync       sync         sync              sync/async         sync/async
[lexer] > [parser] > [compiler] > [environment] > [render/renderString]
```

Since the `render` and `renderString` should still work both async and sync, it forces the `compiler`, `parser` and `lexer` to still support sync.

I'm still looking for another solution.

**Comment by SamyPesse** [comment]
@carljm Sorry I was wrong, the issue is not coming from the parser.

After adding logs to different part of nunjucks, the parser and the compiler works fine, but the function generated by the compiler is throwing this error.

Here is the source compiled by nunjucks: https://gist.github.com/SamyPesse/ad8794f4a657aba730c3e310dd2356d3

The error is thrown at this line [src/environment.js#L564](https://github.com/mozilla/nunjucks/blob/master/src/environment.js#L564), before even calling the `root` function.

**Comment by carljm** [comment]
Ah hmm. Yeah that makes a bit more sense. Kinda good news in that it means you don't need to modify the whole lexer/parser/compiler chain -- but bad news in that I'm not sure how feasible it will be to change nunjucks' compiled output to fix this :/

Seems like it might be a dupe of #643?

**Comment by SamyPesse** [comment]
Yes it's the same kind of issue, the problem seem to be that the source code generated contains too much callbacks; one solution can be to change the `compiler` to generate something which is using promises.

I'll try to implement a fix locally, and publish a PR if I have something which is working

**Comment by hydiak** [comment]
Any news?

**Comment by hydiak** [comment]
[Here](https://github.com/mozilla/nunjucks/pull/787) a PR with possible solution

**Comment by SamyPesse** [comment]
Closing this issue since #787 has been merged.
