### ISSUE TITLE
something very screwy with nunjucks-slim exporting nothing

### ISSUE THREAD

**Issue by dgbeck** [mozilla/nunjucks#751]
My head is spinning. My sense is that there is a fundamental, simple problem with nunjucks-slim that makes it impossible to use in many cases.

After including nunjucks-slim, how can the global nunjucks object be accessed? Am I missing something obvious?

As far as I can tell, nunjucks-slim exports nothing to the global `window` object.

```
<script src="nunjucks-slim.js"></script>
// now window.nunjucks === undefined
```

using browserify, the module has no return value

```
var nunjucks = require( 'nunjucks/browser/nunjucks-slim' );
// now nunjucks === undefined
```

Without access to the nunjucks object, there is no way, for example, to use the `nunjucks.configure()` method. There is also no way to add filters to the environment object used by precompiled templates (that is created on line 99 of nunjucks-slim).

I have read the discussion on #507, which seems to be somewhat related, but this also seems like a separate, more fundamental problem. In this case we are just concerned with using nunjucks-slim in the browser with pre-compiled templates, which looks like [a supported and recommend way](https://mozilla.github.io/nunjucks/getting-started.html) to use nunjucks in production.

Simply adding

```
if( window ) window.nunjucks = nunjucks;
```

at the bottom of nunjucks-slim would solve the issue. Or, alternatively, adding a UMD wrapper would also work. ANY way to get at the nunjucks object would be acceptable.

I am happy to help resolve this issue by submitting a PR. @carljm or whoever is currently steering this ship, can you confirm that such a PR is appropriate, and if so, if you have a preference on a UMD wrapper or just a simple export to `window.nujucks`?

**Comment by devoidfury** [comment]
The nunjucks-slim file starts with `var nunjucks=` -- it should be exported to window and I'm using it in production over here.

**Comment by carljm** [comment]
Thanks for the report!

The fact that it doesn't export anything for browserify or webpack is known and the subject of #507.

AFAIK it should set `window.nunjucks` if sourced directly in the browser.

**Comment by dgbeck** [comment]
Ok I will comment over there, thx.
