### ISSUE TITLE
Built-in included templates/files when precompinling

### ISSUE THREAD

**Issue by softshape** [mozilla/nunjucks#756]
Is there any way to tell nunjucks to actually insert included template's content into the outer template when it produces its precompiled version? We need this for some templates and files (we use "include" for svg files also) to make less server hits when template is loading in the browser.

**Comment by carljm** [comment]
That's something you'd need to do outside of nunjucks (e.g. by preprocessing templates to look for static includes and adding them to your list of templates to be precompiled). Includes happen at runtime, not in a preprocessor step, and includes can be dynamic, so there's no real way for nunjucks to do that.

I'm not sure why you're hitting this issue at all, for two reasons: 1) normally you'd just precompile all your templates, which would catch the includes too (or if you are rendering on both client and server side and want to precompile only the client side templates, maybe put them in a directory or use a filename extension pattern to indicate which templates to precompile), and 2) if you're using the precompiled loader in the browser, there shouldn't be any server hits at all.

You can treat your SVG files like any other template and precompile them, too.
