### ISSUE TITLE
prevent node from crashing on invalid syntax

### ISSUE THREAD

**Issue by silverbux** [mozilla/nunjucks#758]
im compiling and rendering data based from user inputs,
for example if the user input is ```{{ myvar || 'test' }}``` it would crash nodejs. 
is there an option where i could simply ignore invalid syntax? or a better approach to handle this

**Comment by devoidfury** [comment]
You should be able to wrap the `render` call in a try-catch and handle the error in the catch block, or use `render` with the callback argument http://mozilla.github.io/nunjucks/api.html#render
