### ISSUE TITLE
nunjucks-precompile not outputting a .js file

### ISSUE THREAD

**Issue by Mikejonesab12** [mozilla/nunjucks#763]
I am passing the nunjucks-precompile script a directory of input templates and a path to output to. The corresponding .js file is not being created. Instead, the precompiled templates are just being outputted to the console.

Example: nunjucks-precompile src/ dist/templates.js
I am on the windows platform.

**Comment by rhengles** [comment]
http://mozilla.github.io/nunjucks/api.html#precompiling

All the templates will be precompiled always to one file, so you need to use `> output.js` to save it.

**Comment by Mikejonesab12** [comment]
Yep. I am an idiot.
