### ISSUE TITLE
Condolidate doesn't recognize `.njk` files, only `.nunjucks`?

### ISSUE THREAD

**Issue by niftylettuce** [mozilla/nunjucks#767]
https://github.com/tj/consolidate.js/

https://github.com/tj/consolidate.js/blob/8c6dcf22433ccd73198d71bcc2d9f5dbb73f0a57/lib/consolidate.js#L1084

**Comment by carljm** [comment]
This isn't something nunjucks can address.

**Comment by niftylettuce** [comment]
Is it possible you could help point me in the right direction for where this needs to be changed?  I'm uncertain. @carljm

**Comment by carljm** [comment]
Well, in Consolidate I presume? I don't know more than that, never used Consolidate.
