### ISSUE TITLE
Measure test coverage of logic inside templates

### ISSUE THREAD

**Issue by nbransby** [mozilla/nunjucks#769]
I would like to ensure my tests are covering all code paths In the logic defined within my nunjucks templates. 

I had hoped precompiling the template would convert the ifs and loops etc. to javascript and so I could measure the coverage in the compiled template js files but it appears the template is still just text in a string in the js file.

Any ideas on how I could achieve my mission?

**Comment by carljm** [comment]
I'm not sure how you are drawing the conclusion that "the template is still just text in a string in the JS file," but that's not true. Precompilation does convert template logic to JS code, and you should be able to measure coverage on that generated code (though you may have trouble achieving good coverage on it, because it includes checks for a variety of cases that your usage of the template might not hit -- for instance, every loop generates code for handling looping over several different types of objects).

**Comment by nbransby** [comment]
Ok thanks for that - my conclusion is from the output from the nunjucks-precompile tool, example below:
`(function() {(window.nunjucksPrecompiled = window.nunjucksPrecompiled || {})["..\\..\\..\\src\\swift\\javascriptcore.njk"] = (function() {
function root(env, context, frame, runtime, cb) {
var lineno = null;
var colno = null;
var output = "";
try {
var parentTemplate = null;
output += "<% extends \"swift.njk\" %>\r\n\r\n<% block header %>\r\n    <%- if module.name == file.path.name -%>\r\n        var this :JSInstance = try! JSContext().eval(NSBundle<% if bundleId %>(identifier: \"<$ bundleId $>\")!<% else %>.mainBundle()<% endif %>.pathForResource(\"src\", ofType: \"js\")!)\r\n    <% endif %>\r\n<% endblock %>\r\n\r\n<% macro arrayElementReturnValue(type, optional = type.optional) -%>\r\n    <%- if type|kind == 'AnyType' -%>\r\n        <%- if optional -%>\r\n            { Any?($0, wrapped: JSValue.infer) }\r\n        <%- else -%>\r\n            JSValue.infer\r\n        <%- endif %>\r\n    <%- elif type|kind == 'ArrayType' -%>\r\n        { <$ signature(type, optional) $>($0, element: <$ arrayElementReturnValue(type.typeArguments[0]) $>) }\r\n    <%- else -%>\r\n        <%- if optional -%>\r\n            { <$ signature(type, optional) $>($0, wrapped: <$ signature(declaration.type, false) $>.init) }\r\n        <%- else -%>\r\n            <$ signature(type, optional) $>.init\r\n        <%- endif %>\r\n    <%- endif %>\r\n<%- endmacro -%>\r\n\r\n<% macro returnValue(declaration) -%>\r\n    <%- if declaration.type|kind == 'AnyType' -%>\r\n        <%- if declaration.type.optional -%>\r\n            Any?(this[.<$ declaration.name $>], wrapped: JSValue.infer)\r\n        <%- else -%>\r\n            this[.<$ declaration.name $>].infer()\r\n        <%- endif %>\r\n    <%- elif declaration.type|kind == 'ArrayType' -%>\r\n        <%- if declaration.type.optional -%>\r\n            <$ signature(declaration.type) $>(this[.<$ declaration.name $>], wrapped: <$ arrayElementReturnValue(declaration.type, false) $>)\r\n        <%- else -%>\r\n            <$ signature(declaration.type) $>(this[.<$ declaration.name $>], element: <$ arrayElementReturnValue(declaration.type.typeArguments[0]) $>)    \r\n        <%- endif %>\r\n    <%- else -%>\r\n        <%- if declaration.type.optional -%>\r\n            <$ signature(declaration.type) $>(this[.<$ declaration.name $>], wrapped: <$ signature(declaration.type, false) $>.init)\r\n        <%- else -%>\r\n            <$ signature(declaration.type) $>(this[.<$ declaration.name $>])\r\n        <%- endif %>\r\n    <%- endif %>\r\n<%- endmacro -%>\r\n\r\n<% macro arrayElementArgumentValue(type) -%>\r\n    <%- if type|kind == 'ArrayType' -%>\r\n        { this.valueOf($0, element: <$ arrayElementArgumentValue(type.typeArguments[0]) $>) }\r\n    <%- else -%>\r\n        this.valueOf\r\n    <%- endif %>\r\n<%- endmacro -%>\r\n\r\n<% macro argumentValue(declaration) -%>\r\n    <%- if not declaration.type.optional and declaration.type|kind == 'ArrayType' -%>\r\n        this.valueOf(newValue, element: <$ arrayElementArgumentValue(declaration.type.typeArguments[0]) $>)\r\n    <%- else -%>\r\n        this.valueOf(newValue<% if declaration.type.optional %>, wrapped: <$ arrayElementArgumentValue(declaration.type) $><% endif %>)\r\n    <%- endif %>\r\n<%- endmacro -%>\r\n\r\n\r\n<% macro var(declaration) -%> {\r\n    get {\r\n        return <$ returnValue(declaration) $>\r\n    }\r\n    set {\r\n        this[.<$ declaration.name $>] = <$ argumentValue(declaration) $>\r\n    }\r\n} \r\n<%- endmacro -%>\r\n\r\n<% block variable %>\r\n    <%- if declaration.constant -%>\r\n        = <$ returnValue(declaration) $>\r\n    <%- else -%>\r\n        <$ var(declaration) $>\r\n    <%- endif -%>\r\n<% endblock %>\r\n\r\n<% block footer -%>\r\n    <%- if module.name == file.path.name -%>\r\n        <% filter indent(-3) %>\r\n            extension JSProperty {\r\n                <%- filter indent(-2) -%>\r\n                    <% for identifier in module.identifiers|array %>\r\n                        static let <$ identifier $> : JSProperty = \"<$ identifier $>\"\r\n                    <%- endfor %>\r\n                <%- endfilter %>\r\n            }\r\n        <%- endfilter %>\r\n    <% endif %>\r\n<% endblock %>\r\n\r\n";
if(parentTemplate) {
parentTemplate.rootRenderFunc(env, context, frame, runtime, cb);
} else {
cb(null, output);
}
;
} catch (e) {
  cb(runtime.handleError(e, lineno, colno));
}
}
return {
root: root
};

})();
})();

`

**Comment by carljm** [comment]
You appear to be precompiling a template that isn't using nunjucks syntax, thus none of the directives are being interpreted as control directives, the entire template is just being processed as plain text. Nunjucks syntax uses curly braces, not angle brackets.

**Comment by nbransby** [comment]
Ah yes I used the support for changing the syntax, guess that's not supported with precompilation

**Comment by carljm** [comment]
Ah! Yes, that should work fine with precompilation, but it means you need to precompile using a custom configured env, which means you have to use the precompilation API, you can't use the bundled script. See http://mozilla.github.io/nunjucks/api.html#precompiling
