### ISSUE TITLE
Any solution to  hack "overriding a block within an include"?

### ISSUE THREAD

**Issue by zheeeng** [mozilla/nunjucks#770]
#460 point out the missing inheritance in `include`. But I want to structure my files like:

beautiful-page.html:
```
{% extends "layout.html" %}

{% block styles %}
  <link rel="stylesheet" href="styles/pages/beautiful-style.css">
{% endblock %}

{% block content %}
  <p>This is a beautiful page.</p>
{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="scripts/pages/make-page-beautiful.js"></script>
{% endblock %}
```

layout.html:
```
<!DOCTYPE html>
<html>

{% include "includes/head.html" %}

<body>
  {% include "includes/header.html" %}

  {% include "includes/sider.html" %}

  {% block content %}{% endblock %}

  {% include "includes/footer.html" %}

  {% include "includes/scripts.html" %}

</body>

</html>
```

includes/head.html
```
<head>

<title>My Page</title>

<link rel="stylesheet" href="styles/general1.css">
<link rel="stylesheet" href="styles/general2.css">

<!-- stylesheet for specific page -->
{% block styles %}{% endblock %}

</head>
```
includes/scripts.html
```
<srcipt src="scripts/general1.js"></script>
<srcipt src="scripts/general2.js"></script>

<!-- script for specific page -->
{% block scripts %}{% endblock %}
```

`beautiful-page.html` extends layout file `layout.html`, `layout.html` renders block `content`. Then `layout.html` include `includes/head.html` and `includes/scripts.html`, they render block `styles` and `scripts` respectively.

I want a hack solution. What I'm using now is collecting all blocks in `layout.html`, not use include-files which contain blocks.

**Comment by carljm** [comment]
Sorry, nunjucks doesn't support your approach, and I'm not aware of any way to hack around it. If you want to use nunjucks, you'll need to adjust to a nunjucks approach, where includes are for partials (which can have their own independent inheritance), they are not pre-processors.
