### ISSUE TITLE
how can i use === operator

### ISSUE THREAD

**Issue by rambo-panda** [mozilla/nunjucks#771]
as title;

l want use the `===` operator in nunjucks!

This is my temporary solution.

---------------------------
```javascript
// add filter

{{ if a | all_equal(b) }}
//xxxxxxx
{{endif}}
```

**Comment by ricordisamoa** [comment]
#746 has not been released yet

**Comment by jbmoelker** [comment]
[Support for `===` is added in `v2.5.0`](https://github.com/mozilla/nunjucks/commit/b96a8f68f1ce226ea6c019c47f4be69d6c696895#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR20). So closing this issue.
