### ISSUE TITLE
Weird behavior of sort filter in a loop

### ISSUE THREAD

**Issue by kalote** [mozilla/nunjucks#773]
Hello,

I'm using nunjucks (latest 2.4.2) in a sailsJS app. In one of my template, i need to sort an array of data retrieved.
Here's what my code looks like:
```
{% for f in d.subFiles|sort(true, false, "title") %}
  <li>{{f.title}}</li> <!-- this line is in the right order -->
	{% for fe in f.files %}
  <li>{{fe.title}} - {{fe.src}}</li> <!-- this line is also in the right order -->
	<li class="document">
		<a href="{{fe.src}}" target="_blank">{{fe.title}}</a><!-- this is not in the right order -->
	</li>
	{% endfor %}
{% endfor %}
```

d.subFiles is an array of objects, and files is also an array of objects. Each "files" have a title and src attributes:
```
[ { title: 'FILES 2010',
    files:
     [ [Object],
       [Object] ],
    id: 'xxxx' },
{ title: 'FILES 2011',
    files:
     [ [Object],
       [Object] ],
    id: 'xxxx' } ]
```

My issue is that i display LIs in the right order, but when i have an LI with an A inside, the order is not good anymore.

My goal is to have the latest files first (my real array has files from 2010 to 2016). The first LI (f.title) display them in the right order, the second LI (fe.title - fe.src) display them in the right order, but the last part (LI > A) display them in the NOT REVERSE order.

Here's the final rendering that i have:
```
<li>FILE 2011</li>
<li>FILE 1 - /2011/file1.pdf</li>
<li>FILE 2 - /2011/file2.pdf</li>
<li>FILE 2010</li>
<li>FILE 1 - /2010/file1.pdf</li>
<li>FILE 2 - /2010/file2.pdf</li>
<li class="document">
    <a href="/2010/file1.pdf" target="_blank">FILE 1</a>
</li>
<li class="document">
    <a href="/2010/file2.pdf" target="_blank">FILE 2</a>
</li>
<li class="document">
    <a href="/2011/file1.pdf" target="_blank">FILE 1</a>
</li>
<li class="document">
    <a href="/2011/file2.pdf" target="_blank">FILE 2</a>
</li>
```

Strange that when it comes to the LI > A, it does not sort correctly. Also, how is it possible that it renders first the 1st and 2nd LIs, and then the LI > A ?

Thanks for helping

**Comment by carljm** [comment]
Sorry, without seeing the input data I can't penetrate this example to see what might be going wrong. The ticket tracker isn't a support resource; you could try the "nunjucks" Google Group mailing list instead. If you're able to boil this down to a simplest-case fully self-contained example that reveals a bug in nunjucks, please comment here and I'll reopen.
