### ISSUE TITLE
macro parameter with default value overshadowed by unrelated macro

### ISSUE THREAD

**Issue by oadam** [mozilla/nunjucks#774]
A macro parameter cannot be used when it :
* has a default value
* has the same name as another macro

The following code snippet outputs some js code instead of the provided string:

```jinja
{# macro1 and macro2 definition #}
{% macro macro1() %}
{% endmacro %}

{% macro macro2(macro1="default") %}
{{macro1}}
{% endmacro %}

{# calling macro2 #}
{{macro2("this should be outputted") }}
```

**Comment by ricordisamoa** [comment]
Nunjucks seem to behave differently from Jinja2 in this case.

**Comment by carljm** [comment]
Yes, this is definitely a bug. I fixed some bugs in related areas in master (not released yet, since some of those fixes are backwards-incompatible and thus targeted for 3.0), so I'd be curious to know whether you also observe this behavior in the master branch.

**Comment by ricordisamoa** [comment]
> I'd be curious to know whether you also observe this behavior in the master branch

Yes, Nunjucks 3.0.0-dev.3 behaves the same
