### ISSUE TITLE
length filter won't work with objects

### ISSUE THREAD

**Issue by softshape** [mozilla/nunjucks#776]
If JSON has the following node:
```
	"students": {
		"Roberta J.": "5%",
		"Julian F.": "8%",
		"Eliana P.": "12%",
		"Freddie M.": "22%"
	}
```

then in template {{ students | length }} returns empty string. I hoped that https://github.com/mozilla/nunjucks/pull/705 would fix this but no. Is there any support for objects length?

**Comment by ricordisamoa** [comment]
please see #283

**Comment by softshape** [comment]
length as a property would be a breaking change indeed. length as a filter - just an extending of the current filter who works with arrays and shows nothing with objects.

**Comment by carljm** [comment]
@softshape It's still a (minor) breaking change because currently if you have an object like `{length: 7}` the `|length` filter will return 7 for that object, and we want to change it to return ` instead.

**Comment by softshape** [comment]
But isn't this wrong result and `| length` as filter expected to return 1 in this case, and current 7 is just a side effect? This is not breaking but fixing change :)

**Comment by carljm** [comment]
Yeah, that's a reasonable interpretation :-)

I'd accept this change for 2.x if someone submits a PR.

Please direct further discussion to #283
