### ISSUE TITLE
Custom tag with a string argument

### ISSUE THREAD

**Issue by karellm** [mozilla/nunjucks#778]
Hi,

I'm pretty new to nunjucks and try to make a custom tag `{% image "1_create_bucket.png" %}` that would simply create an image tag and take care of setting the correct path.

Here is where I'm at so far:

```js
function ImageExtension() {
    this.tags = ['image']
    this.parse = function(parser, nodes, lexer) {
        var tok = parser.nextToken()
        var args = parser.parseSignature(null, true)
        parser.advanceAfterBlockEnd(tok.value)
        return new nodes.CallExtension(this, 'run', args)
    }
    this.run = function(context, url) {
      return new nunjucks.runtime.SafeString('<img src="' + url + '" alt="">')
    }
}
```

The issue is that `url` is `undefinied`. For some reason my string argument isn't being passed. Am I missing something? Thanks!

**Comment by carljm** [comment]
Not sure, I haven't written a custom tag in quite a while. However, this doesn't look like a case that really justifies a custom tag; why not just a macro?

BTW, please take usage questions to the Google Groups mailing list, not GitHub. Thanks!
