### ISSUE TITLE
Rendering macro inside res.render local variable is tricky!

### ISSUE THREAD

**Issue by feedmypixel** [mozilla/nunjucks#793]
# Getting Macro to render inside of included variable

I wish to render a macro that is found inside of the `res.render` local variable `content` when using `nunjucks` with express as described in the [getting started](https://mozilla.github.io/nunjucks/getting-started.html) guide. This appears to be very tricky and it feels like I am over engineering the solution.

### template.html
The html file I am outputting the content into has the macro imported into it.
```
{% from "macros/internalAnchor.html" import internalAnchor as internalAnchor %}
```
and also has the `content` variable outputted and marked to not escape (the `content` data also contains markup).
```
{{ content | safe }}
```

### Controller
The controller references the local variable content:
```
res.render('template.html', {content: content});
```

### Content
And the `content` variable contains (amongst other markup and content) the call to the macro.

```
{{ internalAnchor('2', 'interactive-mode', 'Interactive Mode') }}
```

I then get the macro rendered as text:
![screen shot 2016-07-13 at 09 57 34](https://cloud.githubusercontent.com/assets/2305016/16798029/fef7368e-48e1-11e6-88b7-19c950b02747.png)

## Current Solutions:
So I have found two options to get this macro rendered when it is inside of a local variable:
### RenderString in Controller
I can just append the call to import the macro before the `content` variable in the controller:
```
res.render('template.html', {
  content: nunjucks.renderString('{% from "macros/internalAnchor.html" import internalAnchor as internalAnchor %}' + article.content)
});
```

### RenderString with context
Or I can use something that feels a little over engineered using the context available in `.renderString` but this then `imports` the macro for every call to itself:
```
res.render('template.html', {content: nunjucks.renderString(article.content, {
  internalAnchor: function (headingLevel, id, text)) {
    const internalAnchorMacro = nunjucks.renderString(
      `{% from "macros/internalAnchor.html" import internalAnchor as internalAnchor %}
       {{ internalAnchor('${headingLevel}', '${id}', '${text}') }}`);

       return new nunjucks.runtime.SafeString(internalAnchorMacro);
   },
 })
});
```

Both of the above provide me with a working macro but both feel a little incorrect. 
Another option is to just add the macro import into the `content` variable data but then this doesn't scale and it should just be in one place as there will be many different content variables (fetched from an external source).

Is there a preferred way of doing this? I have had a look around and stepped through the code and  tried to use `env` specifically `env.renderString` in the hope that it would pick up on the macros import. But this has not helped. I have also had a good dig around in [tests/express-sample/js/nunjucks.js](https://github.com/mozilla/nunjucks/blob/e2efe904fb4d902f5ac5ee73ce1a1f3139dec075/tests/express-sample/js/nunjucks.js)

Ideally I would like to just add the `content` variable to the `template.html` and the macro just works rather than having to explicitly append or call the macro from the controller. 
Does this feel like an issue? Or is this just a misunderstanding of how to implement this functionality?

**Comment by carljm** [comment]
You seem to be looking for something like JS `eval` for nunjucks, where content strings can themselves include nunjucks tags, and nunjucks just doesn't work that way. As you've discovered, the only way to do that is with a separate call to `renderString` that renders the nunjucks tags in your content, which is then plain markup that you can dump into your main template.

So the thing that you're doing that's strange, which is making this feel hard, is trying to embed nunjucks syntax in a context variable, and then have that syntax execute -- it's not really directly related to macros or imports at all. So I'd recommend you not do that, but it's hard to give specific advice on what to do instead without more context on what you need to achieve.

**Comment by feedmypixel** [comment]
Agreed on the strange part this is a symptom of moving from static markup to placing that markup in a database. I will re-think.
Thanks for the feedback.

**Comment by ArmorDarks** [comment]
Just stumbled upon this. Maybe this information will be useful for someone who will face similar issue.

There is actually another solution to described issue. You just need to work it out the other way around. Instead of rendering context, just force-render it in place, where it used.

For this you need to register you `env` `renderString` method as Nunjucks filter. It will accept passed in context and render it in-place.

```js
env.addFilter('render', function (input) {
  return env.renderString(input, this.getVariables())
})
```

And use it within your `template.html`:

```jinja2
{% from "macros/internalAnchor.html" import internalAnchor as internalAnchor %}
{{ content|render() }}
```

This way you won't need to bother with "recreating" context within your render method, since it will use context of current template. However, beware, that this might not work with precompiled templates and slim version of Nunjucks, because it doesn't have `renderString`, thus you won't be able to refer it. Never tried it, though. But for full-fledged usage of Nunjucks, this will work.

You can see working example in Kotsu [here](https://github.com/LotusTM/Kotsu/blob/59200741893e7997ec1bb761a6fe2e0efae0f0ec/modules/nunjucks-extensions.coffee#L195).
