### ISSUE TITLE
Trying to update the docs with missing filters code.

### ISSUE THREAD

**Issue by vipickering** [mozilla/nunjucks#797]
I have written some updates to the documentation to include all the missing filters, that currently point at the Jinja docs. (you can see them [here](https://gist.github.com/vipickering/1901a0235d2e5f35126c5f13b43dd940)).

But the Jekyll site is a complete mess, with very poor documentation. Can Anyone help me make sense of it, then I'll update the Readme file along with my PR?

1. It's missing the basic setup docs. It neglects to mention you need to install Jekyll, or any dependancies. (it looks like its using bootstrap and Jquery via bower, but I can't make it work out the box).
2. the `make prod` function is broken. I get the error `make: *** [prod] Error 1`. This looks like it is trying to copy files from a folder called 'browser' which is none-existent. It also isn't clear at all why you need to run this function, so some clarity would be helpful.

3. Jekyll is being used, but all the files are coded in HTML, with apparently multiple files for each language. No Markdown at all, or shared templates. Yet they look auto-generated. Is this correct. It seems nuts.

Any help appreciated, so I can raise this PR!

**Comment by carljm** [comment]
Hi @vipickering, thanks for your interest in contributing to the docs. Sorry about the state of them -- I didn't set up this system, I wouldn't have chosen it, and I agree its a mess :-) I'd be very happy for any help in fixing it (including the possibility of porting to a completely different system; my personal choice would be Sphinx, but that's Python; I'd be open to something JS-native so we can keep all the dependencies in npm). In the short run, a PR documenting setup for building the docs would be awesome!

For me, once I `gem install` `jekyll`, `redcarpet`, and `pygments.rb`, I'm able to successfully `make` to run `jekyll --watch`and `make prod` to build the site in `docs/_site`. You say you're getting an error about a `browser` directory that doesn't exist, but it's copying the built browserfiles from `../browser`, which should be the top-level `browser/` directory in the repo, which should definitely exist (it has files in it which are git-tracked). Are you running `make prod` from the `docs/` directory?

Regarding (3), now I'm doubly suspicious that you're looking at the `_site` directory, which is the built output site. The files you want to edit are in `docs/` and are in Markdown format; see e.g. `docs/api.md` or a translation of it in `docs/fr/api.md`.

Hope that helps!

**Comment by vipickering** [comment]
@carljm thankyou. I was in the wrong branch (gh-pages). I switched to see the outputted website...and forgot to switch back. (toddler + no coffee = tired dad).

I've now got it all working.

I'll create the PR request as soon as I can.

Thanks for your help :-)
