### ISSUE TITLE
How can I convert string to variable (dynamic macro arguments names)?

### ISSUE THREAD

**Issue by d0mel** [mozilla/nunjucks#800]
Problem description:
I have ‘macro’ (called “c_cta_link”) with multiple arguments:

```
{% macro render(name='', with='', theme='', modifier='', bg='', paint='', href='#',
_link_content='', R_label_wrapper_type='', R_label_text_style='', R_label_content='', 
R_icon_modifier='', R_info_content='', R_custom_settings={}) %}

```

I need to have possibility to run this macro by passing into it either arguments **(1)** or dict of arguments **(2)**:

=================
**(1) Macro run with arguments:**

`{{ c_cta_link.render(name='compare_products', R_label_text_style='t-text-style-11') }}`

=================

**(2) Macro run with dict of arguments:**
```
{% set customSettingsDict = {
     'name': 'compare_products',
     'bg': 'u-bg-5'
} %}

{{ c_cta_link.render(R_custom_settings=customSettingsDict) }}
```
=================

I need to check if {{ c_cta_link.render() }} is run with arguments (1) or with dict of arguments (2). If it’s run with dict of arguments I need to replace macro argument value with its equivalent from dict. I could do it by checking if each argument exist in dict, and if it exists , I’ll set current argument as its equivalent from dict:

```
{% if R_custom_settings.name.length >= 1 %}			
     {% set name=R_custom_settings.name %}
% endif %}

{% if R_custom_settings.with.length >= 1 %}			
     {% set with=R_custom_settings.with %}
% endif %}

(...)


{% if R_custom_settings.R_info_content.length >= 1 %}			
     {% set R_info_content=R_custom_settings.R_info_content %}
% endif %}

```

However I don’t want to check every argument by itself, because it’s too much of redundant code.
I would like to use a loop to iterate through all arguments. In Javascript it’s possible with eval() function and it would be:

```
dynamicNames: {
        theme: null,
        modifier: null,
        bg: null,
        paint: null,
        href: null,
        R_label_wrapper_type: null,
        R_label_text_style: null,
        R_label_content: null,
        R_icon_modifier: null,
        R_info_content: null,
        initComponents: function () {
            var customDict = {
                    'bg': 'u-bg-13',
                    'paint': 'u-paint-6'
                };

            this.initRendering(customDict);
        },
        initRendering: function (R_custom_settings) {
            var helperArray = ['theme', 'modifier', 'bg', 'paint', 'href', 'R_label_wrapper_type', 'R_label_text_style', 'R_label_content', 'R_icon_modifier', 'R_info_content'];
            
            console.log('bg BEFORE: ', this.bg); // output ‘null’
            console.log('paint BEFORE: ', this.paint); // output ‘null’


            for (var i=0; i<helperArray.length ; i++) {
                for (var propertyName in R_custom_settings) {
                    if (helperArray[i] == propertyName) {
                        eval("this." + helperArray[i] + "=R_custom_settings[propertyName];");
                    }
                }
            }

            console.log('bg AFTER: ', this.bg); // output  'u-bg-13'
            console.log('paint AFTER: ', this.paint); // output 'u-paint-6'
        }
    }
```

Thanks a lot for Your help!

**Comment by carljm** [comment]
Write a JS function to do the logic and use `env.addGlobal` to make it available in your templates.

Please take usage questions to the nunjucks Google Group, not GitHub issues.

**Comment by d0mel** [comment]
Thank You very much for the answer and sorry for wrong place of my question.
