### ISSUE TITLE
Add "this" keyword to get the current context

### ISSUE THREAD

**Issue by callumlocke** [mozilla/nunjucks#809]
Handlebars lets you use `this` to access the current context.

A `this` keyword would be really useful for debugging in Nunjucks:

```nunjucks
{{ this | dump }}
```

Also:

```nunjucks
{% for key, value in this %}
  // ...
{% endfor %}
```

**Comment by ArmorDarks** [comment]
You can use `addGlobal` method of Environment to achieve same functionality.

**Comment by jbmoelker** [comment]
Duplicate of #833. Contains a [working demo](http://plnkr.co/edit/JyyLPF?p=preview).

I believe @ArmorDarks answer is sufficient. So I'm closing this issue.

**Comment by limitlessloop** [comment]
Hi, I'm  trying to replicate the example above but I get the following error when I used the above method

```bash
Cannot read property 'getVariables' of undefined
```

Any idea what I'm not doing correctly?
