### ISSUE TITLE
Error: template not found: modal.js

### ISSUE THREAD

**Issue by livemirsi** [mozilla/nunjucks#823]
Hello. I get error: "Error: template not found: modal.js"

`<script src="/js/vendor/nunjucks-slim.js"></script> `
`nunjucks.configure('/views', { 
  autoescape: true,
  web: {
    async: true
  }
});
nunjucks.render('modal.js', {}, function(err,result) {
  console.log(err);
  console.log(result);
});`
modal.js - precompiled file.
I don't undestend where I made a mistake.
If i use nunjucks.js and not compiled files then everything is working.

**Comment by devoidfury** [comment]
When using precompiled templates, load the JS file directly into the page (like you do with nunjucks) and use the original filenames.

```html
<script src="/js/templates-bundle.js"></script>
<script src="/js/vendor/nunjucks-slim.js"></script>
<script>
nunjucks.configure('', {autoescape: true});
var renderedHTML = nunjucks.render('modal.html'); // or whatever the original file was called
// do stuff with renderedHTML 
</script>
```

**Comment by livemirsi** [comment]
Thanks.
