### ISSUE TITLE
Prototype properties can't be used in templates

### ISSUE THREAD

**Issue by callumlocke** [mozilla/nunjucks#824]
When I render a template, and pass in a locals object, it seems that only properties directly assigned to the object can be rendered in the template. Properties on the object's prototype chain can't be rendered.

Is this intentional or is this a bug?

**Comment by ArmorDarks** [comment]
I'm not sure, but I have a feeling that Nunjucks makes clone of passed data, which might lead to striping of prototypes, symbols, etc. Without cloning we'd have leaked context across pages (because of JS referencing). Though, I might be wrong, it's only my assumption.

**Comment by carljm** [comment]
@ArmorDarks is correct.

**Comment by carljm** [comment]
Currently the intention is only to support passing in simple objects with explicit direct properties as context. If someone comes up with a way to lift that limitation without causing other leaked-context bugs, that would be interesting.
