### ISSUE TITLE
env.waterfall is not a function

### ISSUE THREAD

**Issue by kim3er** [mozilla/nunjucks#827]
The browser files aren't up to date on Master. Should they be? The net effect is that the NPM version of Nunjucks is out of sync with the Bower version.

**Comment by carljm** [comment]
Browser files get updated only at release time. Updating them constantly is too much maintenance headache, causes spurious merge conflicts, etc.

But that should mean that the bower version is exactly up to date with the latest npm release. It looks like for some reason the browser files on master got updated more recently than they should have been. I'll fix it.

**Comment by carljm** [comment]
Fixed in 6a6cffa3288598cbd8f03159101ec53df9dc6fe0

**Comment by kim3er** [comment]
Thanks @carljm, that's good to know.
