### ISSUE TITLE
Save reference to nunjuck env in express settings

### ISSUE THREAD

**Issue by lukechilds** [mozilla/nunjucks#828]
I'm writing some middleware for express that I want to modify the nunjuck environment. Currently (I think) I've got to manually save the nunjuck env reference for later use.

```js
const env = nunjucks.configure('views', { express: app });
app.set('nunjuckEnv', env);
```

So I can use it in some middleware:

```js
function myMiddleware(req, res, next) {
  const env = req.app.settings.nunjuckEnv;
  // Do stuff with env

  next();
}
```

It seems a bit long winded to pass a reference of my express app into nunjuck and then a reference of nunjuck into express. I think it would make more sense for the `{ express: app }` option in `nunjucks.configure` to attach itself to the express app.

Am I missing something obvious or would you accept a PR for this?

**Comment by carljm** [comment]
I don't really know much about the express integration (and I'm not really sure it belongs in nunjucks core anyway). But sure, this seems like a simple change that wouldn't break any existing use, I don't see a problem with it.

**Comment by lukechilds** [comment]
Great!

I personally think this makes sense in nunjuck core purely because you're already doing express integration in nunjuck core. May as well save the reference while you're doing it.

Do you have a preferred name? I feel like `app.settings.nunjuck` is neater but there may be some confusion as the docs refer to `nunjuck` and `env` as different things.

**Comment by carljm** [comment]
I meant that I don't really think the express integration itself belongs in nunjucks core; it could be a separate package. It was added before I became nunjucks maintainer.

**Comment by charmander** [comment]
Out of curiosity, what part of the environment are you modifying in middleware?

**Comment by lukechilds** [comment]
@charmander I was adding `req` and `res` as globals on each request so I could do things like `{{ req.query.s }}` in any template without having to manually pass `req` everywhere.

**Comment by charmander** [comment]
Can’t you do that with `res.locals`?

```javascript
app.use(function (req, res, next) {
    res.locals.req = req;
    res.locals.res = res;
    next();
});
```

**Comment by lukechilds** [comment]
Thanks, I'm not too familiar with express, I wasn't aware of `res.locals`. But yes, that makes perfect sense regarding issues with concurrent requests. Thanks for pointing it out!
