### ISSUE TITLE
Root data object

### ISSUE THREAD

**Issue by Hurtak** [mozilla/nunjucks#833]
What I am trying to do is to have little debug interface at the bottom of the page which would just take all the data passed into the templates and displayed them. Something along the lines:

```nunjucks
{% if devel %}
  <code><pre>{{ allTheData }}</pre></code>
{% endif %}
```

The problem is I don't know how to access all data points without knowing their name. Is there some kind of root object which contains all data passed into template? Or perhaps some other way to achieve this goal?

**Comment by jbmoelker** [comment]
@Hurtak I'm not aware of a "root object" exposed to the template. However, you do have access to all variables from within a filter using `this.getVariables()`. So you can use that to create a custom filter:
```javascript
env.addFilter("getVars", function(input) {
  return this.getVariables();
});
```

And use that in your template:
```html
{% if devel %}
<pre><code>{{ '' | getVars | dump }}</code></pre>
{% endif %}
```

Here's a [working demo](http://plnkr.co/edit/JyyLPF?p=preview).

Note: I don't think this is how filters are intended to be used. Should maybe be a custom function / extension. But for debugging during development it gets the job done.

**Comment by Hurtak** [comment]
@jbmoelker That seems like a good solution, thanks for help.
