### ISSUE TITLE
Set project purpose

### ISSUE THREAD

**Issue by jbmoelker** [mozilla/nunjucks#837]
I think it helps users / developers, issue reporters and maintainers if the project has a clearly defined purpose. This ensures people know what to expect from the project. They know if it's relevant to report a given issue or if it's "out of scope". And it helps maintainers to judge reported issues and PRs.

Here's my proposal:

* Aim for templating feature parity with Jinja2.
* Aim for templating feature parity with Twig, but only when not conflicting with Jinja2 parity.
* Works in Node >= v0.10 (as defined in [Travis test matrix]).(https://github.com/mozilla/nunjucks/blob/master/.travis.yml#L9).
* Works in all modern browsers (with [ES5 support](http://kangax.github.io/compat-table/es5/)).
* Works in IE8 with [es5-shim](https://github.com/es-shims/es5-shim).
* Keep footprint browser files as small as possible (save on bandwidth, download time).
* Keep performance as fast as possible (see benchmarks).
* Keep maintenance as easy as possible (avoid complexity, automate what we can).

Notes:

* We don't aim for parity of language specific syntax like Python's splice notation `{{ foo[start:end:step] }}`.
* We don't aim for parity of language specific filters like [Twig's PHP date format](http://twig.sensiolabs.org/doc/functions/date.html).

I would like to add this as a section to the [contributing guidelines](../blob/master/CONTRIBUTING.md) and / or [documentation](../blob/master/docs/). But let's first see if we can reach an agreement.

**Comment by vecmezoni** [comment]
Nice! All of your points are looking good.

> Keep footprint browser files as small as possible (save on bandwidth, download time).
This is the thing that we need to work on. Precompiled templates could be less than now without all the env.something() calls (probably need to uglify env api for precompiled templates)

**Comment by ArmorDarks** [comment]
All seems to be :+1: 

I'm not sure about Twig, though. Running for Jinja2 and Twig in same time might be too much. Besides, Twig already quite heavily deviates from Jinja2.

**Comment by kswedberg** [comment]
@ArmorDarks, I find twig and nunjucks to be largely interoperable at the moment, which is extremely helpful for the projects I'm working on. I don't think there would be any harm in attempting feature parity with twig, as @jbmoelker says, as long as his caveat is kept in mind: "*only when not conflicting with Jinja2 parity*"
