### ISSUE TITLE
Convert the variable to 2 decimals

### ISSUE THREAD

**Issue by kahwooi** [mozilla/nunjucks#839]
I am trying to render totalAmt / 100 to 2 decimal, I am hoping for 5000.30, but it is showing 5000.3:
  
 ```
    var nunjucks = require('nunjucks'); 
   
    env = nunjucks.configure();

    env.addFilter('fixed', function(num, length) {
        return num.toFixed(length || 2);
    });

    var html = env.renderString('{{ totalAmt / 100 | fixed  }}', { totalAmt: '500030' });
```

**Comment by kahwooi** [comment]
I got it fixed, I need to parenthesis around value, example:

`var html = env.renderString('{{ (totalAmt / 100) | fixed  }}', { totalAmt: '500030' });`

**Comment by vecmezoni** [comment]
Pipe (`|`) has greater priority than `/`
