### ISSUE TITLE
Make for...of loop

### ISSUE THREAD

**Issue by rightaway** [mozilla/nunjucks#841]
Because of using the new for...of over for...in in regular JavaScript/NodeJS, it should be possible to use for...of in nunjucks.

**Comment by vecmezoni** [comment]
For ...in is a part of templating language (jinja, nunjucks). If you'll look at https://github.com/mozilla/nunjucks/blob/master/src/compiler.js#L639 you'll see that for...in in template does not compile to for...in in javascript and depends on type of argument of for...in.
It should behave the same in any environment (js, python). 

For...of is javascript feature and i don't think it's a good idea to add it in to the template language.
