### ISSUE TITLE
In the latest Node docs code output is being displayed with a red rectangle.

### ISSUE THREAD

**Issue by vipickering** [mozilla/nunjucks#842]
I'll pick this up today, but keeping track here in case anyone has input.

<img width="652" alt="screen shot 2016-09-12 at 08 29 07" src="https://cloud.githubusercontent.com/assets/1380497/18427942/04d0d9d2-78c3-11e6-8dbe-886f5dc2f066.png">

This is happening because we are using "Jinja" as our code highlighting lang. We will need to switch this out for a custom one (or we could do our own!).

The quickest fix for now is to turn off the error output.

**Comment by vipickering** [comment]
Actually investigating this further, it looks like something may have gone wrong in the merge. Some of the tags are also broken.

I'll investigate and fix all the broken bits.

**Comment by vecmezoni** [comment]
Resolved with https://github.com/mozilla/nunjucks/commit/dc004cf10547301159a93aadbe0081be18bc833a
