### ISSUE TITLE
Uncaught ReferenceError: nunjucks is not defined as of 2.5.0

### ISSUE THREAD

**Issue by kswedberg** [mozilla/nunjucks#846]
Someone already posted an issue over at the [nunjucks-loader repo](https://github.com/at0g/nunjucks-loader/issues/36), but I think it might belong here instead. 

The browser/*.js files are no longer exposing the nunjucks variable: https://github.com/mozilla/nunjucks/commit/0ed30890437498493eb346220791ac314e616d1e#diff-a67bf4bfda09ce795f668e35c563550fR2

What's strange is that the 2.4.3 commit occurred just 2 minutes before 2.5.0, but it didn't exhibit the same problem.

In any case, using browser/nunjucks-slim.js, for example, now produces the error `Uncaught ReferenceError: nunjucks is not defined`, when bundled using webpack.

**Comment by kswedberg** [comment]
On second thought, this can be fixed by nunjucks-loader requiring nunjucks directly now instead of using the exports-loader. I submitted a PR there: https://github.com/at0g/nunjucks-loader/pull/37

**Comment by vecmezoni** [comment]
Actually it's exposed, but if you have `define`, `module` or `exports` it won't be set to window.nunjucks.

**Comment by vecmezoni** [comment]
Bad thing that it's broken, but now it's clearer to require nunjucks.

**Comment by kswedberg** [comment]
Right you are. Thanks for the reply.
