### ISSUE TITLE
Getting the environment (render) function inside custom tag

### ISSUE THREAD

**Issue by AlexNodex** [mozilla/nunjucks#850]
Is there a way to get the current environment inside a custom tag extension without instantiating a new environment?.

The reason I ask is because I would like my custom function to return an "include" string which I would like nunjucks to render

Currently it just outputs the "include" line - something like the following.

```javascript
function ModuleExtension() {
    this.tags = ['module'];
    this.parse = function(parser, nodes, lexer) {
        var tok = parser.nextToken();
        var args = parser.parseSignature(null, true);
        parser.advanceAfterBlockEnd(tok.value);
        return new nodes.CallExtension(this, 'run', args);
    };
    this.run = function(context, args) {
      return "{% include 'foo.html' %}"
    };
}
env.addExtension('ModuleExtension',new ModuleExtension());
```

Using

```jinja
{% module %}
```

Returns...

```jinja
{% include 'foo.html' %}
```

I would like to render "foo.html" and return its response (with args that I provide) - ideally in the current environment to save instantiating new objects for the task and more importantly retaining anything injected into the environment such as globals/filters/other extensions.

**Comment by AlexNodex** [comment]
I can render the file fine if I "renderString" and pass the environment into the Extension like so.

```
function ModuleExtension(env) {
    this.tags = ['module'];
    this.env = env;
    this.parse = function(parser, nodes, lexer) {
        var tok = parser.nextToken();
        var args = parser.parseSignature(null, true);
        parser.advanceAfterBlockEnd(tok.value);
        return new nodes.CallExtension(this, 'run', args);
    };
    this.run = function(context, args) {
      return this.env.renderString("{% include 'foo.html' %}");
    };
}
env.addExtension('ModuleExtension',new ModuleExtension(env));
```

Is this likely the only way I'm going to be able to achieve what I am after?

**Comment by vecmezoni** [comment]
First argument of this.run will be environment

**Comment by AlexNodex** [comment]
The first argument is the context, that was the first thing I tried !

**Comment by vecmezoni** [comment]
context.env would be the thing you want

**Comment by AlexNodex** [comment]
Ah right, that makes sense ! . Does it have a safe string method attached to it so I can output responses from macros etc ?

**Comment by vecmezoni** [comment]
Probably you should wrap return value with ```nunjucks.runtime.SafeString()```

**Comment by AlexNodex** [comment]
Unfortunately the extension is inside a require / module.exports and I don't have access to the nunjucks object. Is there not a way I can obtain it from the context?

**Comment by vecmezoni** [comment]
Then where do you get nodes.CallExtension?

**Comment by AlexNodex** [comment]
I can only assume it's called by nunjucks when it goes through the contracts of the extension.

If I console.log(nunjucks) anywhere in the extension it doesn't exist.

**Comment by vecmezoni** [comment]
looks like there is no way to get SafeString from elsewhere but nunjucks.runtime

**Comment by AlexNodex** [comment]
I've now injected it right into the template but for some reason it's not working.

Here is the example

```
// index.js
var template=new nunjucks.Environment([new nunjucks.FileSystemLoader('views')]);
template.runtime=nunjucks.runtime;
console.log(template.runtime);
// logs various functions including SafeString..
var extensions = require('./includes/extensions.js')(template);
```
```
// includes/extensions.js


```
function ModuleExtension() {
    this.tags = ['module'];
    this.parse = function(parser, nodes, lexer) {
        var tok = parser.nextToken();
        var args = parser.parseSignature(null, true);
        parser.advanceAfterBlockEnd(tok.value);
        return new nodes.CallExtension(this, 'run', args);
    };

    this.run = function(context, args) {
        var $module=args.id;
        var $view=args.view;
        var $controller=args.controller;
        console.log(context.env.runtime);
        // logs as above - a load of functions including SafeString //
        // context.env.renderString("{% include 'foo.html' %}")
        var $output=context.env.runtime.SafeString('WHat?');
        console.log($output); // undefined ....
        return $output;
    };
}
module.exports = function(env) {
    env.addExtension('ModuleExtension', new ModuleExtension(env));
};
```

**Comment by AlexNodex** [comment]
I worked out the issue, for some reason it needed  to be

`var $output=new context.env.runtime.SafeString('WHat?');`

(new) object. I can't work out why but I'm not all that good with javascript so that's probably why!

Thanks for all the help, much appreciated
