### ISSUE TITLE
support filter in if condition?

### ISSUE THREAD

**Issue by brucejcw** [mozilla/nunjucks#856]
Does `nunjucks` support using filter in if confition? I didn't find doc about this...  
For example: using [trim](https://mozilla.github.io/nunjucks/templating.html#trim) in `if`, see my fake code:
```
{% if trim(name) == "" %}
```  
Is there a way to support using [trim](https://mozilla.github.io/nunjucks/templating.html#trim) here?

**Comment by vecmezoni** [comment]
```jinja
{% if name | trim == "" %}
```
