### ISSUE TITLE
basic help needed

### ISSUE THREAD

**Issue by eurakilon** [mozilla/nunjucks#862]
I'm probably missing something, but I can't figure out the way to use nunjucks-slim.js
- [x] created the template `/src/views/test.html`
- [x] cmd line → `nunjucks-precompile src/views > src/template.js`
- [x] /index.html →
  - [x] `<script type="text/javascript" src="/js/nunjucks-slim.min.js"></script>`
  - [x] `<script type="text/javascript" src="/src/template.js"></script>`
  - [x] `<script type="text/javascript" src="/js/script.perso.js"></script>`
- [x] /js/script.perso.js →
  - [x] `var env = new nunjucks.configure('/src/views');`
  - [x] `$('#foo').html(env.render('test.html'));`

Result → `Uncaught Error: template not found: test.html`

**Comment by vecmezoni** [comment]
If you'll swap nunjucks-slim and template everything will work, i think.
This is how precompiled loader works: https://github.com/mozilla/nunjucks/blob/0c3a03b94f77d8e5f65852a720d709f4abaeaec6/src/environment.js#L67

**Comment by eurakilon** [comment]
You mean that instead of `<script src="/js/nunjucks-slim.js"><script src="/js/template.js">` I should write `<script src="/js/template.js"><script src="/js/nunjucks-slim.js">`? Because I still get the same error :/

**Comment by jbmoelker** [comment]
@eurakilon can you put your code on a code Playground like [Plunker](http://plnkr.co/) so we can have a look at what's going wrong?

And are you correctly sourcing `template.js`? Your `nunjucks-precompile` outputs to `src/` while your last comment tries to include from `js/`.

**Comment by eurakilon** [comment]
yep, I put `/js/`, that was a typo, I should have written `/src/`, but it's still not working.

My question is more about "Getting started with nunjucks-slim.min.js". I couldn't find any example anywhere on the Documentation neither on internet of people using this file, so I come here to ask to the developers an exemple for basic use of nunjucks-slim

**Comment by eurakilon** [comment]
(I'm sure the problem is more about lack of information than presence of bug in the code)

**Comment by eurakilon** [comment]
@jbmoelker Is what I have done at least what I'm supposed to do to make nunjucks-slim working?

@vecmezoni When you said `This is how precompiler work` ... I didn't get how it works, could explain more?

**Comment by jbmoelker** [comment]
I agree, we can do better on the documentation. I personally don't have any experience using `nunjucks-slim`. And I don't see any test coverage for `nunjucks-slim` either. Unless you are able to put up some of your code somewhere, I find it hard to help you out.

**Comment by revelt** [comment]
@eurakilon hi! Looks like this ticket got stale. Would you feel OK to close? If not, please round up the missing bits that need answered and we'll get this rolling again. 👍
