### ISSUE TITLE
Expressions and math section is duplicated in the template docs

### ISSUE THREAD

**Issue by JesseE** [mozilla/nunjucks#869]
- Apparently there was a merge conflict which duplicated the expressions and math section of the template docs.

- I assign myself to this task

**Comment by jbmoelker** [comment]
Problem is visible just below ["Comparisons" section](https://mozilla.github.io/nunjucks/templating.html#comparisons):
<img width="514" alt="screen shot 2016-09-20 at 15 25 46" src="https://cloud.githubusercontent.com/assets/1516059/18672027/a733a5ea-7f46-11e6-922a-e914801eea96.png">
