### ISSUE TITLE
array style property accessor not working 

### ISSUE THREAD

**Issue by cesarvarela** [mozilla/nunjucks#876]
With this json:
```
  texts: {
        en:  
        {
          whatever: 'heheheh'
        },
        es: {
          whatever: 'jejejejej'
        } 
      }
```

I want too have this global variable at the top of muy index.njk
```
{% set lang = 'en' %}
```

And then do:
```
{{ texts[lang].whatever }}
```

But it isn't working. Of course `{{ texts['en'].whatever }}` does work.

**Comment by jbmoelker** [comment]
I can't replicate this issue. Here's a [live working example](http://plnkr.co/edit/amTzK5?p=preview).

I hope this helps. If you need more help, please file a new issue with a live example or link to code repository.
