### ISSUE TITLE
Strict comparison (`===`) has unexpected results with `none`.

### ISSUE THREAD

**Issue by jgerigmeyer** [mozilla/nunjucks#879]
When a macro argument has a default value of `none`, strict comparisons of the argument value within that macro has unexpected results:

```
{% macro test(foo=none) %}
  {{ foo == none }} // true
  {{ foo === none }} // false
  {{ foo == null }} // true
  {{ foo === null }} // true
{% endmacro %}

{{ test() }}
{{ test(foo=none) }}
```

See the following jsfiddle: http://jsfiddle.net/jgerigmeyer/34sporyy/1/

**Comment by lazopm** [comment]
I think it's supposed to be `None` like in python

**Comment by jgerigmeyer** [comment]
Really? That strikes me as odd, given the note at http://jinja.pocoo.org/docs/dev/templates/#literals

**Comment by jgerigmeyer** [comment]
This appears to be working in v3.2.0.
