### ISSUE TITLE
Defining global macros

### ISSUE THREAD

**Issue by go-oleg** [mozilla/nunjucks#88]
Been playing around with Nunjucks and the `macro` feature.  Is it possible to define a global `macro` (similar to how its possible to define a global `filter`) that would be accessible in all templates without having to do an explicit `import` of the template containing the `macro`?

And of course, thanks for Nunjucks...the documentation is super easy to follow and I was able to get my environment set up and render templates in no time :-).

**Comment by robvdl** [comment]
A bit confusing to call this macros, since nunjucks is supposed to be heavily insired by jinja2 I would have expected it to do jinja2-style macros as well, not something different.
