### ISSUE TITLE
Include by variable 

### ISSUE THREAD

**Issue by shaunpatterson** [mozilla/nunjucks#898]
Is it possible to include by a variable?

```
{% set temp = "header.j2" %}
{% include temp %}
```

I've done some basic tests using compiled templates (I'm using webpack and nunjucks-loader) the code above breaks.  However, if I change it to

```
{% include 'header.j2' %}
{% set temp = "header.j2" %}
{% include temp %}
```

they both work because 

`dependencies["./header.j2"] = __webpack_require__( 6 );`

has been added to the template.  Is there a way to fake this out or specifically mark a file as a dependency?

**Comment by valtido** [comment]
Not tested this, but a possible HACK is that you can simply append a string to it.

`{% include temp + "" %}` 

also it is a lot better and advisable to use, `{% include temp + ".j2" %}` just as a precaution security wise.

**Comment by revelt** [comment]
@shaunpatterson should we keep this issue open or would you feel ok to close it?

**Comment by shaunpatterson** [comment]
Close.
