### ISSUE TITLE
Jinja2 with context

### ISSUE THREAD

**Issue by srossross** [mozilla/nunjucks#90]
I have a project that I want to use templates for both flask and an expressjs. 

Currently I have an  `{% include "foo.html" with context%}` statement which works in flask.

What is the best way to write this to work for both?

**Comment by ArmorDarks** [comment]
This also should work for `{% import "index.nj" as ...`, but it doesn't

Example: http://jinja.pocoo.org/docs/dev/templates/#import-context-behavior

Is they any chances that there will be updates regarding this?

Thanks!
