### ISSUE TITLE
Calling builtin (include) extensions dynamically.

### ISSUE THREAD

**Issue by thetutlage** [mozilla/nunjucks#911]
I have situation where I want to call include dynamically from an extension or a global. I did my best to read the source code and browse the existing issues but no luck.

## Situation
Let's say (for the sake of simplicity) I have an extension called `each` which can include a template inline instead of calling `for` and then include inside it.

```twig
{% each users, 'user', 'user.njk' %}
```

Which is equivalent to

```twig
{%for user in users %}
  {% include 'user.njk' %}
{% endfor %}
```

Inside my extension I am doing

```javascript
function CompactEach () {
	this.tags = ['each']
	this.parse = function (parser, nodes) {
           const tok = parser.nextToken()
	    const args = parser.parseSignature(null, true)
	    parser.advanceAfterBlockEnd(tok.value)
	    return new nodes.CallExtension(this, 'run', args)
	}
	this.run = function (context, args, toVar, template) {
             // stuck
	}
}
```

I am stuck on how to call `include` inside the `run` function.

**Note**: I agree this is just a good to have feature since it does not limit the user. But this is just a simple use case of **calling inbuilt extensions/parsers dynamically** and doing so can open a whole new world of extending nunjucks.

Thanks 😄

**Comment by ArmorDarks** [comment]
So, did you figure it out?

**Comment by thetutlage** [comment]
Nope I created http://edge.adonisjs.com , focused on simpler developer API
