### ISSUE TITLE
Set blocks prints its content

### ISSUE THREAD

**Issue by ArmorDarks** [mozilla/nunjucks#914]
In 3.0.0 set block for some reason immediately prints it content.

``` jinja2
{% set test %}
TEST
{% endset %}

result: {{ test }}
```

outputs

``` html
TEST

result:
```

As you can see, set print itself immediately, and `{{ test }}` call doesn't work.

Should it be like that?

**Comment by atheros** [comment]
I was trying to use {% set %} as a walkaround the bug #679, so I wouldn't have to use call that breaks variable context. It seems set block doesn't work in macros. As noted above, content is displayed and variable is empty.

At top level, {% set %} block works as expected.

**Comment by noahlange** [comment]
Temporary workaround: overwrite the `compileCapture` function in `compiler.js` with the following.

```javascript
compileCapture: function(node, frame) {
        // we need to temporarily override the current buffer id as 'output'
        // so the set block writes to the capture output instead of the buffer
        var oldbuf = this.buffer;
        this.buffer = 'output';
        this.emitLine('(function() {');
        this.emitLine('var output = "";');
        this.withScopedSyntax(function () {
            this.compile(node.body, frame);
        });
        this.emitLine('return output;');
        this.emitLine('})()');
        // and of course, revert back to the old buffer id
        this.buffer = oldbuf;
    }
```

PR incoming.
