### ISSUE TITLE
{% raw %} doesn't work as expected

### ISSUE THREAD

**Issue by ciases** [mozilla/nunjucks#923]
Hello there!
I'm trying to escape content for `<pre><code>` tags. Here is my test string:
```html
{% raw %}
<span>try</span>
"\n\s" _'print' "this"
{% endraw %}
```
I got only `try "\n\s" _'print' "this"` without `span` tag. How can I get all content escaped? I tried `{{` and `escape`, `safe` builtin filters but without success.
Any suggestions? Thanks.

**Comment by devoidfury** [comment]
`{% raw %}` is only for escaping nunjucks-engine-specific things, like  `{{ variable }}`, `{% blocktag %}`, `{# comment #}`.

Try using a filter block:

```jinja
{% filter escape %}
<span>try</span>
"\n\s" _'print' "this"
{% endfilter %}
```

**Comment by ciases** [comment]
Cool! Thanks!
I guess this example of using `filter` should be in documentation.

**Comment by devoidfury** [comment]
It is in the docs, here: http://mozilla.github.io/nunjucks/templating.html#filter
