### ISSUE TITLE
Unable to Filter an include inside a macro

### ISSUE THREAD

**Issue by damienwebdev** [mozilla/nunjucks#926]
I'm attempting to do something similar to...
```twig
{% macro codeblock() %}
   <h4>Example Code</h4>
   {% filter escape%} {% include 'mytemplate.html' %} {% endfilter %}
{% endmacro %}
```

Which returns an empty string from the filter and results with something like...

```twig
   <h4>Example Code</h4>
```

If I try to do...

```twig
{% macro codeblock() %}
   <h4>Example Code</h4>
  {% include 'mytemplate.html' %}
{% endmacro %}
```

I get my unescaped content back from the include like.

```twig
   <h4>Example Code</h4>
   <div class="mytemplate">My Template</div>
```

Ideally, the macro would doing something similar to...

```twig
   <h4>Example Code</h4>
   &lt;div class=&quot;mytemplate&quot;&gt;My Template&lt;/div&gt;
```

 I'm using v3.0.0. I see there's a test for `should compile macros with args that can be passed to filters` but I'm not sure if this is a compiler issue with the composition of these two functions or if I'm doing something dumb.

If it would be helpful, I can submit the use case as a unit test, but I'm not sure whether to put it into the compiler or somewhere else as it spans multiple levels.

Cheers!

**Comment by damienwebdev** [comment]
Closing this as it seems no one cares.

**Comment by zachleat** [comment]
Aww, leave it open! I sub’d here.
