### ISSUE TITLE
How to access part of a list?

### ISSUE THREAD

**Issue by jonashao** [mozilla/nunjucks#929]
in jinja2, we can access part of a list by:
`{% for post in site.posts | list[0:4] %}`
or
`{% for post in site.posts[0:4] %}`

but nunjucks seems not provided these filters,

`splice` can devide a list into serveral parts, but if I only need first n elements, how to do?

**Comment by ricordisamoa** [comment]
It seems that the new maintainer doesn't think that Python's splice notation is within the project's scope (#851)

**Comment by zetareticoli** [comment]
Any update about that?

**Comment by ArmorDarks** [comment]
https://github.com/mozilla/nunjucks/pull/976

**Comment by zetareticoli** [comment]
Cool. When a new release is planned?

**Comment by krassowski** [comment]
@zetareticoli and anyone concerned: it was released on 24th of May! :)
@jonashao it seems that this issue could be closed.

**Comment by fdintino** [comment]
Thanks @krassowski . Fixed with #976

**Comment by zetareticoli** [comment]
Not found any documentation on how to use it.

Please, link=

**Comment by fdintino** [comment]
@zetareticoli: [documentation here](https://mozilla.github.io/nunjucks/api.html#installjinjacompat). Call that function and you'll be able to use it in your templates the same as you would with jinja2.
