### ISSUE TITLE
Printing an object

### ISSUE THREAD

**Issue by dhendo** [mozilla/nunjucks#94]
Currently, if I output an object using nunjucks, I get  "[object Object]":

Nunjucks:
context: {myObj: {}}
template: {{ myObj }}
output:  "[object Object]"

Jinja:
context: {myObj: {}}
template: {{ myObj }}
output:  "{}"

Is this desired behaviour for people? If people are interested, I can look into creating a patch to better mimic the Jinja functionality. (Possibly just dump the output from JSON.stringify)

More than anything else, this could be useful for debugging.

**Comment by alexbeletsky** [comment]
I'll be happy if nunjucks provide some ability to act as Jinja (as @dhendo mentioned above). Maybe have a special tag, just idea

```
context: {myObj: {}}
template: {{% myObj %}}
output: "{}"
```

**Comment by garygreen** [comment]
I've always just added a global `dump()` function to nunjucks which does `console.log` -- use in the views like `{{ dump(somevar) }}` which outputs to the console whatever that var is. Alternative is to just actually check what your outputting in your controller. Benefit is that I then I have the all the chrome tools at my disposable.

I'm also not convinced nunjucks needs to do anything more with this like jsonifying, that seems to be going too far. It's more of a development issue imo, which is easily solved by a custom `dump` or similar method.

**Comment by alexbeletsky** [comment]
Which version it's added to? I'm using `"nunjucks": "^1.2.0"` seems not to be there.

**Comment by jlongster** [comment]
@alexbeletsky `dump` was a custom function he added. I just added at as a builtin filter, so you can do `{{ foo | dump }}` now and it just calls `JSON.stringify`

**Comment by LordWingZero** [comment]
For anyone else stumbling upon this issue, chances are youre trying to send JSON out to the view so you can use it in client side Javascript.

## Router
```Javascript
return res.render('login', {
    title: 'Login',
    validationErrors: JSON.stringify(err.validationErrors)
});
```

## View
```Html
<script type="text/javascript">
  console.log({{ validationErrors | safe  }});
</script>
```

**Comment by mattbasta** [comment]
You should avoid marking JSON output as |safe, since it can still contain a string with a closing script tag.

**Comment by LordWingZero** [comment]
What's the alternatives? Everything else escapes and gives me &quot; also my JSON is not user created so it will never have malicious data in it.

**Comment by CaptEmulation** [comment]
here is the filter I use to escape double quotes in JSON (dependency on lodash):
```
nunjucksEnv.addFilter('json', function JSONstringify(obj) {
  function objectToSafeStrings(_obj) {
    return _.mapValues(_obj, value => {
      if (_.isObject(value)) {
        return objectToSafeStrings(value);
      } else if (_.isString(value)) {
        return value.replace(/\"/g, '\\"');
      }
      return value;
    });
  }
  return JSON.stringify(objectToSafeStrings(obj));
});
```

**Comment by CaptEmulation** [comment]
It appears this issue has been resolved in nunjucks v3.0.0-dev2 when using the built-in filter `dump`

**Comment by Kevinlearynet** [comment]
I prefer this, which is tabified:

```
// json formatting
nunjucksEnv.addFilter( 'json', function ( obj ) {
	var json = JSON.stringify( obj, null, '\t' );

	return new Nunjucks.runtime.SafeString( json );
} );
```

**Comment by fred66sp** [comment]
Is very simple:

{{ data.products | dump | safe }}

**Comment by salemhilal** [comment]
I hate to drag up an old issue, but I ran into trouble with `dump` when trying to dump all the data in a Post object because a handful of properties contain circular references. Would you be open to a PR that uses `util.inspect` instead? I'm not sure about the best way to handle [the `spaces` argument](https://github.com/mozilla/nunjucks/blob/master/nunjucks/src/filters.js#L128) in a non-breaking way, but one option could be to fall back to `util.inspect` if `JSON.stringify()` throws an exception.

**Comment by stephane-klein** [comment]
With Eleventy I use https://github.com/11ty/eleventy/issues/266#issuecomment-716176366

**Comment by murtuzaalisurti** [comment]
> With Eleventy I use [11ty/eleventy#266 (comment)](https://github.com/11ty/eleventy/issues/266#issuecomment-716176366)

Thanks!
