### ISSUE TITLE
nunjucks.render adds "s="+ timestamp to URL, causing issue in caching nunjucks files

### ISSUE THREAD

**Issue by sudhirbeldar** [mozilla/nunjucks#941]
Hello team, I have started using nunjucks and finding it great for development. 

Now I reach to level where my application needs to cache nunjucks files. But I am not able to do so as everytime I am rendering nunjucks file, Nunjucks.js is adding "s="+ timestamp as shown below

url += (url.indexOf('?') === -1 ? '?' : '&') + 's=' +
	               (new Date().getTime());

So everytime , url is different. Can anyone let me know the reason of doing so. And how can I cache my nunjucks files?

**Comment by devoidfury** [comment]
It's suggested that you use precompiled templates instead of the web-loader outside of development.
Relevant section in the docs: https://mozilla.github.io/nunjucks/api.html#recommended-setups

**Comment by sudhirbeldar** [comment]
Thank you very much @devoidfury.  I will try this suggestion.

**Comment by thomaspessato** [comment]
Is this solved? I'm having the same issue, and if there's a solution for this, can someone share it? :)

**Comment by ArmorDarks** [comment]
@thomaspessato 

As @devoidfury suggested, you'd better use precompiled templates for client-side, then you won't have this issue at first place.

**Comment by fdintino** [comment]
You can disable the cache by passing `{useCache: true}` to the web loader:

```javascript
var env = new nunjucks.Environment(new nunjucks.WebLoader({useCache: true})
```

**Comment by PreethiSagana** [comment]
Is there a working solution for this? I'm having the same issue. I need to cache nunjucks files in browser for offline data

**Comment by tomkennedy22** [comment]
A hacky solution I found - I have the nunjucks.js file downloaded and serve myself, so edited nunjucks.min.js to remove this functionality. There's a line like this - 

```(t += (-1 === t.indexOf("?") ? "?" : "&") + "s=" + new Date().getTime()),```

That I simply commented out to resolve this issue.
