### ISSUE TITLE
templating document in Chinese shows incorrectly

### ISSUE THREAD

**Issue by initialdmg** [mozilla/nunjucks#956]
in the website, the page tranformed from the markdown file has something wrong. In the html, every tag of "h1" and "h2" has an id attribute, but has only one quotation mark after the '=' , result in the wrong style of webpage. it might be the markdown plugin's bug.

**Comment by gaolinfeng** [comment]
#866

**Comment by initialdmg** [comment]
fixed in Feb 2017
