### ISSUE TITLE
locals in browser side

### ISSUE THREAD

**Issue by bonesoul** [mozilla/nunjucks#959]
I'm including locals in my project using;

`  app.locals.moment = require('moment'); // setup moment.js as local so we can use it templates.`

Then in my templates i can use it as;

`<span class="text-muted heading-text" data-popup="tooltip" data-placement="bottom" data-original-title="{{ moment(review.createdAt).locale('tr').format('LLL') }}">{{ moment(review.createdAt).locale('tr').fromNow() }}</span>`

but i'm also using same template in browser side but getting errors as moment is not defined.

```
 Error: Unable to call `moment`, which is undefined or falsey
    at Object.t.prettifyError (nunjucks.min.js:2)
    at nunjucks.min.js:2
    at h.root [as rootRenderFunc] (eval at _compile (nunjucks.min.js:2), <anonymous>:104:3)
    at h.render (nunjucks.min.js:2)
    at nunjucks.min.js:2
    at f (nunjucks.min.js:2)
    at a (nunjucks.min.js:2)
    at nunjucks.min.js:2
    at i (nunjucks.min.js:2)
    at Object.t.asyncIter (nunjucks.min.js:2)
t.prettifyError @ nunjucks.min.js:2
(anonymous) @ nunjucks.min.js:2
root @ VM5770:104
render @ nunjucks.min.js:2
(anonymous) @ nunjucks.min.js:2
f @ nunjucks.min.js:2
a @ nunjucks.min.js:2
(anonymous) @ nunjucks.min.js:2
i @ nunjucks.min.js:2
t.asyncIter @ nunjucks.min.js:2
getTemplate @ nunjucks.min.js:2
render @ nunjucks.min.js:2
e.exports.render @ nunjucks.min.js:2
success @ moderation.js:31
i @ jquery.min.js:2
fireWith @ jquery.min.js:2
z @ jquery.min.js:4
(anonymous) @ jquery.min.js:4
```

How can i set same locals for browser side?

**Comment by ArmorDarks** [comment]
You need to add it as part of Nunjucks environment configuration, via [addGlobal](https://mozilla.github.io/nunjucks/api.html#addglobal) method.

**Comment by bonesoul** [comment]
thanks!
