### ISSUE TITLE
Using Nunjucks in Flask application - including HTML

### ISSUE THREAD

**Issue by aditp91** [mozilla/nunjucks#960]
Hi please view my question here:
http://stackoverflow.com/questions/42471204/using-nunjucks-in-flask-app-trying-to-include-html

Any thoughts or suggestions would be nice! thanks

**Comment by gpestana** [comment]
@aditp91 I tried to answer your question in stackoverflow. It does not seem a problem related to Nunjucks. It might even be a typo.

**Comment by aditp91** [comment]
Thank you @gpestana
