### ISSUE TITLE
Overriding parent variables from child

### ISSUE THREAD

**Issue by martixy** [mozilla/nunjucks#961]
Right now, due to the way inheritance is done, it works the other way around. That is, the parent overrides the child variable.

Wouldn't it make more sense for it to be the other way around?

So for example
base:
```TWIG
{% set background = '#333' %}
<!DOCTYPE html>
<html>
<body bgcolor="{{ background }}">
{% block body%}{% endblock %}
</body>
</html>
```
Child:
```TWIG
{% extends 'base.nj' %}

{% set background = '#fff' %}

{% block body %}
Content things
{% endblock %}
```
The current result is a gray screen.
If you want to actually make this work, in every parent you have to explicitly check for the existence of your variable before setting it.

**Comment by ArmorDarks** [comment]
Hi

See https://github.com/mozilla/nunjucks/issues/406

**Comment by martixy** [comment]
I don't actually see an answer to my question there. Just a confirmation of why you get the result you get / how inheritance works(i.e. parent gets procced last, so it's value takes precedence).

**Comment by ArmorDarks** [comment]
It is just how Jinja2 and Nunjucks inheritance works. There nothing can be done with it.

In #406 you can find few recommendations how to deal with it. I do not think that there will be any changes regarding this.

If you have a good proposal how to improve this behavior, you should post it to Jinja2 repository first, and it should be adopted by Jinja2 community. Only then there will be chances that maintainer will also add it to Nunjucks.

**Comment by ArmorDarks** [comment]
I think that issue could be closed.
