### ISSUE TITLE
Feature request: Add switch statement

### ISSUE THREAD

**Issue by magicspon** [mozilla/nunjucks#967]
Hello,

It would be great if there was a `{% switch %}` statement in nunjucks

Something like the following:

```
{% switch someVar %}
  {% case 'value1' %}
   ...
  {% case 'value2' %}
   ...
  {% case 'value3' %}
   ...
  {% default %}
   ...
{% endswitch %}
```

I'm relatively new to nunjucks so i'm not sure of the complexities involved in adding something like this.  I saw this: https://mozilla.github.io/nunjucks/api.html#custom-tags, but it's a little bit beyond me! 

Cheers

**Comment by bewards** [comment]
is there any way to use an `or` conditional operator within a switch? That doesn't seem to work nor does the following:
```
{% switch contentType %}
      {% case 'webinar' %}
      {% case 'past-webinar' %}
```

**Comment by luwes** [comment]
@bewards make sure there is no whitespace in between case tags, I had the same issue.
https://github.com/mozilla/nunjucks/pull/1034/files#diff-44aa9f4dcb77c0625e108f0ccec0a2aaR125
