### ISSUE TITLE
Can't use "nunjucks.compile" with custom filters

### ISSUE THREAD

**Issue by andreibancioiu** [mozilla/nunjucks#977]
I am unsure whether this is a bug or expected behavior: `nunjucks.compile` fails when the template string uses a custom filter.

Any thoughts on this?

```
var templateString = '{{ price }}';
var templateStringMoney = '{{ price | money }}';

var env = nunjucks.configure({ autoescape: true });

env.addFilter('money', function(str) {
    return '$' + str + '.00';
});

// Works
var compiledTemplate = nunjucks.compile(templateString);
alert(compiledTemplate.render({ price: 100 }));

// Fails: "filter not found: money"
var compiledTemplateMoney = nunjucks.compile(templateStringMoney);
alert(compiledTemplateMoney.render({ price: 100 }));
```

**Comment by ArmorDarks** [comment]
Do you notice, that you've configured `env`, but using plain `nunjucks` to compile instead? `nunjucks.compile` itself knows nothing about your configured environment, you need to provide it:

```js
nunjucks.compile(templateStringMoney, env)
```

See https://mozilla.github.io/nunjucks/api.html#compile

**Comment by andreibancioiu** [comment]
@ArmorDarks thank you!

I somehow assumed that `compile` reuses the "default" environment, just like `renderString` and others:

```
// Works
alert(nunjucks.renderString('{{ price | money }}', { price: 200 }));
```
