### ISSUE TITLE
How is SafeString supposed to work?

### ISSUE THREAD

**Issue by callumlocke** [mozilla/nunjucks#979]
I can't find docs on SafeString.

I'm returning a `SafeString` from a custom filter, but it has no effect – the result has encoded `<` as `&lt;`, etc.

The `| safe` filter works fine, but my own custom filters that return a `SafeString` do not.

**Comment by callumlocke** [comment]
Realised the problem. Closing in favour of #980

**Comment by niftylettuce** [comment]
@callahad I believe this to be an issue with v2 to v3 - this only occurred in v3 onwards.
