### ISSUE TITLE
Detect if offline when calling render()

### ISSUE THREAD

**Issue by thomaspessato** [mozilla/nunjucks#982]
I tried to render a template in offline mode, but 'render' method keeps putting a query string to force disable cache and to make a request. What if we wanted to consider offline navigation?

[This is the piece of code](https://github.com/mozilla/nunjucks/blob/737e4e005cd2a62f1d9e7cd4552b76b21d368930/browser/nunjucks.js#L6069) that forces ignore cache.

That doesn't make sense when offline. What about we leave this 'forced' query string aside when offline?

Something like:
```javascript
if(navigator.onLine) {
            url += (url.indexOf('?') === -1 ? '?' : '&') + 's=' +
                   (new Date().getTime());
}
```

Sorry if this is something that has already been solved, but I didn't find anything that could help with this question until now.

**Comment by ArmorDarks** [comment]
What exactly do you mean under offline mode?

You can also use precompiled templates, they won't have such behavior with timestamps.

**Comment by thomaspessato** [comment]
@ArmorDarks,
I'm building a PWA that goes offline with all it's templates. 

Considering that, I don't want to call render with 'timestamp' in it. It just forces a request (passing by the service worker). But when I'm offline, I can't see any reason to 'force' that request (since I have no connection). 

Don't know if I was clear enough...

I tried several parameters, like 'useCache: true' and a couple of other combinations, but with no success. So I was thinking if this is something that haven't been done yet.

I used that piece of code that I wrote and it worked (in Chrome and Firefox, don't know about the other browsers).


So to give a point to the discussion: I was thinking if the render() method could consider that the client is offline so that it doesn't use an querystring.

**Comment by ArmorDarks** [comment]
Did you try precompiled templates? In most cases it's what you want to use for client-side, and it should fix your issue, because all templates will be always loaded in memory, and whenever you will call `render`, it will try to load it from memory first, thus Nunjucks won't need to make new request.

Alternatively you can use `renderString` instead and orchestrate loading of your templates on your own.

**Comment by ArmorDarks** [comment]
And of course, you can write your own loader, which will accommodate needed behavior. See [lodaders docs](http://mozilla.github.io/nunjucks/api.html#loader)

**Comment by thomaspessato** [comment]
Thanks @ArmorDarks , I'll try this and see if covers my case for the PWA. If not, I'll comment on this issue again 😃

**Comment by zomars** [comment]
Any luck with this @thomaspessato ?
