### ISSUE TITLE
Volunteering The Atlantic to pick up maintenance

### ISSUE THREAD

**Issue by fdintino** [mozilla/nunjucks#985]
@vecmezoni If you haven't had any volunteers yet, the developers at The Atlantic would be willing to take on maintenance responsibilities.

**Comment by vecmezoni** [comment]
No one volunteered yet. 
Will it be you or any other developers of The Atlantic?

**Comment by fdintino** [comment]
It would be me, @pkafei, @joshmaker, @whatisjasongoldstein, @defbyte, @kjmahoney, and @jeremy-green

**Comment by fdintino** [comment]
If you would prefer fewer administrators then I along with @jeremy-green and @joshwest are the team leads.

**Comment by vecmezoni** [comment]
Ok, i need to approve this decision with at least one former maintainers:
@carljm, @jlongster, @jbmoelker could you please drop a line if you agree with this decision.

If no one will answer i will add you as a project admin and you'll decide whom to give admin access.

**Comment by carljm** [comment]
Seems fine to me. Thanks, The Atlantic!

**Comment by vecmezoni** [comment]
@fdintino, i've added you as an admin.

**Comment by vecmezoni** [comment]
Please update contribution guide and repository description. Feel free to ask me if you need any information or help.

**Comment by ArmorDarks** [comment]
Nice to see that someone picked up the project. Thanks and good luck guys!

**Comment by ArmorDarks** [comment]
Hi.

Are there any plans to do something with Nunjucks? :)
