### ISSUE TITLE
Context is emtpy

### ISSUE THREAD

**Issue by mjaros** [mozilla/nunjucks#987]
I am trying to get the file path of a template in a global function and was thinking about using the context. But it seems to be an empty object in this example:

```js
const nunjucks = require('nunjucks');

const env = new nunjucks.Environment(new nunjucks.FileSystemLoader());

env.addGlobal('getContext', () => {
  return JSON.stringify(this);
});

env.renderString('{{ getContext() }}', (err, res) => {
  if (err) console.error(err);
  console.log(res);
});
```

My impression was that the context should be available on `this`.

**Comment by ArmorDarks** [comment]
Context indeed available, under `this` as `this.ctx`.

However, you're using arrow function. Arrow functions do not change `this`.

In other words:

```js
env.addGlobal('getContext', function () {
  return JSON.stringify(this); // or `this.ctx` or `this.getVariables()`, depending on what you want
});
```

**Comment by fdintino** [comment]
More specifically, arrow functions set `this` inside the function to be whatever `this` is in the scope where the function is declared. Because the arrow function is being used in what appears to be a module, `this` is undefined.

**Comment by mjaros** [comment]
Ah, my mistake, didn't think about the arrow function there.

However, when using it properly, `this.ctx` is still an empty object:

```js
const nunjucks = require('nunjucks');

const env = new nunjucks.Environment(new nunjucks.FileSystemLoader());

env.addGlobal('getContext', function() {
  return JSON.stringify(this.ctx);
});

env.renderString('{{ getContext() }}', (err, res) => {
  if (err) console.error(err);
  console.log(res);
});
```

**Comment by fdintino** [comment]
@mjaros I would assume that context is an empty object there because you aren't passing in any context. If you were to change the last function call to the following, it should work:

```javascript
env.renderString('{{ getContext() }}', {foo: 'bar'}, (err, res) => {
  if (err) console.error(err);
  console.log(res);
});
```

**Comment by mjaros** [comment]
@fdintino Thanks for the clarification. I was assuming the context was already pre-filled with more values I could somehow use to get the path of the template. Maybe see #988 for what I am trying to do.
