### ISSUE TITLE
How do randonmize for cycle array?

### ISSUE THREAD

**Issue by zetareticoli** [mozilla/nunjucks#989]
I have an array of items and want to print it out in a random order using `for`

Tried doing something like
`{% for story in stories | random %}`

But it doesn't work.

Any idea?

**Comment by noahlange** [comment]
Random gets you a single element from an array. AFAIK there's no built-in "shuffle" filter. You'll probably need to write a custom one.

```javascript
import { shuffle } from 'lodash';

export default function shuffle(arr) {
  return shuffle(arr);
}
```

```javascript
```

**Comment by zetareticoli** [comment]
So I need to proceed as follows:

1. Create new shuffle filter using external lib lodash (new file .js?)
2. Import new filter (where?)
3. Use filter in .njk file

**Comment by noahlange** [comment]
1. You could theoretically stuff it all into the same file you're building your Nunjucks environment in. For larger projects that could be an annoyance.
```javascript
import { Environment } from 'nunjucks';
import { shuffle } from 'lodash';

const env = new Environment();
env.addFilter('shuffle', arr => shuffle(arr));
```
2. This will depend on what platform you're using / what your module bundler is. You'll need to call `.addFilter` in whichever file you're `configure()`ing or instantiating your Environment.
3. Yup.

**Comment by fdintino** [comment]
Sounds like this request for support was resolved.
