### ISSUE TITLE
consult express' app.locals when rendering a template

### ISSUE THREAD

**Issue by Pomax** [mozilla/nunjucks#99]
when using expressjs's `res.render("...")` function, app.locals will be used to consult variables, however, using a nunjucks `getTemplate(..).render()`, there does not appear to be a way to have that happen, even after making sure nunjucks is bound to the express app using `env.express(app)`.

**Comment by AlexNodex** [comment]
Does this mean we can pass app to extensions and have the locals mutated properly before any rendering is called ?
