### ISSUE TITLE
print array from model

### ISSUE THREAD

**Issue by jmls** [mozilla/nunjucks#992]
let's say I have some data like

`{ foo: ["a","b","c"]}`

and I want that array to be exported exactly as is

`foo: [{{foo}}]`

gives me 

`foo: [a,b,c]`

how do I get it to keep the array "as is" (include the quotes) so that the end result looks like
` foo: ["a","b","c"]`

thanks

**Comment by ArmorDarks** [comment]
Use `dump` filter, like `{{ foo|dump }}`

**Comment by fdintino** [comment]
Closing, looks like this support issue was resolved.
