### ISSUE TITLE
Server-side render precompile API docs

### ISSUE THREAD

**Issue by aperaham** [mozilla/nunjucks#995]
It was not entirely obvious from reading the API docs that precompilation was not required nor was it recommended or supported for server-side (node/express) rendering. It was only after observing the precompiled template javascript code and searching through other github issues [https://github.com/mozilla/nunjucks/issues/499](https://github.com/mozilla/nunjucks/issues/499) that I was certain precompilation for server-side rendering would not be necessary. 

Looking for a definitive answer regarding the issue caused a few hours of confusion that I think could have been avoided with an explicit description in the docs for how templates are compiled and then cached on the server.

I would be happy to contribute a short passage to the API docs about server-side rendering if the community/moderators agree that the docs could use a bit more clarity on the topic. As it stands, I'm uncertain as to how many other users had the same question and came to the same conclusion. 

Thanks!

**Comment by fdintino** [comment]
@aperaham I'm never opposed to making things clearer in the docs. Though I'm not sure where it should go, perhaps in the FAQ? If you are offering, yes a pull request would be great!

**Comment by jordie23** [comment]
Put it here: https://mozilla.github.io/nunjucks/api.html#precompiling

State something like "precompiling isn't recommended/doesn't work for server-side". 

I just wasted a few hours on this too trying to speed up rendering only to find `window.` errors, which I guess means precompiling doesn't work in nodejs?

**Comment by aperaham** [comment]
Indeed, @jordie23, I noticed `window` being used in the compiled template code as well, which of course is not used in node. I think a short description in the FAQs and in the precompiling section of the api docs would be best. I'll submit a pull request soon.

**Comment by aperaham** [comment]
Pull request for updated FAQ: https://github.com/mozilla/nunjucks/pull/1009
